openequella/openEQUELLA

- Source/Plugins/Server/com.tle.core.reporting/build.sbt
Tested on a fresh build env / equella-deps without the reporting-common 6.2 dep and it appeared to work fine.
> #95 - removed the dep on the 6.2 version of reporting-common

- Source/Plugins/Server/com.tle.web.mycontent.files/resources/lang/i18n.properties
- Source/Plugins/Server/com.tle.web.mycontent.files/src/com/tle/web/myresource/MyResourceContributeSection.java
As the office.dll has not a compatible license we should remove it. If we do so, we can't build the msi file. The solution will be to provide instructions about how to build the msi file for the office integration to anyone that have the license to do it. this PR change the link to download the msi file to a link to the documentation.
> 98. To remove office dll from code we just point to the documentation instead to the msi file

- Source/Plugins/Controls/com.tle.web.wizard.controls/resources/web/js/dialog/controls.js
- Source/Plugins/Controls/com.tle.web.wizard.controls/resources/web/js/shufflelist.js
- Source/Plugins/Server/com.tle.web.wizard/src/com/tle/web/wizard/controls/CMultiCtrl.java
You can now enter pipes and percent characters in shuffle list and shuffle group controls.
The new delimiter is a "slippery when wet car" character, which has the added bonus that because it's unicode it won't even conflict with user-entered slippery when wet cars (it could happen...) since they are URL encoded in the JS.
Note that before this fix (and not noted in the original bug description), you could not enter unicode characters into the shuffle group controls and have them persisted properly.
> #269 Shuffle controls special chars

- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/reindex/ItemMetadataFilter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/ItemDaoImpl.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/dao/helpers/DMLPartitioner.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/type/HibernateCsvType.java
Resolution to https://github.com/equella/Equella/issues/229 : Resources will not be re-indexed when editing Resource Metadata ACLs in the Collection Definition Editor in the Administration Console
I still need to do some final testing on this, but looks to work on initial tests with Postgres so I wanted to get the basic idea of the fix out here for folks to review.
> Issue 229:  Use a wildcard search for the ItemMetadataFilter

- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/summary/section/attachment/AttachmentsSection.java
Simple change to allow all xml path results to be checked when determining restricted attachment display.
> #459 all restricted display attachments now display for a given path

- Source/Plugins/Core/com.equella.base/src/com/tle/core/TextExtracterExtension.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/handler/CappedBodyContentHandler.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/AbstractOffice2007Extracter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/HtmlExtracter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/MsExcelExtracter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/MsWordExtracter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PlainTextExtracter.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/guice/FreetextModule.java
- Source/Plugins/Core/com.equella.core/src/com/tle/freetext/TextExtracter.java
Initially explored a way to interrupt the indexer thread, but the Tika AutoParser doesn't acknowledge interrupts.  I ended up creating a 'capped' parse handler for the Tika parser so it won't run indefinitely.  
New `com.tle.core.freetext` > `optional.properties`:
```
textExtracter.parseDurationCap=30000
textExtracter.durationCheckFrequency=15
```
> #492 Parse duration cap implemented for PDFs

- Platform/Plugins/com.tle.platform.common/src/com/dytech/devlib/PropBagEx.java
- Source/Plugins/Core/com.equella.base/src/com/dytech/edge/common/PropBagWrapper.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/scripting/types/XmlScriptType.java
For issue #476 .
Logic is in place to return the parent and children of a given `XmlScriptType`.  I added in a `XmlScriptType.getName()` as well.  The scripting below outputs the expected values.  I chose to go with the call format of `node.getParent()` instead of `node.getParent(node)` or `xml.getParent(node)`.  Both ways functionally worked, so I opted for the simplified way. 
```
xml.set("lom/general/title", "a title");
xml.set("lom/general/description", "a desc");
var titleXml = xml.getSubtree("lom/general/title");
var descXml = xml.getSubtree("lom/general/description");
displayChildren(xml);
displayLineage(xml.getSubtree("lom/general/title"));
var temp = utils.newXmlDocument();
temp.set("/parent1/child1", "p1c1");
temp.set("/parent1/child2", "p1c2");
temp.set("/parent1/child3", …
```
> #476 XmlScriptType getParent and getChildren logic in place

- Platform/Plugins/com.tle.platform.common/src/com/dytech/devlib/PropBagEx.java
- Source/Plugins/Core/com.equella.base/src/com/dytech/edge/common/PropBagWrapper.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/wizard/controls/HTMLControl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/wizard/controls/HTMLCtrlWrapper.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/AbstractHTMLControl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/GroupsCtrl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/scripting/objects/ControlScriptObject.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/scripting/objects/impl/ControlScriptWrapper.java
History in #475.  Allows scripting to be 'aware' of which repeater node the control is in.
> #475 ControlScriptObject getParent and getIndex(child) implemented

- Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
The font size and spacing assigned to each drop down entry was too
large and so the lines of CSS that caused this were removed.
> Make course drop down entries more compact #632

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsList.scala
Group name of 'diagnostics' was singular, and thus not being picked up in the UI.  Fixed spelling.
> #578 Fixed spelling of group name for M.D.F.

- Source/Plugins/Core/com.equella.base/src/com/tle/web/api/search/interfaces/SearchResource.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/myresources/api/search/SearchMyResource.java
see #730 for discussion—remove reference to SOAP, make the documentation link more specific and useful
Second take at this—I've made the bugfix branch based off of `develop` rather than `master`. Let me know if it's still not right, I don't know a easier way to do this than to delete the old remote branch and try again.
> more precise 'where clause' docs link

- Source/Plugins/Core/com.equella.core/src/com/tle/web/activation/operation/BulkRolloverOperation.java
Previously, this screen simply did a date check to enable the execute
button. This commit also adds a check to ensure that the options page is
selected.
#557
> Bulk Rollover Activations - Premature execute button fix

- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WizardServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/PagesSection.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/RootWizardSection.java
#749 
* check items' mandatory fields are filled in or not in all pages before saving
* checking runs when contribute, edit and clone an item
* failed three auto-tests (TokenLoginTest, SearchSettingsTest and AdvancedScriptControlTests) due to other reasons. So Jolse suggested me put this PR first.
> Fixing saving items without mandatory fields filled in

- Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
On IE 11, the extra `DOCTYPE, <head/>, <html/> and <body/>` tags in the login notice caused issues that prevent the login notice from rendering properly. Removing the "fullpage" plugin from TinyMCE should resolve this, as this plugin's purpose is to add the page setup tags that cause this problem.
> Login Notice: Remove fullpage plugin that added doctype and html tags

- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/FileSystemService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/impl/FileSystemServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/LoginNoticeService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/impl/PreLoginNoticeResourceImpl.java
#660 
MIME type as a wildcard was sufficient for modern browsers, but not for IE11. Added a method to get the MIME type from login notice images to fix in IE11.
> Add MIME-type checker to FileSystemService

- autotest/OldTests/src/test/java/com/tle/webtests/test/searching/hierarchy/HierarchyTopicTest.java
- autotest/OldTests/testng-codebuild.yaml
#825 
Was checking result count when only looking for two specific results - caused intermittent test fails due to parallel tests not having cleaned up before this test starts. Changed test to look for the specific results instead.
> Fix HierarchyTopic Autotest

- Source/Plugins/Core/com.equella.admin/resources/lang/i18n-admin-console.properties
- Source/Plugins/Core/com.equella.admin/src/com/tle/admin/controls/cloudcontrol/CloudControlModel.java
#758 
* Fix the bug that a node picker is not correctly validated if it is mandatory.
* Put two spaces between the label text of a config and a asterisk if this config is mandatory.
> Validate node picker if it is mandatory

- Source/Plugins/Core/com.equella.core/src/com/tle/web/scorm/treeviewer/ScormTreeNavigationSection.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/RootItemFileSection.java
#841 
Note: The contents of the SCORM package are still logged with the
viewscorm.jsp link access. This change means that there is an 
additional audit log entry for the package itself with the referrer 
(eg Moodle `[MoodleURL]/course/view.php?id=123` or 
`[OEQinstURL]/searching.do` if navigated to in a OEQ search) link.
> Add getAuditEntry override for SCORM packages 

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/controls/universal/handlers/fileupload/StandardFileCreate.scala
When gathering metadata upon staging a file, the path is incorrect. This
causes tika to be unable to detect metadata.
Bug detected upon failure of WizardFileUploadProperties test.
> Fix gathering metadata pointing to wrong filepath

- Source/Plugins/Core/com.equella.core/js/package.json
- Source/Plugins/Core/com.equella.core/js/src/Uploads/UploadList.purs
- Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/cloudproviders/CloudWizardControl.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/controls/universal/UniversalWebControlNew.scala
* Use an API for getting the wizard state instead of having it come from inline page scripts
* Ensure that inline file uploads trigger re-syncing of the item state
> Make inline file uploads stay in sync with cloud control state

- buildspec.yml
Adding the task to build the import/export tools broke the build, as it was failing to find some files it needs to determine version etc.
Simply need to make sure we return the directory before the task, as the `publishBuildResults` assumes that. Seeing we only do one `cd` just went with `cd -`. If it was more involved, we go with `pushd` and `popd`.
> Fix CodeBuild Issue

- renovate.json
Finding lots of PRs, and with all the rebasing we've got tons of builds
happening. May also need to consider reconfiguring the rebase process
too.
I think this is how you're meant to do this. I'm following https://renovatebot.com/docs/reconfigure-renovate/
> Slow down Renovate

- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/factory/guice/HibernateFactoryModule.java
- Source/Server/equellaserver/src/com/tle/core/equella/runner/EQUELLAServer.java
An unimportant warning from Hikari that was previously displayed as a 
single line is now filling the build logs with stack traces since updating 
it in #918. After doing some digging it was determined that this 
warning is of no consequence, it is simply the postgres driver 
determining what it can and cannot do, and can therefore be safely 
suppressed.
> Set Hikari logging on build to error state

- Source/Plugins/Core/com.equella.core/resources/view/logon/logon.ftl
When images are aligned in a login notice, they use the float:left or float:right styles. Without overflow being hidden, this makes the image fall off the end of the login notice section. Hiding it forces the images to be in the correct place.
> Stop aligned images from falling off the end of the login notice

- Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.js
- Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.purs
- Source/Plugins/Core/com.equella.core/resources/web/css/ie11compat.css
- Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java
Resolves an issue in which switching to "Videos" or "Images" in the search tab would break the styles upon moving back to "Standard" ( which looked like this)
Now working as intended.
Also fixed an issue in which the menu icons would not render in IE11.
Also fixed an issue which would prevent the login notice editor from rendering in IE11.
> Allow new UI in IE11 to change CSS

- import-export-tool/build.gradle
One dependency required in the two tools is the package javax.xml.soap, which is no longer available from Java 9. So we need to add this dependency through Gradle, in order for users who use Java 9 or higher version to get them running properly.
> Fix Import/Export tools not running with JAVA 10

- Source/Plugins/Admin/com.tle.webstart.admin/src/com/tle/admin/boot/Bootstrap.java
- Source/Plugins/Admin/com.tle.webstart.admin/src/com/tle/admin/boot/LoginDialog.java
* Fix the bug that when users  type wrong credentials they can't see any error messages until they try a second time.
* The error message is highlighted in red and bold.
> Rework login dialog to display messages properly

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
- Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/react.ftl
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
* remove() isn't supported on IE11
* IE complains about extraneous </link> tags and invalid html (as it should)
* use <base> tag instead of baseURI
> IE11 fixes

- Source/Plugins/Admin/com.tle.web.adminconsole/plugin-jpf.xml
The reason why last fix was not working is because on Unstable, the way to access adminconsole.jar is different. Locally, the downloading request URL directly points to this file, however on Unstable, the URL points to another file (com.tle.web.adminconsole@1.0.0.jar) , which  results in different methods handling the URL. Thus, the way to calculate ETag is different, which causes the 400 HTTP response code.
After discussing with Jolse,  the best solution is to add the attribute of unpack in the corresponding JPF file. This helps extract the adminconsole.jar from  com.tle.web.adminconsole@1.0.0.jar and then adminconsole.jar is directly accessible. 
To test it, I closed Intellij, and started Equella by running those sbt commands, which are exactly what is done on Unstable. And the result …
> fix-etag-missing-from-unstable

- Source/Plugins/Core/com.equella.core/resources/web/css/ie11compat.css
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/cloudprovider/CloudProviderApi.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/activation/CourseResource.java
> More fixes for IE11 compatibility

- .travis.yml
On develop branch, change JDK used in Travis build to openjdk8, and remove the specified Ubuntu dist.
> Change to openjdk and remove Ubuntu dist for travis builds

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/SettingsResource.scala
Fixes an IE11 issue in which the UI switcher in the settings menu wouldn't show the correct switched state. Due to IE11 caching a GET request.
> IE11 Compatibility: Disable caching on UI API requests

- Source/Tools/UpgradeInstallation/src/com/tle/upgrade/UpgradeMain.java
- Source/Tools/UpgradeInstallation/src/com/tle/upgrade/upgraders/AddFreetextAnalyzerConfig.java
This PR aims to fix the issue that tle_upgrader does not include the language analyzer property in optional-config.properties. By fixing this, our clients can upgrade oEQ by using the tle_upgrader and use the new feature of  the language analyzer.
This issue was found by Charlie and tested by him as well.
> Add freetext analyzer config to upgrader

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
For read only wizard state calls, no need to save it back to session. The fact that it was outside of the sync block meant it was a race condition as well.
> Only save back to state if editing

- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardConnectorServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/editor/AbstractConnectorEditorSection.java
Issue:  #784 
Lang pack for Bb B2/WS was partial broken after package / i18n reorg.  Changed old method to match other existing integrations.
> #784 Wired in the Bb integ strings

- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/AbstractIndexEngine.java
- Source/Server/equellaserver/build.sbt
Using Reflections API to scan lucene JARs causes the similar issue described in https://github.com/ronmamo/reflections/issues/81#issue-95158893
An acceptable solution is to use Classgraph instead.
Both the oEQ Installer and Upgrader were tested, ensuring Tomcat stop complaining. Also the feature of using different language analyzers was tested.
> Replace reflections with classgraph

- Source/Plugins/Core/com.equella.core/js/package-lock.json
- Source/Plugins/Core/com.equella.core/js/package.json
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudAttachmentResourceExtension.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderService.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/UriTemplateService.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/package.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthclient/OAuthClientService.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/cloudproviders/CloudWizardControl.scala
- autotest/IntegTester/ps/package-lock.json
- autotest/IntegTester/ps/package.json
- autotest/IntegTester/ps/tsrc/registration.tsx
- autotest/Tests/src/test/scala/equellatests/restapi/cloudprovider/package.scala
These are the three breaking changes I suggested we include before release. All three are in different commits and could be cherry-picked.
* Use Basic Auth instead of form parameters in OAuth token requests
* Change baseurl variable to baseUrl to be consistent with JSON property
* Rename properties in registration from "uri" to "url"
> Cloud provider breaking changes

- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WebRepository.java
The FileSystemService has a few overloaded 'write' methods, but only one of those methods can generate MD5 hash. 
We have been using the one that doesn't generates MD5.
> Fix md5 of file attachment not saved

- .idea/codeStyles/Project.xml
- Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/events/SectionEvent.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/DuplicateDataSection.java
A bit background here: when the text field duplicate check is enabled, a warning will be given if duplicates are found. Users must tick the checkbox in 'Duplicate data'  page in order to publish.  However, if the item includes attachments and one or more attachments are of type 'Web Pages', then users will not be able to save even though they tick the checkbox.
> Fix textfield duplciates not allow saving item

- docker/Dockerfile
The new openjdk hash does not work well in Develop. So revert it to the old one which works.
> revert openjdk hash used in docker file

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
Allows for forced refresh of the state upon internal redirect, even if
the URL stays the same
> Add forceReRender prop to LegacyContentProps to prevent double save click bug

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Fix the double clicking bug in moderation. 
I have tested  contributing items (one or multiple pages with a cloud control), editing, cloning, new versioning, deleting and searching items, login/logout and a lots more. 
It has been working fine so far on my machine. If anybody can checkout and do some local experiments, that is really appreciated!!
> Fix moderation double clicking bug

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
So the problem with some actions not being triggered first go is because when the Purescript / Typescript conversion happened, the trigger for calling the legacy page submit API moved into React effect hook dependency list but it didn't take into account redirecting to the same URL. [LegacyPage.tsx](https://github.com/apereo/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx#L215)
In order to fix it properly we can use the "key" property of the react router location object, which will have a different value for each time a history location is pushed, thus it can trigger even with the same path and query.
The original fix is just a workaround which is checking for values very specific to the moderation page, however this problem will …
> Fix newUI same URL redirect bug

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/controls/universal/UniversalWebControlNew.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/universal/handlers/UrlHandler.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WizardServiceImpl.java
* add the feature of link attachment duplicate check
* update duplicate information when editing, replacing or deleting a link attachment
Please note that the duplicate warning message and duplicate data page now can be affected by both file and link attachments.
> link attachment duplicate check

- Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/PagesSection.java
There are two problems which combined to cause the "uuid" as title problem:
* The cloud provider xml is only sent to the server when the "validate" global jquery event is called - the save button doesn't trigger this when opening the "publish" dialog, so the form fields need to be setup in the "presubmit" handler
* The cloud provider xml is being used when it shouldn't be - it should only be used inside the 
`SectionEvent.PRIORITY_AFTER_EVENTS` queued event, as this event get cancelled by the publish buttons.
> Fix cloud provider / server side xml sync problems

- docker/Dockerfile
There were two issues:
1. The docker image was weighing in at 2.06G (now 1.28G)
2. A new docker image for a new build resulted in almost all the layers
having to be pulled - as they'd all change.
Large Docker Image
This was primarily caused by a double up of the layer which contained
the installed equella which was caused by the RUN statement after it had
been copied into the final equella image. But seeing this is a
multi-stage build with one stage dedicated to building / installing, it
made sense for it to completely finalise the installed equella directory
ready to copy into the final image.
To do this various logic was moved into the install 'stage' and effort
was also undertaken to minimise RUN statements.
Excessive layer churn
In docker each statement in a Dockerfile creates a …
> Minimise docker image size and optimise layer order

- Source/Server/equellaserver/build.sbt
This bouncycastle dependency was conflicting with GitHub classpath (used in the recent multi-language stemming support update) and stops the installerZip from building. 
After looking into it, it was discovered that this dependency is not directly used in the code, and removing it allows installerZip to work. We'll see how the CI goes with it.
> Remove unused bouncycastle dependency

- Source/Plugins/Core/com.equella.core/resources/view/harvestlist.ftl
- Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/react.ftl
Allows DiscoverabilityTest - Harvest test to work in the new UI, and
also makes the harvest.do links appear as links in the new UI. Up 
until now, they were just text.
> Fix invalid <a/> tag in harvestlist.ftl, add robots meta tag to new UI

- autotest/OldTests/src/test/java/com/tle/webtests/test/usersscripts/UserScriptTest.java
This test fails in new UI due to the form of creating scripts keeps its fields' values regardless of saving or cancelling.
The associated issue is #1150 
So let's make the UserScriptTest pass in new UI firstly.
> make UserScriptTest pass in new UI

- autotest/OldTests/src/test/java/com/tle/webtests/test/drm/DRMPrivilegeTest.java
There is a bug in the new UI which prevents navigating directly (via URL or fullscreen button) to an attachment that has DRM. In the old UI, the DRM agreement prompt would pop up, in the new UI it simply says that the item does not exist.
> Make DRMPrivilegeTest pass in the new UI

- autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/AbstractRestApiTest.java
Common issue with many of the rest tests in the new UI is the check for a token was called before the token existed.
> Make the getToken method wait for a token

- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/controls/asc/AdvancedScriptControlTests.java
This test fails due to the Selenium click() does not wait for ajax request completed.
So adding a proper waiting can fix it.
> make AdvancedScriptControlTest pass in new UI

- autotest/OldTests/src/test/java/com/tle/webtests/test/drm/DRMTest.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/LinkPage.java
Related to #1160. Fullscreen does not currently work for attachments with DRM in the new UI.
> Make DRMTest pass in the new UI

- autotest/OldTests/src/test/java/com/tle/webtests/test/searching/SearchSettingsTest.java
This test failed due to the Screen Option. More details are logged here #1162  .
In addition, I think we can keep this fix even though #1162 is fixed.
> make SearchSettingTest pass in new UI

- Source/Plugins/Core/com.equella.core/js/package.json
- Source/Plugins/Core/com.equella.core/js/tsrc/components/AppBarQuery.tsx
Debounce the search  functionality in new search UI to improve user experience.
A search is triggered after user stops typing for half second.
Successfully tested with throttling in local environment.
> Fix the slow typing issue in new search UI

- autotest/OldTests/src/test/java/com/tle/webtests/test/drm/DRMTest.java
This test failed in Legacy UI because of a unnecessary URL parameter.
Not sure why @SammyIsConfused  added this parameter, but removing it does make the test pass in both Legacy and new UI locally.
> remove unnecessary URL parameters

- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/replicatedcache/impl/ReplicatedCacheServiceImpl.java
1. In clustering environment, the ECS registration token is stored in the database, and the token will be deleted from the database once it is used.
2. Say node1 generates a token, then the only way that node 2 and 3 can know this token is to grab the token from the database, because oEQ uses Guava cache which does not support being shared among instances.
3. According to [the guava cache api](https://guava.dev/releases/19.0/api/docs/com/google/common/cache/LoadingCache.html#refresh(K)), refreshing the cache will call the CacheLoader's load method, and this method is where reading the token from the database was implemented before. Therefore, each node is able to know the token is the token is available
> Fix ECS registration token issue

- Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java
- buildspec.yml
Fixed an issue with https://github.com/openequella/openEQUELLA/pull/878 in which the styles.css was wrongly moved out of the oldLayout, causing graphical issues. Tested that it still works in IE11.
> Fix incorrectly prerendering styles.css in new layout

- .travis.yml
- ci/coverage-save-results.sh
- ci/oldtests-save-results.sh
- ci/s3cp.sh
- ci/scalacheck-save-results.sh
- ci/tests-save-screenshots.sh
As a security measure [Travis CI removes encrypted variables for builds on forks][1]. To support this, here we now wrap calls to `aws s3 cp` to check that required env vars are present. If they're not, copying is skipped.
However, S3 was also used to share the installer across all the test jobs. To still have the possibility of running the tests against fork PRs I've added code to use the new(ish) [Travis Workspaces][2]. But it should be noted this feature is still Beta, so I hope it works. :crossed_fingers: 
Assuming this build all works fine on this PR. The next test will have to be after it's merged to develop to see if the build still copies all bits to S3 nicely.
[1]: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
[2]: …
> Add support for forks to the Travis CI Build

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
In IE11, this GET request is getting incorrectly cached, which breaks cloud controls (since without a wizard state update, cloud controls cannot react to file uploads on the same page as them without a refresh) and could potentially affect non-ECS areas too, since this API is regularly called by wizards. I've seen this happen in a non-cloud control collection, although since the collection did not need to react directly to the file upload, it had no (visible) effect on the functionality.
Modern browsers never cache GET requests, and so this will simply match what happens in other browsers in IE11.
#1218
> Add NoCache to wizard state update api

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
Another roadblock caused by IE11's caching. related to #1218
> Add NoCache to wizard state provider api

- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/CEditBox.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WebRepository.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WizardServiceImpl.java
Charlie's testing for the Duplicate data page found one problem about showing the title of each editbox that has duplicates. 
At the moment, the name of the schema node is being displayed on the Duplicate data page rather than each editbox's title. For example, in the below image, 'duplicatesinhere' is the node name, not the editbox's name.
So this PR fixes this problem.
> Display editbox's title rather than the name of schema node in the duplicate data page

- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/AttachmentDao.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/AttachmentDaoImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/quickupload/service/impl/QuickUploadServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WizardServiceImpl.java
At the moment, if a file attachment has been published and then when editing this file, the duplicate warning appears despite no duplicates being really found. This is because duplicates are found by the file MD5 and the file itself is in the result list. So the duplicate check treats the file itself as a duplicate. 
So this PR aims to fix this issue by excluding the file itself if it has been published.
> Fix the bug that the file attachment check treats the file itself as a duplicate

- Source/Plugins/Core/com.equella.core/test/java/com/tle/core/freetext/index/LanguageConfigurationTest.java
This test checks if a correct Lucene language analyser is instantiated by Classgraph, based on the language configuration.
Also, I will check if this test gets running on Travis CI.
> Add a unit test for the language configuration feature

- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/ItemFilestoreServlet.java
Solves #1181. The original method for file attachment cache validation was to use a max age parameter, which meant that modifying a file but maintaining its filename would cause stale preview images. Using a checksum instead forces the invalidation should the file content change. 
> Replace max-age with Etag checksum check to fix attachment preview caching

- buildspec.yml
Previous work of oEQ version checking adds a new build command to run 'npm test' in the `Buildspec.yml` file.
This command however causes a problem that the directory where `publishBuildResult` gets running is wrong. 
So need to slightly change the new build command,making it gets running in a subshell.
> Run the npm test in a subshell so it does not change the directory

- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/summary/content/ChangeOwnershipContentSection.java
This feature was previously done in the `Item summary` and `Moderation history` pages. We also want the last owner's details displayed instead of 'unknown user' in the `ownership change` page.
#726
> Display last owner's details in the ownership change page

- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/ItemFilestoreServlet.java
Set the value of `max-age` to 0 so that the browser will send a request to server all the time. Then the server will check `Last-Modified` of the attachment, which does not cost too many resources.
#1181
> Disable the browser's cache for attachments

- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/SearchQuerySection.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/standard/Tree.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/standard/model/HtmlTreeServer.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/page/WizardPage.java
The controls of the advanced search were only being added at render time, missing the all the event handler code.  The change ensures that the controls are added earlier on in the process.
Some dead code was also removed in Tree.java
#1309
> Ensure advanced search controls added to tree when editing params

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
#1313 
According to my investigation, this bug is caused because the the route to the Item Summary page is considered as an external route due to the new function `isClientPath` in LegacyContentApi. 
This function  only marks Urls which end with '.do' as internal routes, excluding 'logon.do'. However, routes to the Item Summary page (e.g. http://localhost:8080/charlie/items/802798b4-5bf8-4b70-b7d5-4c91d366386a/1/)  should also be internal ones.
So the proposed (and maybe the safest) fix is to let `isClientPath` mark the Urls of  Item Summary page as internal routes.
Lastly, in terms of why this bug only happens in one page collection, the answer could be found from line 88 - 99 of `index.tsx` .
> Fix the alert dialog bug when publishing items

- docker/Dockerfile
- docker/docker-compose.yml
Previous work was done to set up a clustered environment of oEQ. However to use a different version of oEQ requires manually changing the argument `OEQ_INSTALL_FILE`  in the Dockerfile, which is not what we want.
Instead, it is good to specify the installer file name in the `docker-compose.yml` file.
> Enable docker-compose to specify oEQ installer version

- Source/Plugins/Core/com.equella.base/src/com/tle/common/taxonomy/terms/Term.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/taxonomy/impl/TermDaoImpl.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/TaxonomyApiTest.java
#1225 
The problem I found is when sort from a top level, the indexes of each direct child node's are properly changed. However, if any child node also has its own children, indexes of these children are not changed accordingly. Therefore the order of all nodes is messed up. 
So the proposed fix is to walk through the tree and update all affected nodes's indexes.
Please note that the order of grandchildren is not changed (this is the feature of sorting all nodes).
> Update indexes of child nodes when sort from a top level

- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/AttachmentDaoImpl.java
The issue this PR aims to fix is related to the RDA feature Attachment Duplicate Checking.
There is not a specific Github issue related however.
At the moment, the Attachment Duplicate Checking excludes items that are with status of Deleted, Rejected or Suspended. In order to make it consistent with the Field Duplicate Checking, archived items should be excluded.
I remember @abidingotter mentioned `SimpleDBA` would get involved in this fix, but I have not found any change about `SimpleDBA` is required. 
Also please note this change will make differences on another functionality called `QuickUpload`. I checked the code and discussed with Charlie, and we are confident that this change will not break `QuickUpload`
> Exclude archived items for attachment duplicate checking

- Source/Plugins/Core/com.equella.core/src/com/tle/core/filesystem/staging/service/impl/StagingServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/scheduler/impl/SchedulerModule.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/scheduler/standard/task/RemoveStagingAreas.java
Allows a system admin to turn off the `RemoveStagingAreas` via the boolean system-level config `com.tle.core.tasks.RemoveStagingAreas.enable` in `optional-config.properties`.  Also adding more file audit logging.  
This will affect both the background task and the manual invocation via `/access/scheduledtasksdebug.do`.  Didn't seem like a clean way to allow the manual and block the background method, and this _should_ be a rarely used configuration.
Issue: #1344 
> Added config to disable RemoveStagingAreas

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/react.ftl
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/DiscoverabilityTest.java
#1148 
With the New UI turned on,  meta tags for discoverability are missing and two test (`metaTest` and `validatationTest`) have been skipped in the New UI due to this issue.
This PR aims to fix this issue by passing the tags from back-end to front-end through `LegacyConetent` and then use React hook to dynamically control these tags.
Although there are no new tests against this fix, the two previously skipped tests are re enabled to work for these changes.
> Add meta tags for discoverability into the HTML head tag

- Source/Plugins/Core/com.equella.core/resources/web/scripts/cloud.js
The cloud search sends an AJAX request to the server before various React components have been rendered on the page. This means that the screen options div is not present when the cloud search collects all the form elements on the page to submit to the server.
The fix is to do a setTimeout(..., 0) so that the AJAX request does not happen until all the rendering scripts have occurred.
#1162 
> Delay the cloud search until after page rendered by React

- .github/stale.yml
Some have commented Stale Bot is a bit too active. Now that we've
worked our way through old possibly out of date issues from initial
migrations etc, let's double the duration between triggers.
Also: Sorted the list of labels.
> Decrease frequency of Stale Bot activities

- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/user/impl/UserServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/usermanagement/standard/dao/impl/UserInfoBackupDaoImpl.java
Add @Transactional attributes to relevant methods so that Hibernate doesn't surprise us with random saving of objects later on.
#1367 
> Add appropriate @Transactional attributes

- Source/Plugins/Core/com.equella.admin/src/com/tle/admin/taxonomy/tool/internal/TermTree.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/taxonomy/TaxonomyConstants.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/taxonomy/terms/Term.java
Prevent user from entering the ! character in a new term as it used as an escape character in an internal LIKE query.
> Disallow the special like escape character in the taxonomy UI

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/customisation/RootThemeSection.java
#1184 
1. Support `customer.css` in the New UI;
2. Fix the issue that the `Themes settings` page displays wrong things
Please note once a customer CSS file is uploaded or removed, a force refresh is required to reload the CSS file.
> Ensure 'customer.css' is loaded in the New UI;

- buildspec.yml
Recently, Codebuild has failed several times due to the directory for publishing build results being wrong. We do not know why this is happening yet, but we can avoid it by removing `cd -` after building the import/export tools
> Do not use 'cd -' after building import-export-tool

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
- autotest/IntegTester/ps/www/control.tsx
- autotest/IntegTester/src/main/scala/integtester/testprovider/TestingCloudProvider.scala
#1369 
Add a REST endpoint in oEQ so that Cloud Provider Proxy can handle Delete requests;
Add a REST endpoint in IntegTester to respond to Delete requests.
Please note that some Header information is missing. Tom suggests we raise another ticket and fix it.
Also I feel it's better to open another PR which will include autotests for these proxy functions.
> Enable Cloud Provider Proxy to handle Delete requests

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
A bug in the new UI causes this drop down selector in the screen options to duplicate each time a new page that contains screen options is opened. The issue looks like this.
This happens because the screen options component rerenders incorrectly. I fixed this by tying the key of the screen options component to the page contentId.
> Stop duplication issue in screen options

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
- autotest/IntegTester/ps/www/control.tsx
- autotest/IntegTester/src/main/scala/integtester/testprovider/TestingCloudProvider.scala
#1414 #1413 
1. Add a new REST endpoint to support PUT requests through Cloud Provider proxy;
2. Include HTTP headers in Cloud Provider proxy (JSESSIONID is dropped).
> Create a REST endpoint to handle Cloud Provider Proxy PUT requests;

- .travis.yml
- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/user/impl/UserServiceImpl.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/cal/CALActivationsRolloverTest.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/controls/PackageAndNavigationTest.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/controls/asc/AdvancedScriptControlTests.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/dashboard/PortalsTest.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/viewing/ItemSummaryTest.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/AbstractPage.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/portal/AbstractPortalSection.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/portal/RecentContributionsEditPage.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/portal/RecentContributionsSection.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/tasklist/ModerationView.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/viewitem/PackageViewer.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/AbstractWizardControlPage.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/AbstractWizardTab.java
- autotest/Tests/src/test/scala/equellatests/pages/LoginNoticePage.scala
- autotest/travis.conf
This PR aims to make the Selenium tests more stable. 
PackageAndNavigationTest is less likely to fail. This test was very stable before the version 79 of Chrome . Although we use the beta version Chrome and make some changes, this test can still fail intermittently. So this test should become stable again once the next stable version of Chrome is available.
PortalsTest and AdvancedScriptingControlTest are less likely to fail.
For the oEQ installing issue (only failed on Travis), just need more builds to verify the fix.
For the Scala tests which sometimes fail on Codebuild, it should not happen any more.
> fix functional tests

- Source/Plugins/Core/com.equella.core/resources/view/swagger.ftl
This fixes the broken link to the openEQUELLA docs site was incorrectly pointing to equella.github.io rather than openequella.github.io. 
#1430
> Update the incorrect link in the apidocs.do page

- Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
- n/a tests are included
- n/a documentation is changed or added
A CSS workaround that was required for previous versions of Firefox is no longer required, so it was removed.
#1010 
Fixed buttons:
> Remove Firefox workaround that is no longer required

- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeHandler.java
Change the generated YouTube video URLs to the new format.  
Note: tests could be made, but we'd need to create a page object for the YouTube video page, which would take a while and it could change at any time.  I deem it not worth the time and effort for such a minor bug.
#1087
> Fix Youtube view links

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/standard/renderers/ImageRenderer.java
- Add alt tags to the logo (including in the theme editor page)
- Change the ImageRenderer such that if the alt tag is null or empty, the image src becomes the alt tag rather than just an empty string.
> Accessibility: Add alt tags where they are missing

- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/standard/controls/Repeater.java
Adds title attributes to the move up/move down/delete buttons in wizard repeater controls.
> Add titles to the move and delete repeater buttons

- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
- Source/Plugins/Core/com.equella.core/resources/view/editbox.ftl
- Source/Plugins/Core/com.equella.core/resources/view/universalattachmentlist.ftl
The "Duplicate Warning!" string for attachment and editbox duplicates should have role=alert as an attribute for accessibility reasons (So that a screen reader should prioritise those on the readout)
> Add role=alert to the Duplicate Warning string

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
The Save button changes in the EBP caused the save button to be slightly too wide for the page, causing an unnecessary horizontal scrollbar. 
> Accessibility: Set width of the save button to remove horizontal scroll bar

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
The move up, move down and delete icons in the repeater control were not visible in the new UI post EBP.  This PR fixes that by using the material UI icons.
> Add material Icons to repeater buttons

- Source/Plugins/Core/com.equella.core/src/com/tle/web/search/itemlist/ThumbnailDisplay.java
This sets the img tag alt for thumbnails to be the image fiilename. 
> Accessibility: Set the image alt in the ThumbnailDisplay.java

- Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/standard/renderers/TextFieldRenderer.java
Add aria-label to search bar (actually, any textfield rendered by the TextFieldRenderer that has a placeholder attribute).
> Add aria-label to searchbar

- Source/Plugins/Core/com.equella.core/src/com/tle/web/hierarchy/section/TopicDisplaySection.java
#1465 
Navigating through hierarchy topic links in the new ui were being treated as an update to the existing page content, instead of an internal redirect.
This change forces a redirect, so each topic gets a route, and a subsequent entry in the browser history object. SO the back button is behaving as expected. 
Based on my initial testing this change doesn't break the old ui, but it needs some slightly more in-depth testing
> force redirect for hierarchy topics, to get the back button working properly in the new ui

- Source/Plugins/Core/com.equella.core/resources/view/logon/logon.ftl
#1432 
Very minor one here, just adding the role='alert' to error messages on the login page that I forgot the first time around 
> add role attribute to login error messages

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1432 
This is fixing a change I made during EBP. The display of the buttons in the footer of a fancybox dialog now match the html markup
> fix dialog footer button css

- Source/Server/equellaserver/build.sbt
#1479 - Removed the `jetty-utils` dependency.  It was needing an upgrade, but didn't look to be used anywhere.
> #1479:  Remove jetty-utils dep

- Source/Server/equellaserver/build.sbt
#1317 
Upgrade the Jackson deps to 2.10.2 (which also matches the Jackson version in the admin console).
Locally, I didn't see the sbt deduplication issues mentioned in the ticket.  We'll see how the CI builds turn out.
> #1317 upgrade Jackson to 2.10.2

- Source/Plugins/Core/com.equella.core/src/com/tle/core/favourites/bean/FavouriteSearch.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/favourites/service/FavouriteSearchServiceImpl.java
#1280 
After discussing with @mrblippy , we think the best fix is to check and rewrite the URL of favourite searches because it doesn't require data migration. Maybe there are different approaches, but some significant changes would be required. 
In terms of why the redirection Servlet not working, it is probably because clicking the favourite search link triggers a tree check before it sends the request.
> Fix "no tree for xxx" error caused by favourite search links

- .travis.yml
- autotest/travis.conf
#1401 
As the latest stable version of Chromium Browser and Driver are available on Ubuntu Package, we don't use beta version of Chrome and download the Driver.
#1401
> Use APT provided Chromium Browser and Driver

- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
Updated the links to the documentation landing page in the footers to openequella.github.com and bumped the copyright year to 2020.
> chore: update links and copyright year

- Source/Plugins/Core/com.equella.admin/src/com/dytech/edge/admin/wizard/WizardHelper.java
- Source/Plugins/Core/com.equella.admin/src/com/dytech/edge/admin/wizard/WizardTree.java
- Source/Plugins/Core/com.equella.admin/src/com/dytech/edge/admin/wizard/XStreamDataConverter.java
- Source/Plugins/Core/com.equella.admin/src/com/tle/admin/collection/summarydisplay/BasicConfig.java
- Source/Plugins/Core/com.equella.admin/src/com/tle/admin/collection/summarydisplay/DisplayNodesConfig.java
- Source/Plugins/Core/com.equella.admin/src/com/tle/admin/itemdefinition/ItemSummaryTemplateTab.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/security/streaming/XStreamSecurityManager.java
- Source/Plugins/Core/com.equella.base/src/com/tle/core/xstream/TLEXStream.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/item/ItemSummaryApi.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/harvester/EQUELLAProtocol.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/helper/AttachmentHelper.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/search/searchset/virtualisation/ManualListVirtualiser.java
- Source/Plugins/Core/com.equella.core/src/com/tle/mets/importerexporters/CustomMetsAttachmentImporterExporter.java
- Source/Plugins/Core/com.equella.core/test/java/com/tle/ims/metadata/AbstractMetadataMapperTester.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/equella/service/impl/InitialiserServiceImpl.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/xml/service/impl/XmlServiceImpl.java
- Source/Server/adminTool/src/com/tle/client/harness/ClientLauncher.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/adminconsole/AdminConsoleTest.java
Due to #1496 
In testing 2010.1-RC2, I noticed the error in the logs:
```
Security framework of XStream not initialized, XStream is probably vulnerable.
```
Looking closer at the [XStream release notes](https://x-stream.github.io/changes.html), I found:
```
Add XStream.setupDefaultSecurity to initialize security framework with defaults of XStream 1.5.x.
Emit error warning if security framework has not been initialized and the XStream instance is vulnerable to known exploits.
```
I searched for all invocations of XStream and piped them through a new class `com.equella.base...XStreamSecurityManager` and applied a policy that any class that starts with `com.tle` or `com.dytech` can be XStream'd, as well as the default security rules given by XStream.  All other classes should be blocked.
I …
> #1496 Apply XStream security configs

- Source/Plugins/Core/com.equella.core/src/com/tle/tomcat/service/impl/TomcatServiceImpl.java
- Source/Server/equellaserver/build.sbt
No-effective change to tomcat AJP connector to work with Tomcat 8.5.51.  This disables the mandatory secret for AJP connections.
> Release/2020.1.0 chore/update tomcat to 8 5 51

- Source/Plugins/Core/com.equella.core/js/tsconfig.json
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Enabling --strict enables --noImplicitAny, --noImplicitThis, --alwaysStrict, --strictBindCallApply, --strictNullChecks, --strictFunctionTypes and --strictPropertyInitialization
remove optional included automatically in --strict as well as an unneeded error suppression option.
> build: switch typescript into strict mode

- buildspec.yml
This was recently added to the Travis/OSS build (#1539), so we need it to match in the Edalex Codebuild.
Need to wait and see now if Codebuild agrees with the change. I did spin up the Codebuild docker image locally and try the commands first, so :crossed_fingers: .
> Codebuild: Use .nvmrc to control Node versions

- package-lock.json
- package.json
lint-staged offers a few niceties:
1. it has more concise and expressive pattern matching than pretty-quick or git-format-staged
2. it can run lint tasks in parallel
3. it offers more readable output in the cli
4. it is a single dependency instead of two dependencies
it maintains the same overall behavior as before, when files are staged, they are run through the linters.
the output from the linters are automatically staged as well, and the nicely formatted files are committed.
NOTE: Both lint-staged 10 and husky 4 require Node 10+
> style: replace git-format-staged and pretty-quick with lint-staged

- CONTRIBUTING.md
adds links to documentation for tooling used for creating pre-commit hooks and linting staged files.
related to https://github.com/openequella/openEQUELLA/pull/1556#issuecomment-602939419
> docs(contributing): add links to tools used to setup pre-commit hooks

- Source/Plugins/Core/com.equella.base/src/com/tle/common/settings/standard/SearchSettings.java
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/SearchSettingsModule.ts
- autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/SearchSettingApiTest.java
#1337 
As discussed, add two boolean flags to 'SearchSettings' for the configuration of Owner filter and Date-modified filter.
Also update the tsx 'SearchSettings' interface.
> Add the configuration of Owner filter and Date modified filter

- Source/Plugins/Core/com.equella.core/js/tsrc/acl/index.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderAddDialog.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderListPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/components/CourseSelect.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/config.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/course/EditCourse.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/course/SearchCourse.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/entity/index.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContentRenderer.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/encodequery.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- package.json
builds on #1557 
Sets a preference for using `let` and `const` over `var` in ts files.
Sets a preference for using `interface` over `type` for defining object structures.
> style: normalize use of let, const, and interface

- Source/Plugins/Core/com.equella.core/src/com/tle/tomcat/guice/TomcatModule.java
- Source/Plugins/Core/com.equella.core/src/com/tle/tomcat/service/impl/TomcatServiceImpl.java
- build.sbt
#1533 
2020.1.0 included tomcat 8.5.51 , and subsequently broke the AJP connector.
This PR fixes the AJP connector with the following:
`mandatory-config.properties` :
`ajp.secret.required` - it should be set to `false` for now.  Default is `true` since it's more secure
`ajp.address` - Default is `127.0.0.1`
Another configuration, `ajp.secret` , was added in, but should be considered a beta feature. The default value `ignore` of `ajp.secret` will do just that.
I am waiting to test `ajp.secret` until httpd 2.4.42+ is released into the repos - currently looks like it doesn't have full approval of the community.  It would be appreciated if folks in the community can confirm `ajp.secret` works with a different web server, and then `ajp.secret` can move out of beta.
Support for ajp secret in …
> Follow ups to GhostCat - AJP connector

- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsList.scala
#1337 
Create a new sub-category called Search filters under the new ‘Search’ category.
The Setting filter page will be developed in a different PR.
Also, I wonder if we need to change the description of this category (provided by Cath) because not only the MIME type filter but also the Owner filter and Date-modified filter will be included in the page.
> Add search filter category

- autotest/Tests/tests/cal/institution/items/90/63706-extra/activations.xml
CALPrivilegeTest has been not working since yesterday and the reason is one of the testing activate requests in this test was expired. So updating the testing activate request can fix this issue.
> Update the testing activate request for CALPrivilegeTest

- .travis.yml
- Source/Plugins/Core/com.equella.core/js/tsconfig.json
- Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/entity/index.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
- Source/Plugins/Core/com.equella.core/src/com/tle/web/core/filter/SameSiteFilter.java
- package-lock.json
- package.json
Parcel does not check types
> Parcel performs no type checking. You can use `tsc --noEmit` to have typescript check your files.
https://parceljs.org/typeScript.html
This sets up type checks as part of a new `check:ts-types` step.
> types: check typescript types during check process

- Source/Plugins/Core/com.equella.core/js/__tests__/versioncheck.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/__tests__/util/langstrings.test.ts
- package-lock.json
- package.json
~Builds on #1558, the changes specific to this PR are in ae2bb7898553cc4356a75ebeedb0146ff87f7d94~
edit: rebased off latest develop with previous changes merged
Adds the recommended and stylistic rules from https://github.com/jest-community/eslint-plugin-jest
as well as checking that `describe` and `it` are used consistently across the tests.
> test: lint jest scripts

- Source/Plugins/Core/com.equella.core/js/tsrc/components/CourseSelect.tsx
the type is representing a form event on an input element.
This also replaces `event.target` with `event.currentTarget` which in this case is the same.
But `currentTarget` has the advantage that it is known ahead of time, and therefore can be statically typed.
See https://stackoverflow.com/a/10086501
> types: replace any in course select

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/auth/Auth.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/remoting/resteasy/RestEasyServlet.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/AuthApiTest.java
- autotest/OldTests/testng-codebuild.yaml
- autotest/OldTests/testng-travis-webservices.yaml
Provides a simple REST auth endpoint for user (and cookie) based authentication (rather than token / OAuth), utilising existing authentication and authorization mechanisms as referenced from the current form based authentication process.
Testing was a little interesting, as this did not really fit within the current oEQ REST testing paradigm. So I also pushed this out into it's own package (including root package reflecting current situation).
#1656 
> Basic auth endpoint for REST

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/UISettings.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
When open New UI pages from Old UI, the UI setting does not get updated so New UI is still not enabled. But all the pages are rendered in new UI. This PR aims to fix this issue. I have not added any test for this yet.
`SettingsResource` is the reference for how to update UI Setting.
> Enable New UI when open tsx pages from Old UI

- autotest/Tests/src/main/java/com/tle/webtests/pageobject/portal/MenuSection.java
`testAutoLoggedIn`, which is part of `FavouriteItemsTest`, has been failing quite frequently on GHA. Since the error is  `NoSuchElementException` and the test is really simple, the first attempt to fix this issue is adding a explicit wait.
> Fix FavouriteItemsTest that fails frequently on GHA

- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/RootWizardSection.java
To ensure metadata attributed to hidden pages is not wiped by the
mandatory field check.
#1678 
The lost metadata was caused by the mandatory fields check - it would initialize all pages of a wizard. Since wizards can have visibility scripting, this caused issues with hidden pages initializing when they shouldn't, which wipes their metadata. 
Surrounding this initialisation with a check against isViewable() solves the issue whilst retaining mandatory field checking. 
> Contribution wizard lost metadata fix

- oeq-ts-rest-api/package.json
- oeq-ts-rest-api/rollup.config.js
- oeq-ts-rest-api/src/AxiosInstance.ts
- oeq-ts-rest-api/tsconfig.json
esModuleInterop has cascading effects, using it here means any libraries that depend on it must also use esModuleInterop.
In this case it was a small enough change that it can be removed, and downstream adopter(s) can choose to use interop or not.
~externalizing the node_modules means that downstream bundlers will need to resolve the `import` or `require` statements for packages which are dependencies, like Axios.
This allows downstream builds to automatically deduplicate dependencies which may be used by multiple packages.~
_edit_: it looks like because the commonjs resolver isn't included, rollup can't find any of the node modules anyway and it's behavior is to keep the import and soft error, meaning external isn't needed. …
> build: removes esModuleInterop

- Source/Plugins/Core/com.equella.core/js/package-lock.json
- oeq-ts-rest-api/package.json
So as to comply with recommendations by renovate at:
https://docs.renovatebot.com/dependency-pinning/#so-whats-best
First raised as part of #1722 
Manual testing of oEQ is still fine, and so is the execution of the npm run test for this module.
> chore: Unpin NPM deps for oeq-ts-rest-api

- oeq-ts-rest-api/package.json
- oeq-ts-rest-api/src/AxiosInstance.ts
- oeq-ts-rest-api/src/Common.ts
- oeq-ts-rest-api/src/Errors.ts
- oeq-ts-rest-api/src/Schema.ts
- oeq-ts-rest-api/src/Security.ts
- oeq-ts-rest-api/src/index.ts
- oeq-ts-rest-api/test/schema.test.ts
This adds support to the REST Client to be able to simply:
* List available schemas (`listSchemas`); and
* Get a specific schema (`getSchema(uuid)`).
It also includes a slight improvement to the error handling to include the standard oEQ error response within `ApiError`.
But this was painful! First, what one sees in the Swagger/apidocs for the expected models returned is mostly wrong. And the same goes if you niavely look at the method signature in the code for an endpoint.
oEQ does a whole lot of customisation for its responses, so even though the method signature might say it will return a certain type, that can not be relied on - and in the case of listing schemas is mostly wrong (it says `SchemaBean` but you with really get either a stripped down `BaseEntityBean` or the more full …
> Add support to the REST Client for retrieval of schemas

- Source/Plugins/Core/com.equella.core/js/__mocks__/getSchemaUuidResp.js
- Source/Plugins/Core/com.equella.core/js/__mocks__/getSchemasResp.js
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/schema/SchemaModule.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/schema/SchemaModule.ts
This adds a method to retrieve a specific schema (based on UUID) and generate a basic tree structure. It also provides a method to build the node path for a specified node.
The generated structure currently doesn't include the extra fields for leaf nodes (_type, _indexed, _field) as we wont yet be using them. But we can easily come back and add them when/if we need them.
I've included tests with the REST calls mocked out - including for the previous function rushed through to retrieve a list of schemas. They're basic, but at least give us some coverage for now.
I believe this completes the work needed for SchemaModule, (including related schema work in the REST client). So everything should be in place for @SammyIsConfused to finish off the schema browser.
#1337 
[contributor license …
> Add schema retrieval to SchemaModule.ts

- .idea/typescript-compiler.xml
- Source/Plugins/Core/com.equella.core/js/package.json
- Source/Plugins/Core/com.equella.core/js/tsconfig.json
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
Due to some runtime tweaking of paths etc, although the sourcemaps are
generated with `npm run dev:build` they didn't work - as the sourcemap
retrieval resulted in a 404. This meant you couldn't do TS/React level
debugging in browser or IDE. With this update, you now can.
I also removed the IntelliJ typescript-compiler.xml file to stop
IntelliJ spitting out duplicate .js and .jsx files alongside the .ts and
.tsx. (I may have done this on another branch too.)
> chore: Make sourcemaps work

- Source/Plugins/Core/com.equella.core/js/package-lock.json
- Source/Plugins/Core/com.equella.core/js/package.json
- Source/Plugins/Core/com.equella.core/js/tsrc/components/SearchSettingFormControl.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsListControl.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/ContentIndexSettings.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/SearchPageSettings.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/components/DefaultSortOrderSetting.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeList.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/UISettingEditor.tsx
- autotest/IntegTester/ps/package-lock.json
- autotest/IntegTester/ps/package.json
- autotest/IntegTester/ps/tsrc/cloud.tsx
- autotest/IntegTester/ps/tsrc/theme.tsx
- autotest/IntegTester/ps/tsrc/update.tsx
- autotest/IntegTester/ps/tsrc/viewitem.tsx
The two versions of material-ui/styles are for two different purposes - one is standalone and can be used in non-Material UI contexts, and the other is for material-ui projects. 
We were having some strange build issues with the dependency on @material-ui/styles being inaccessible. This change hopes to address that by migrating openEQUELLA to @material-ui/core/styles only. 
Also - in my IDE I was having some strange issues with errors being highlighted  in equella code from the version of material ui in the IntegTester not being the same as the one in the com.equella.core/js folder. So I matched those versions together by bumping up the IntegTester version.
> Use only @material-ui/core/styles and move away from standalone @material/styles

- .github/workflows/ci.yaml
Version 2 is now out of preview and has some fixes, so time to start using the official release. Hopefully will also address the upload issues as mentioned in #1792 .
> CI: Upgrade GHA artefact upload action

- Source/Plugins/Core/com.equella.base/src/com/tle/beans/user/UserInfoBackup.java
- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
- Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20202/RemoveLastKnownUserConstraint.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/user/impl/UserServiceImpl.java
#1619 
Removing the composite constraint (username and institution ID) from table `user_info_backup` allows users to login with a user account that was deleted but recreated later with the same username and different user id.
> Fix last known user constraint violation issue

- renovate.json
This makes the following changes to the renovate config:
* Increase PR limit from 10 to 20
* Allow a maximum of 2 PRs per hour (used to be 1)
* Enable automerging - devDependencies only
* Remove no longer supported config option
I think this would be worthwhile, as we have an increasing number of 'stuck' PRs so it'd be good to have some more headroom to progress the backlog. Further, with better CI it seems a good time to start trialling automerging.
For now automerging is just limited to devDependencies, on the premise they should be rather safe to bump along but require frequent updates and we should be able to see the value.
I have validated the config with:
npx -p renovate renovate-config-validator
(And indeed, it was with that I discovered with had a no longer supported option - so I …
> chore: reconfigure renovate bot - more throughput and automerge

- Source/Server/equellaserver/build.sbt
It would appear this may have just been added from conversion of the old
Ivy setup which didn't do transitive dependencies (so all had to be
managed explicitly in XML files). Having removed it, all still built and
ran via `sbt cleanrun`.
Done in response to https://github.com/openequella/openEQUELLA/pull/1892
> chore: Remove unused com.google.code.findbugs:jsr305

- Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchResult.stories.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- oeq-ts-rest-api/src/Search.ts
#1306 
Integrate search page with search result component and search module.
When opening the search page, search settings are retrieved first.  Then, a default search is done so that a list of items are displayed. 
To match the existing functionality in old Search UI, a couple of things are considered.
1. The default sort order is handled on server side (view `getOrderType` in `DefaultSearch.java` to get more details)  so client does not need to implement it again.
2. The default item status is 'live' and 'review' and it's handled on client.
> Integrate search page with search result component

- Source/Server/equellaserver/build.sbt
It would appear this may have just been added from conversion of the old
Ivy setup which didn't do transitive dependencies (so all had to be
managed explicitly in XML files). Having removed it, all still built and
ran via sbt cleanrun.
In response to https://github.com/openequella/openEQUELLA/pull/1698
> chore: Remove unused org.javassist:javassist

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> Fix AttachFile icon size in SearchResult component

- .github/workflows/ci.yaml
The uploading of the coverage reports was taking a very long time and
sometimes failing. I believe this is because the artefact upload action
wasn't really designed for uploading directories with tens of thousands
of files.
Considering the upload of the primary artefacts only takes a few minutes
(and is a few hundred megabytes), I'm assuming this will save us
significant time and shorten our test runs by about 50%.
> chore(ci): Prepackage coverage report

- Source/Server/equellaserver/build.sbt
It appears this was just added as part of the SBT migration.
In response to #1952 
> chore(deps): Remove unused stax2-api dependency

- Source/Plugins/Core/com.equella.core/js/__mocks__/getSearchResult.js
- Source/Plugins/Core/com.equella.core/js/__mocks__/searchresult_mock_data.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchResult.stories.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
- oeq-ts-rest-api/src/Search.ts
#1306 
Using a hyperlink to open Item Summary page results in reloading the whole page, so we instead use `Link` provided by react-router to avoid reloading whole page. Also include an Item's version in Search result so that client can generate the correct path for viewing each item.
> Redirect to Item by React Router

- Source/Plugins/Core/com.equella.base/src/com/tle/common/search/DefaultSearch.java
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
#1306 
The search triggered by opening the Search page should include the default search order configured in the Search settings page. Therefore, in the Search page, retrieve Search settings first, and then add `order` to search criteria.
For some unknown reasons (maybe just unknown to me), the order values have been inconsistent  for a long time. For example, in the context of Search settings, the value of order `Last modified date` is `datemodified`. However in the context of Search, the accepted value is 'modified'. Previously in Purescript, this was handled by a Purscript Map. More details can be seen from these two links [old search setting page](https://github.com/openequella/openEQUELLA/blob/master/Source/Plugins/Core/com.equella.core/src/com/tle/web/search/settings/SearchSettingsSe …
> Ensure the default search order is included in the first search

- Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsList.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsListHeading.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetedSearchSettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/SearchFilterSettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/theme/ColorPickerComponent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Well, this was one of those small little refactors that suddenly became a bit more... Not too much more, but.. you'll see.
The intention was to make `ThemePage` use the new `SettingsPageTemplate` and `SettingsList` so as to be consistent with our new settings work. That was achieved, however getting there got a bit tricker due to some bumps with the the `ColorPickerComponent`, so that ended up also getting refactored as well. It went from a class based component to a functional one, and rather than a pop-over is now a dialog (which is also more consistent), as well as some of it's oddities were removed and tidied up.
But also did some tweaking to `SettingsList` for a stronger heading, while also providing the heading as a stand-alone component. This was triggered by noting some of the …
> Refactor Theme Editor page to use the new standard SettingsPageTemplate

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
https://github.com/openequella/openEQUELLA/issues/1540
The main issue here was that <div id=col2> contains rouge whitespace. I couldn't find exactly what code was inserting that whitespace, so the lest risky option is to just alter the minimum width. I also altered some of the text size in the course selection panel so more information be displayed.
Also, I noticed that the sticky save button fix for #1524  had some poritioning issues when viewed inside a selection session, which I also fixed
_A note for whoever tests this, make sure the selectOrAdd selection session also still displays correctly_
> Fix structured selection session course panel display overflow issues

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchModule.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
#1306 
Add the feature of pagination to Search page. When change the page size or move to next/previous pages, a search is triggered.
> Add pagination to Search page and tweak SearchResult

- .idea/codeStyles/Project.xml
The `~*` file mapping in tsconfig for parcel to properly generate source
maps results in IntelliJ attempting to generate import statements like:
import SomeThing from "~adirectory/anotherdir/Something"
This fixes that, and results in import statements with proper relative
paths.
> chore(intellij): Ignore TS file mappings for imports

- oeq-ts-rest-api/src/Search.ts
The attachmentType is not always present in all items. This caused search
to fail due to type mismatch - found in the default vanilla institution.
This commit solves that issue.
> Make attachmentType optional to fix search issues

- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchOrderSelect.tsx
#1306 
Added a sorting control on Search page to allow sorting search results. The initially selected sort order is consistent with the default sort order configured on the Search setting page.
> Add sorting options for Search page

- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Adds the text "The LIST_SCHEMA permission is required to select a schema" underneath the schema selector.
> Add helpertext for the schema selector

- Source/Plugins/Core/com.equella.core/js/.storybook/preview-head.html
oEQ places a global variable logoURL via a script in the head of server
side rendered pages. This can then be accessed via the New UI pages
which are being tested with Storybook. So to ensure Storybook works,
this needs to be provided within Storybook.
Resolves #2013
> chore: Add global logoURL for Storybook

- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
In the screenshot, there are two places on the page reading "Search Results". Obviously this is redundant, so this PR removes the ListSubheader (the smaller grey one).
> Remove subheader in searchResultList

- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PostLoginNoticeConfigurator.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- autotest/Tests/src/test/scala/equellatests/pages/LoginNoticePage.scala
- autotest/Tests/src/test/scala/equellatests/tests/LoginNoticeMenuPropertiesSerial.scala
This is the second in a series following on from #1990 and is an attempt to standardise our settings pages with the new pattern established with the New Search UI work.
This work involved:
* Removal of tab layout for notice editors;
* Removal of custom save button and snackbar/notifications;
* Reworking save methods and handlers;
* Combining the two editors under the new SettingsPageTemplate instead; 
* Reworking the ScalaCheck tests - however this was nicely isolated in the Page class due to reasonable abstraction of processes
Attempted to fit in with what was there as much as possible and undertook minimal component level refactoring. And it seemed it had most of what was needed for triggers for the SettingsPageTemplate for prevent nav, etc.
There is a known existing issue with TinyMCE …
> Refactor the LoginNotice settings pages to use the new SettingsPageTemplate

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
#1306 
Added a spinner for the Search page. When the page is retrieving search settings or doing a search, show the spinner before those actions are completed. Where the spinner is positioned is dependent on if the search result list is empty or not.
> Add a spinner for Search page

- oeq-ts-rest-api/src/Collection.ts
- oeq-ts-rest-api/src/Common.ts
- oeq-ts-rest-api/src/Schema.ts
- oeq-ts-rest-api/src/Security.ts
- oeq-ts-rest-api/src/index.ts
- oeq-ts-rest-api/test/collection.test.ts
This adds support for the main GET endpoint to list oEQ Collections. This is initially needed so that we can provide a list of collections to filter search results by, however full support is provided here (including the use of the `full` flag).
This is _very_ similar to the Schema endpoint, and so we have a pattern now emerging. I think any BaseEntity related Resources will more or less follow this. But we'll want to see more - especially as we start to also edit them (so far we've only done retrievals).
> Add support for GET /api/collection to API module

- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/controls/PackageAndNavigationTest.java
Add RetryTest annotation to the tests inside PackageAndNavigationTest as they are persistently flakey.
> Add retries to PackageAndNavigationTest

- Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchBar.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Adds a toggle to the search page for "raw search" mode. 
- When raw search is off, search queries are de-bounced type-ahead, sent to the server side with an appended '*' wildcard
- When raw search is on, search queries are sent as-is, and only when you hit enter
- Helper-text to remind the user to hit Enter appears when in raw search mode
- Tool-tip appears when hovering on the toggle to explain the purpose of raw search mode
- Jest tests to assert that type-ahead and wildcard append happen in simple search mode
- Jest test to assert that type-ahead and wildcard append do not happen in raw search mode
> Add "Raw search" mode to new search UI

- Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchBar.stories.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
- Move raw search controls into SearchBar.tsx from SearchPage.tsx
- Use grid and styles to place the raw search control to the right hand side of the search bar rather than underneath, with some extra room for language string changes
> Refactor raw search into searchbar

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
Two new attachment properties have been added to the SearchHelper object, used by the search2 api endpoint:
- Mimetype (for file based attachments)
- isPlaceholderThumb: Indicates if an attachment does not yet have a generated thumbnail
The plan is to eventually use these two properties to display more pleasing thumbnails in the SearchResult frontend component
> Feature/search2 API attachment enhancements

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
WIldcard for simple search was getting incorrectly appended to empty search queries. This fix trims the query before sending it and only appends the wildcard for non-empty searches.
> Trim the search query and only append wildcard to non-empty queries

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
So as to be a bit cleaner, and similar to a number of Material Design
search bars you see about the place - so as to hopefully feel
contemporary to users.
Required custom styling, but I think that's acceptable in this case as
we wanted something a little different and it is a key/special component
as one of the main ones users interact with.
Note two changes:
1. I've made the search button on the left hand side clickable; and
2. I haven't included the button to clear a search - I really wanted to try and keep it as minimal and clean as needed. I figured between ESC and backspace users should have enough.... :thinking: 
#1306 
> Restyle new search bar

- Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchBar.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchModule.test.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
The main feature which was being implemented here was to remember what options a user has selected on a search page when they use the back button to return to a search. But also snuck in a quick couple of others (reduced prominence of raw mode toggle; and remove need to press enter when in raw search mode) following team review.
This became a bit more involved, as it was realised `SearchBar` was handling the state around raw mode itself - rather than pushing state up. As a result, `SearchBar` was refactored to use two way binding to support pushing this state up allowing it to be stored in history. However `SearchBar` does still maintain it's own internal state of the current query value to support debouncing of sending the new query value up.
In addition to state, it was also noted that …
> Remember search options when going 'back' to the search page

- Source/Plugins/Core/com.equella.core/js/.storybook/preview-head.html
- Source/Plugins/Core/com.equella.core/js/__stories__/components/MimeTypeFilterEditingDialog.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/components/RichEditor.stories.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
I'd started to notice a few broken bits in storybook (for example #2024). So I went through and clicked on all the stories to make sure they worked, and those which didn't I've addressed in this PR.
Of note, fixing `RichEditor.stories.tsx` at first seemed like it'd just be adding `renderData` to preview-head.html (to mimic how the oEQ server places that in the header). However once that problem was fixed, another more significant problem resulted which was TinyMCE unable to load its CSS.
This issue was due to the component attempting to use the dynamic configuration (from `renderData` and `Config`) to set a URL for where to download the CSS from. But this was tripping over using the default `href` on the `<base>` element which Storybook adds. So instead, I modified the component to have …
> Fix broken Storybook stories

- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> Make window scroll to top when search is performed

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaSelector.tsx
This PR attempts to remove lots of 'react-beautiful-dnd' warnings by using the approach discussed in 'react-beautiful-dnd' github.
This PR also addresses other warnings (e.g. MUI warning about uncontrolled component && Jest warning about using `act`) in this test.
> Refactor the Jest test of Faceted search settings page

- .github/workflows/ci.yaml
There is currently an issue we're having with GHA where the wrong commit
is built. This appears to be related to issue
https://github.com/actions/checkout/issues/237
There is a comment there from 4 days ago
(https://github.com/actions/checkout/issues/237#issuecomment-662662682)
where the issue is now acknowledged but it's noted as a complex issue
with no definite date for resolution.
Others have reverted to v1, so it seems worth trying - especially if the
availability of the fix seems to be an unknown (possibly long) time
away.
P.S. It seems mainly related to forks - so I think the Renovate PRs are okay.
> chore(ci): Revert GHA checkout action to v1

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/DateRangeSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/RefineSearchPanel.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
#1306 
Integrated the Date range selector with Search page. Also slightly changed to header of Refine panel.
> Integrate date range selector to search page

- Source/Plugins/Core/com.equella.core/js/package-lock.json
- oeq-ts-rest-api/.eslintrc.js
- oeq-ts-rest-api/package-lock.json
- oeq-ts-rest-api/package.json
- oeq-ts-rest-api/src/Common.ts
- oeq-ts-rest-api/src/UserQuery.ts
- oeq-ts-rest-api/src/Utils.ts
- oeq-ts-rest-api/src/index.ts
- oeq-ts-rest-api/test/TestConfig.ts
- oeq-ts-rest-api/test/UserQuery.test.ts
- oeq-ts-rest-api/test/search.test.ts
- oeq-ts-rest-api/test/utils.test.ts
Primarily the change here was to add support for the `/userquery/search` endpoint in the form of `UserQuery.ts`. But then when I noticed the formatting on my commits was not correct I added that support to the `oeq-ts-rest-api` module by applying the final tweaks to`oeq-ts-rest-api/package.json` and `oeq-ts-rest-api/.eslintrc.js`. On running that, suddenly I found many other files were also a bit out of wack.
So unfortunately this PR now contains a lot more noise than I'd like. Here is a run down to the help:
Feature (ccf789a):
* `UserQuery.ts`
* `UserQuery.test.ts`
* Auxillary: `Common.ts`, `index.ts`, `TestConfig.ts`
**Ran the tests:**
```
Test Suites: 7 passed, 7 total
Tests:       23 passed, 23 total
Snapshots:   0 total
Time:        4.905 s
Ran all test suites.
```
[contributor …
> oeq-ts-rest-api: Add support for /userquery/search

- Source/Plugins/Core/com.equella.core/js/tsrc/components/DateRangeSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/Date.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
#1306
Here are some improvements made for the Date range selector. However, the component becomes a lot more complicated accordingly. So I am still thinking if these improvements are worth to have. 
1. Used `KeyboardDatePicker` to allow type and clear a date. But in order to properly use it, `state` is required, which increases complexity.
2. Changed to default picker labels to `from` and `to`.
3. Added a util function to help convert a date object to a string in ISO format. The reason is Javascript native function `toISOString` changes the time to UTC time,  which may result in incorrect search results.
> Improve Date range selector

- Source/Plugins/Core/com.equella.core/js/tsrc/modules/UserModule.ts
This ended up being much simpler than I thought. And in the end it made no sense to really test when it'd be hitting mocked data. So here you have one new file with one simple functions that'll I'll then consume in my next PR - a search user component.
#1306 
> front-end: Add a module and function to list users

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
#1394 
When a attachment reordering is performed, a Legacy content request is sent and its response is an empty object. `LegacyContent.tsx` did not handle this case properly, which results in opening a `undefined` page. So this PR attempts to fix this issue and #1523 .
> Do not redirect if href is undefined

- Source/Plugins/Core/com.equella.core/js/tsrc/components/Date.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/Date.ts
We have recently updated  `@types/luxon` from 1.24.1 to 1.24.3 and the newer version has changed some functions' return types. (e.g. `string` -> `string | null`). So  this PR removed a couple incorrect null assignment.
> Do not assign null to undefined in Typescript.

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
#1735 
Fixed the resumption token used in some REST APIs. 
The testing environment for below screenshots has 5 items totally.
First request with initial resumption token being `0:2`. The length specified in params is ignored.
Second request with the token returned from last request
Third request with the token returned from last request. No more token is returned.
Another request with an initial token which can retrieve all items so no token returned.
Another request with an invalid token. So use the length from query params instead.
> Fix resumption token used in REST APIs

- Source/Plugins/Core/com.equella.core/js/__mocks__/getCollectionsResp.js
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/CollectionsModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/OEQHelpers.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SchemaModule.tsx
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
- oeq-ts-rest-api/src/Common.ts
#1306 
As the resumption token has been fixed, this PR attempts to update Schema module and Collection module to use resumption tokens to retrieve data.
Created a new function to list entities that extend `BaseEntity`, and then updated the two modules to use this function. Also updated mock data and renamed a field of `CommonParams`.
> Update Schema module and Collection module

- Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/service/impl/ThemeSettingsServiceImpl.java
#2107 
The issue was caused by the lastModified check on the legacy.scss file. 
Creating a new File() with getResource().getFile() worked fine in a dev environment - but in an installed oEQ
this file would be inside a jar and wouldn't work. The lastModified date would always return 0. 
This PR changes to use an URLConnection to the same file to grab the value and then close the stream, and I have tested this via installerZip. 
> EBP: Updates to legacy.scss do not show up properly until theme changes happen

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
Simple update to also show the number of search results at the top of the list.
#1306 
> front-end: Display count of search results

- .github/SECURITY.md
Adds security policy into .github/SECURITY.md, which GitHub automatically will associate with the security tab in the UI.
https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository
> docs: add security policy for openEquella

- Source/Plugins/Core/com.equella.base/src/com/tle/common/searching/Search.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/searching/VeryBasicSearch.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/ItemIndex.java
#1306  
This PR attempts to make the end of a date range inclusive in searches without making any change on the old Search page.
Also during the work, I found that in the old Search page, selected dates are always convert to UTC dates, which means the search results may be wrong. For example, if I select 1st Aug, the real date passed to Lucene is `31 July 14:00:00` because AEST is 10 hours ahead of UTC time. More info can be found in screenshots.
In new Search page: 
In old Search page:
> Make date range end inclusive in searches

- .idea/codeStyles/Project.xml
- Source/Plugins/Core/com.equella.core/js/__stories__/search/StatusSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/StatusSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/SearchPageSettings.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- oeq-ts-rest-api/package-lock.json
- oeq-ts-rest-api/package.json
- oeq-ts-rest-api/src/Common.ts
- oeq-ts-rest-api/test/search.test.ts
Another Refine Search control, this time for status.
Also needed to refactor the `OEQ.Common.ItemStatus` from an `enum` to essentially a string literal union. Triggered due to issues with Jest losing visibility of the enum post transpilation. To provide the full power I was after, rather than just a plain ol' string literal union, I brought in [runtypes](https://www.npmjs.com/package/runtypes).
Further auxilary items:
* A wording change for the configuration of whether to display this control - previously worded around non-live statuses;
* For IntelliJ project turned on sort imports by module - so that <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>o</kbd> gives a nice tidy up (which was done in some files); and
* Sorted the sub groups of the Search Page language strings, as it was become rather …
> Refine Search - StatusSelector

- Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/theme/index.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/newuitheme/impl/NewUITheme.java
I noticed it was not possible to properly setup a dark theme as the cards were fixed at white. So this change supports being able to theme the colour of the cards, as well as some minor tweaks to the look of EBP cards.
(We may want to cherry-pick the EBP commit 45f43de back to `develop` with the other EBP updates.)
> Support being able to set the theme for the paper / card elements

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/service/FreeTextService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/service/impl/FreeTextServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/freetext/FreetextIndex.java
- Source/Plugins/Core/com.equella.core/src/com/tle/freetext/FreetextIndexImpl.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
#1306 
This PR includes back-end changes for the feature of whether to search attachments or not. As we don't want to use `User Preference` to check if the option of searching attachments is enabled, added a new search param which represents the option, and overloaded method  `search` to accept a boolean.
> Add the support of whether to search attachments to Search2 API

- Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchAttachmentsSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchAttachmentsSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/search.test.ts
#1306 
So here is another Refine Search control - Search attachment Selector. By default, the option of 'yes' is selected. And because there are no Search settings controlling this component's visibility, it's always visible. 
The structure of this component is almost same as `StatusSelector`, and so are its tests and stories. So we can create an abstract component called `TwoOptionsSelector` , but I am not sure how much value we will gain at this stage so I did not implement this.
> Search attachment Selector

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983  
Margins were off for side-by-side portlets- the leftmost portlet merged into the rightmost one. This simply adds a margin to the right of each portlet.
> EBP: Add margin to the right of portlets

- oeq-ts-rest-api/src/AxiosInstance.ts
- oeq-ts-rest-api/src/SearchFacets.ts
- oeq-ts-rest-api/src/Utils.ts
- oeq-ts-rest-api/test/Search.test.ts
- oeq-ts-rest-api/test/Utils.test.ts
An incorrect assumption was made back in 861e4b1, and due to a missing test didn't realise this broke `searchItems`. So this PR reverts 861e4b1 and does it differently, as well as adding a test of `searchItems` for the missing coverage. (Although it looks like we could do with a fair bit more testing there.)
> Fix support for CsvList params in SearchFacets

- Source/Plugins/Core/com.equella.core/js/__mocks__/FacetSelector.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/search/FacetSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchFacetsModule.test.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
#1306 
Here is another refine control - Facet Selector.  A new type representing Search page specific Classifications was firstly added in `SearchPage.tsx`.  A function transforming standard Classifications to the Search page Classifications was also added in and will be consumed in the next integration. 
The component does not have its own state so at this stage only props changes can trigger a re-render. 
Jest tests and Storybooks for this component are also included.
> Feature/Facet Selector

- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
- Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20202/RemoveLastKnownUserConstraint.java
#2210 
The PR fixes the bug about failing to upgrade from `2019.2.4` or `2020.1.3` to 2020.2 . The approach is to let 2020.2 replace both  `v20192` and `v20201` of `RemoveLastKnownUserConstraint`  with the `v20202` one.
I can locally upgrade from 2019.2.4 to 2020.2 and upgrade from 2020.1.3 to 2020.2 without the errors.
> Fix migration issue caused by 'RemoveLastKnownUserConstraint'

- Source/Plugins/Core/com.equella.base/src/com/tle/common/search/DefaultSearch.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResult.scala
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
In the New Search UI we plan to highlight matching terms as they were done in the legacy UI. To emulate this, we need the search endpoint to return the list of words to highlight based on the query. This here PR does that.
As well as that, I did some minor unrelated refactoring of `DefaultSearch.QueryParser` as I was reading code - so I thought I might as well include it here (contained in ce0e9cc). Also while adding a test for this, I did some tidy-up of `Search2ApiTest`. And also as an aside, so that I could document the new `SearchResult` param, I also documented all the others.
> Modify /search2 to return a list of words to highlight

- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
#2210 
Previous fix can still cause trouble.
For example, on unstable, `v20202` of this migration has been applied,  but `v20192` and `v20201` are never applied. So database does not have records for these two migrations. As a result, the migration task finds two new migrations  `v20192` and `v20201` and try to run them, but fails because we don't actually provide matched files (beans) for them.
The builds in previous PR were green because none of `v20192`, `v20201` and `v20202` exist in the database. I am still not 100% sure the logic behind. From my understanding, the migration task should have found three migrations to run and failed due to the same reason, but it actually did succeed...
But anyway, the solution is to make sure  `v20192` and `v20201` have an available bean in 2020.2. …
> Ensure no more complaints about migration for last known owner

- Source/Plugins/Core/com.equella.core/js/__mocks__/SearchResult.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchResultList.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/Search.test.ts
This mainly adds support to `oeq-ts-rest-api` to support the new `highlight` array which comes back from the search2 endpoint. In doing this though I noticed the return type for `search` was the `Common.PagedResult<T>` which does not match the server - and even has the `resumptionToken` which search2 does not use.
So inline with the Server definition I also created a specialised interface (`SearchResult`), one that didn't have a `resumptionToken` and instead does have a `highlight[]`. I could have looked at changing `PagedResult` to have a base class without `resumptionToken` and build from there, however server side these are not related so it made no sense to build in that relationship this side of the fence.
Once that was also done I tweaked the front-end to use it. Interestingly, …
> Add support to REST Module for new Search term highlights 

- Source/Plugins/Core/com.equella.core/js/tsrc/components/DateRangeSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
#1306 
Move the definition of type `Date Range` to `SearchModule` to reduce coupling between business layer and front-end.
> Move Date Range to SearchModule.

- .github/workflows/ci.yaml
leverages github actions setup-node to remove need for `shell: bash -l -eo pipefail {0}`
based off https://github.com/actions/setup-node/issues/32#issuecomment-539794249
> ci(github-actions): use actions setup node with nvmrc

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983 
- Save and Change password buttons padding and shadow fix
- First and last name alignment
- Timezone/Language section alignment
- Checkbox padding and alignment
- Header size and font aligns with other new stuff (I.E contribution page)
- Uses MUI theme colours
- Added padding to expanded dropdowns when they are at the bottom of a page
- Change dividers to use MuiDivider styles
- border radius for the watched collections box
> EBP: User Preferences Page styles

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983 
The bottom of the dropdown used to fall off the edge of the card. 
> EBP: Make room for Find Uses/Add To External System dropdown

- Source/Plugins/Core/com.equella.core/js/__mocks__/SearchResult.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchResult.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchResultList.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/TextUtils.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/TextUtils.ts
This change highlights search terms in the title and description of search result items in the same way (algorithmically) as the Legacy Search UI. The algorithm around this was mainly in java class `com.tle.web.sections.render.TextUtils`. As a result, a key part of this PR was to convert that to TS (`utils/TextUtils.ts`).
Once that was in place, it was just a matter of weaving it in, integrating with the 'highlight' list returned as part of #2225. 
To assist testing, I also refactored the `SearchResult.stories.tsx` to Storybook 6 before adding an additional story.
#1306 
> Highlight search terms in the results

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/TextUtils.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/util/TextUtils.ts
The legacy highlighting code had an additional word boundary in the regex. Further testing revealed the importance of this, so adding it back in here to the conversion.
> front-end: Highlight only matches from the start of words

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983 
- Add MUI padding to textfields
- Fix some broken select user dialog widths and add shadow borders (after the fix is screenshot 2, before the fix is in screenshot 3)
> EBP: Improve text field styles

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SettingsPage.tsx
- Source/Plugins/Core/com.equella.core/src/com/tle/web/settings/menu/SettingsMenuContributor.java
Previous fix does not work for the Settings page because this page isn't a Legacy page. The new fix in this PR can ensure Old UI  persists for both Settings page and Legacy pages.
> Make Old UI persist for settings page

- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
#1306 
This is just a simple language string change, to make the unsupported browser message a little more generic. In particular moving the word 'supported', and removing the message about new ui. Since an end user would likely not understand what the 'new ui' even means
> Adjusted wording for unsupported browser message

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983 
Use material UI styles for dropdowns. 
Also fix broken style for quick search. 
And fix styles on select buttons in manage pages. 
> EBP: Improve dropdown styles

- package.json
This rule conflicts with how we are doing our mocks. In that we're not
mocking a whole module, we simply mocking the return data of some
functions within a module.
However this rule is now heavily polluting our GHA builds.
More info on rule at: https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-mocks-import.md
> chore(eslint): Disable jest/nomocks rule

- oeq-ts-rest-api/src/AxiosInstance.ts
- oeq-ts-rest-api/src/UserQuery.ts
- oeq-ts-rest-api/test/UserQuery.test.ts
Adds oEQ userquery/lookup REST endpoint support to the oeq-ts-rest-api module. 
This will enable us to lookup oEQ users, groups and roles by id. 
The primary driver for implementing this is to allow for the new Search page to read in a user id from a query string, and display the correct user details in the OwnerSelector control. 
> Add lookup functionality to UserQuery rest module, with a few basic tests

- Source/Plugins/Core/com.equella.core/js/__stories__/components/MimeTypeList.stories.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFilterSettingsModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeList.tsx
- oeq-ts-rest-api/src/MimeType.ts
- oeq-ts-rest-api/test/MimeType.test.ts
This PR Adds support the TS REST Module for the new endpoint added in #2339 to retrieve viewer configuration for a specified MIME type. This work is seen in `MimeType.ts` and `MimeType.test.ts`.
However when doing this I saw that the existing `/mimetype` query (to list MIME types) was still sitting in one of the front-end modules (`SearchFilterSettingsModule.ts`) so I refactored that out into the new `MimeType.ts` and then refactored the consumers as needed.
#1306
> Add support for retrieving MIME type viewer configuration to oeq-ts-rest-api

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/MimeTypeResource.scala
- autotest/OldTests/src/test/java/io/github/openequella/rest/MimeTypeApiTest.java
Missed this in the initial implementation. So not really a bugfix, but kinda. Anyway, simply wraps the request to get the provided MIME type in an `Option` and then goes from there. `Some(entry)` => Do as it did before (copy and paste); `None` => Return a response of `HttpStatus.SC_NOT_FOUND`.
#1306
> bugfix(rest-api): Should return a 404 if MIME type not found

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983 
This css file was missing from legacy.scss, causing the external system connector's window to be unusably small. The screenshot shows an error window as I'm working upon another bug at the moment, but these styles are definitely necessary.
Before style fix: 
After style fix:
> EBP: Add missing auth.css

- autotest/OldTests/src/test/java/com/tle/webtests/test/viewing/ItemSummaryTest.java
This test has been causing problems in the old and new UI in GHA as of late. It seems the runner is often in non-english speaking countries and so Google redirects to a different version of itself so that the xpath check doesn't work.
As discussed with @edalex-ian, I've changed the link to be archive.org and the xpath to be the preamble string at the start of the page (see screenshot).
> Improve ItemSummaryTest - testAttachmentViewCount

- package.json
The -f option for remark means "frail", which means any problems (including warnings) cause a non-zero exit. 
Because of #2360, this PR removes the option from the task so that false positives for the no-dead-urls rule don't break builds.
> Remove -f from the check:md call

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#1983 
Turns out the styles applied to the file attachment dialog in #2255 didn't apply in the URL attachment dialog, and so this PR applies the same styling to the URL dialog.
Before change:
After change:
> EBP: Improve URL attachment dialog styles

- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/bugs/VisibilityScriptingBugTest.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/controls/PackageAndNavigationTest.java
- autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
- autotest/OldTests/src/test/java/testng/FailureRetryAnalyzer.java
- autotest/OldTests/src/test/java/testng/TestAnnotationTransformer.java
- autotest/OldTests/src/test/java/testng/annotation/NewUIOnly.java
- autotest/OldTests/src/test/java/testng/annotation/RetryTest.java
- autotest/OldTests/src/test/java/testng/annotation/SkipTest.java
- autotest/OldTests/testng-codebuild.yaml
- autotest/OldTests/testng.xml
- buildspec.yml
Add the ability of skipping tests in TestNG at runtime based on the environment.
There are three steps done to support this.
1. Add a new annotation which is used to specify whether to skip a test or not.
2. In 'TestAnnotationTransformer', dynamically disable a test based on the annotation and environment.
3. Include the Transformer in `tesnng-codebuild.yaml `.
This PR also refactored the directory structure where `TestAnnotationTransformer` is sitting.
> Allow skipping tests in TestNG at runtime

- autotest/OldTests/testng-codebuild.yaml
We can use `TestNG packages` to run all the functional tests  from package `io.github.openequella.rest` .
> Use TestNG packages to run new REST endpoint tests

- build.sbt
We currently only have a 'rebuild' task that also starts the server.
Often though after pulling latest code, all I want is a rebuild to
ensure my working copy is all clean before starting in the IDE.
Typically, projects have a 'rebuild' task to help with this workflow.
With this new task you can now simply:
```
sbt devrebuild
```
or, if you do want the server to start as well
```
sbt cleanrun
```
or, if after doing the above `sbt devrebuild` you later just want to start the server you can follow with:
```
sbt equellaserver/run
```
> chore(sbt): Add rebuild task

- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/service/impl/ThemeSettingsServiceImpl.java
Just a quick one when I was exploring what we can now do with setting up a custom theme. This increases what images we can use for a logo.
Biggest issue was before if you image was not 36px high, it'd get squashed and stretched making most images unrecognisable. As you can see in the screenshot, now we can use nice square ones for example - as somewhat common logo format.
#2478
> feat(server): Maintain logo aspect ratio

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/ViewerModule.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/ViewerModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
- oeq-ts-rest-api/src/Search.ts
Unfortunately, unless the viewer for the video MIME types was configured as 'file' then the viewer would fail. By default, the viewer is the HTML 5 Viewer of oEQ, so it was attempting to use the resultant HTML from that page in a `<video>` tag.
To fix this, the path of the file for file attachments is also returned in the attachment data for search results. This can then be used by the front end to build a direct `file` URL when wanted. In the case of the viewer, this is pretty well always unless the viewer configuration is for download.
> Fix view video attachments from New Search UI search results

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
#688 
This PR adds Selection Session data to `renderData` for the new search UI.  The data includes: the ID of a Selection Session, the ID of an Integration and the layout which is used.
> Include Selection Session information in RenderData.

- .eslintignore
- .github/workflows/ci.yaml
- .gitignore
- .prettierignore
- Source/Plugins/Core/com.equella.core/js/.gitignore
- Source/Plugins/Core/com.equella.core/js/tsconfig.json
This PR adds steps to GitHub Actions workflow to build the static instance of Storybook and upload it as an artefact. 
Drafted until I see it working on CI.
> Add steps to ci.yaml to build and artefact storybook

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/ApiHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/AdvancedSearchResource.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/i18n/TextBundle.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/powersearch/PowerSearchService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/remoting/resteasy/RestEasyServlet.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/AbstractRestApiTest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/AdvancedSearchApiTest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/MimeTypeApiTest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
Added a new simple `api/settings/advancedsearches/` for retrieval of Advanced Searches (aka Power Searches).
While doing this, also needed to refactor a couple of supporting classes.
#1306
> Feature - REST API to retrieve advanced searches

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/BaseEntitySummary.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/AdvancedSearchResource.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/RemoteSearchResource.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/powersearch/PowerSearchPrivileges.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/powersearch/PowerSearchService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/powersearch/impl/PowerSearchServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/remoting/resteasy/RestEasyServlet.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/AdvancedSearchApiTest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/RemoteSearchApiTest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/models/BaseEntitySummary.java
- oeq-ts-rest-api/src/AdvancedSearch.ts
- oeq-ts-rest-api/src/Common.ts
Just another simple endpoint, this time to get a list of Remote Searches.
This is very similar to #2512 , and as a result includes a degree of refactoring to keep things DRY and pave the way for any future `BaseEntity` work we do. To some degree there is a whole framework on the Java side for this, however on this side we're attempting to keep it more concrete and explicit.
Also snuck in a minor refactor to sort the list of properties in `LegacyGuice`. (One day we probably want to sit down and consider if this approach is really what we want to be doing - one big bag for all the DI.)
> Feature - REST API to list remote searches

- Source/Plugins/Core/com.equella.core/js/__mocks__/RemoteSearchModule.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/search/RemoteSearchSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/RemoteSearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/RemoteSearchSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
This adds a new 'selector' for the New Search UI to navigate to the remote legacy remote search pages. The New UI side of things all works, however it has unveiled a few bugs with the legacy UI remote searching (primarily excessive persisting of state). Those issues are well outside the scope of this work, however will definitely need to be fixed to release 2020.2 and so will be in a PR soon.
Video: https://streamable.com/on6ljx
#1306
> feature(new-ui): Add new Remote Search Selector

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Float on the autocomplete-container was causing graphical issues, different controls rendering on top of one another. Turned off float and added padding, and also hidden the disabled native input that was showing. 
Before: 
After:
> EBP: Fix inline Taxonomy term selector styles

- Source/Plugins/Core/com.equella.core/js/__mocks__/MimeTypes.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/components/MimeTypeFilterEditingDialog.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/MimeTypeFilterEditingDialog.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/SearchFilterSettingsPage.tsx
This PR fixes the Storybook of component `MimeTypeFilterDialog`.
By doing this, I also refactor the props of the component to allow injecting a function which retrieves Mime Types.
This approach provides more flexibility and has been used in some components so I think we should use this approach for 
`MimeTypeFilterDialog`.
> Fix MimeTypeFilterDialog Story

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/RenderDataHelper.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/LegacySelectionSessionModule.test.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
#688 
This PR is about whether show the `Select SummaryPage button` or not.
The approach include a few steps:
1. Due to the fact that the visibility of this button is controlled by either `oEQ setting` or `LMS oEQ plugin setting`, read and merge the two settings into one boolean flag.
2. Include the flag in `renderData.selectionSessionInfo`.
3. Front-end shows/hides the button based on the flag.
I think what is most important is the logic of how the two settings are merged.
I only uploaded two screenshots for when the LMS setting is `No restrictions`.
> Don't show select summary button if it is disabled

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#2546 brought in a bug in which various fancybox dialogs that did not use arrows would start showing them. This is because in places where fancybox doesn't specifically set "display:none" inline it gets overridden by "display:flex" in legacy.scss. Thankfully, when the arrows are required "display:flex" is set inline to the tag by fancybox so we don't need to set it directly. 
Before: 
After:
> EBP Bugfix: Stop arrows from appearing on dialogs that don't use them

- autotest/OldTests/src/test/java/com/tle/webtests/test/viewing/MimeTypesTest.java
Disabling this flakey test temporarily whilst it is worked on in #2568 so that it doesn't get in the way of other builds.
> Disable MimeTypesTest temporarily whilst it is worked on

- Source/Plugins/Core/com.equella.core/js/__mocks__/AdvancedSearchModule.mock.ts
- Source/Plugins/Core/com.equella.core/js/__mocks__/RemoteSearchModule.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/search/AuxiliarySearchSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/IndexPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/AdvancedSearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/AuxiliarySearchSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/RefineSearchPanel.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Add a new selector which navigates uses to the legacy Advanced Search UIs (as Advanced Search is not planned to be implemented until 2021.x).
To do this, I refactored the `RemoteSearchSelector` into the generic `AuxiliarySearchSelector` and then plugged it in. There was also a requirement that it should always be displayed along with the Collections selector, so I also modified that logic in the `RefineSearchPanel`.
Lastly, due to the support for saved search URLs from legacy UI (using `searching.do`) requiring logic in the routes, I had to further rework this as Advanced Searches are access by `searching.do`. This required refactoring out of `routes.tsx` and into the main router `Switch` in `IndexPage` so as to achieve the dynamic nature needed. This seems rather valid, as the route is …
> Feature - Advanced search selector

- Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
Related to #2527, the delegate `ghostscript` doesn't inherently close when imagemagick does. This PR ensures that when thumbnailing times out, any child processes of imagemagick are killed first. 
> Make sure that thumbnailing timeout kills both imagick and ghostscript

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/CourseListHelper.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
#688 
This PR adds the feature of 'Drag and Drop' to the new Search UI so each Item and attachment is draggable and they can be dropped to the course list in Selection Session.
The approach is basically to reuse some old JS functions provided in `courselist.js` to make TS component draggable. 
The whole logic should be: 
1.  `CourseListSection.java` prepares a droppable area which is the course list, including setting up the `onDrop` event handler, and specifying what elements can be dropped.
2. A search is in done in new search UI and returns some search result Items.
3. Make each search result Item draggable.
4. After the async call for attachment viewer details is completed, make each attachment draggable.
Please view this [Video](https://streamable.com/768cpf).
> Drag and drop in new search page

- Source/Plugins/Core/com.equella.core/js/__stories__/search/AuxiliarySearchSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/BaseUrlHelper.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/LegacySelectionSessionModule.test.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/components/OeqLink.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/AuxiliarySearchSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/guice/AdvancedSearchModule.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/RootAdvancedSearchSection.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/RootSearchSection.java
#688 
This PR addresses the issue that Remote search page and Advanced search page didn't display properly in Selection Session if they are open from new search UI.
There are three changes: 
1. Create a new TS component named 'OeqLink'. The reason is we have a few places where we need to switch between `React Route Link` and `MUI Link`, depending on whether the page is in Selection Session. 
2. For Advanced search requests coming from new search UI in Selection Session, create a new Legacy endpoint which is `advanced/searching.do`. To support this endpoint, also create a Section module and a Section. 
3. Make sure functions related to `Drag and Drop` are only called when Selection Session is in structured.
> Support Advanced/Remote searches in Selection Session

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
The previous fix made in #1330 does not work in Selection Session because the ItemSummary page URL has some query params (e.g. `stateId=2`). 
So in this PR, I slightly modified the ItemSummary URL Regex to make sure it also works for above situation.
A video is available [here](https://streamable.com/rdrck4).
> Don't display the Leave or Cancel dialog when saving a new item

- Source/Plugins/Core/com.equella.core/js/tsrc/components/DateRangeSelector.tsx
This PR addresses the issue that the dates selected in new search UI does not displayed properly in small windows.
There are two changes: 
1. Only show the calendar icons when either one of the two date pickers is focused.
2. Only Use 6 grids as the date picker width for breakpoint `xl`.
Here is a [video](https://streamable.com/wsti82)
> Only show the Date picker calendar icon when the field is focused

- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeAttachmentSerializer.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeHandler.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeViewableResource.java
The YouTube controls were not working properly. This is because once oEQ got to parsing the date modified string that was returned for a YouTube result it was found to be unparsable. It used to work properly but updates to the YouTube API involved changes to the date format. 
This PR addresses the issue by parsing the date properly, in the YoutubeHandler when running Youtube searches and displaying results, in the YoutubeAttachmentSerializer when saving attachments to the database, and YoutubeViewableResource when displaying the resource summary.
> Parse Youtube Date Modified dates properly

- Source/Plugins/Core/com.equella.core/js/__stories__/components/Date.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/components/DateRangeSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchBar.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/components/UserSearch.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/search/OwnerSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchAttachmentsSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchResult.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/search/StatusSelector.stories.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/UserSearch.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/OwnerSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchAttachmentsSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/StatusSelector.tsx
This PR aims to address all remaining eslint warnings except those that fall under `react-hooks/exhaustive-deps`. Since those will take a lot more investigation to fix without breaking functionality, they will be done separately.
- Add typing of `Meta<propsOfStorySubject>` to all storybook default exports. Added export to interfaces where necessary.
- Add name to the default export function in index.tsx
- Removed false import of DateRange Material UI icon from SearchModule.ts
- Renamed RangeType so it doesn't get reassigned
> Address eslint warnings (not exhaustive/deps)

- .idea/misc.xml
- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/heartbeat.ts
A number of possible errors were not being caught. This would result in
spurious console log entries, and lack of feedback to the user that an
issue had occurred.
Most of these are now addressed, by simply shutting down oEQ and then
chasing things popping up in the console log. Or in a few cases, just by
manual code analysis and looking at the user result.
And also snuck in a minor IntelliJ project file update.
> Improve SearchPage error handling

- Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
Since the Java method `waitFor` returns a boolean to indicate whether the process is finished or not, we should use this boolean rather than using `StreamReader.isFinished()`.  With this change, I no longer have errors like `kill and pgrep calls` and `Error generating thumbnail` locally.
In terms of why `StreamReader.isFinished()` is not working reliably, I think we need to dig into its `run`.
> Properly check whether thumbnail generation is timeout or not.

- Source/Plugins/Core/com.equella.base/src/com/tle/common/connectors/ConnectorFolder.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/BlackboardRESTConnectorConstants.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/BlackboardRestAppContext.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/beans/Availability.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/beans/Course.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/beans/Token.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/BlackboardRESTConnectorService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/utils/ConnectorEntityUtils.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/blackboard/servlet/BlackboardRestOauthSignonServlet.java
- Source/Plugins/Core/com.equella.core/test/java/com/tle/core/connectors/utils/ConnectorEntityUtilsTest.java
History in #2587
Caching adjustments:
* Leverage Bb REST API refresh tokens so the user does not have to log back into Bb during the same oEQ session
* User session caching now in place for auth token
* Auth caches now combined into a single cache of the entire `Token`
* `Course`s and `Folder`s requests are now setup to check the cache, and if none are available, pull a fresh set of results from Bb
Found a unrelated bug where only the first 200 content items from a Bb course were being returned.  Now pulls all pages of content results.
> Fix Bb LTI / REST caching and request all course folders

- Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/command/SaveDialog.java
#1204
Previously, if users `save and continue` an Item and later save the item as a draft, a 500 error will occur. The reason is New UI failed to stay in the Wizard (I haven't dug into why it failed). But what we want is the page should navigate to ItemSummary page instead of staying in the Wizard if user save an Item as a draft.
So this PR's changes can ensure the navigation happens.
> Ensure navigating to ItemSummary page if an Item is saved as a draft

- Source/Plugins/Core/com.equella.core/src/com/tle/core/workflow/thumbnail/service/impl/ThumbingCallable.java
When testing the fix for #2527 It came to @PenghaiZhang 's attention that thumbnailing errors do not specify a culprit filename and that it would be a value-add to include. Looking into it I realised it was a quick oneliner to make this happen. 
> Add filename to "Error generating thumbnail" log message

- Source/Plugins/Core/com.equella.core/resources/com/tle/core/i18n/service/impl/i18n-resource-centre.properties
A language string that went missing at some point. Gets used during error handling for the Canvas integration. 
#2601 triggers this missing language string. 
> Add back missing com.tle.core.connectors.canvas.error.prelim language string

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
When a LMS like Brightspace and Canvas is configured to use 'selectOrAdd', the selection submit response is a `ChangeRoute`, which means the page should navigate based on what route is returned.
Probably in most cases, the page should navigate to the Checkout page.
Here is a [video](https://streamable.com/2e2agl) made with Brightspace.
> Support navigating to Checkout page after selecting an Item

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/RootSearchSection.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/selection/SearchSelectable.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/selection/section/SelectionSummarySection.java
#2605 
So I can reproduce this error by logging in as a normal user such as AutoTest. And this PR's changes can fix this issue although I am not entirely sure what is the matter with ACL for this bug. If I revoke ACL `SEARCH_POWER_SEARCH` then I just simply can't see this advanced search from the list, not to mention to open the advanced search page.
There are a few things worth to mention here.
1. if Advanced Search is open from new Search then the Section used is `RootAdvancedSearchSection`;
2. `RootAdvancedSearchSection` contains the node Section `SelectionSummarySection`;
3. `SelectionSummarySection` needs the UI Settings to determine what callback is used for the `Unselect all` button.
Step 3 is where the error gets caused.
> Fix the 500 error when navigating to Advance search from new search UI

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
#1306
There were numerous issues integrating this inside selection session iframes. Plus, it doesn't really make sense for someone to want to share a search in a selections session. So the decision was made (for now at least) to not show the share button in selection sessions
> Don't show share search button when in a selection session.

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Bit of a quick win that fell out of work involved with #2577. I won't be adding additional EBP changes to this PR as this is not scheduled work.
When the YouTube search happens, all of the results get put into the dialog list. Without a max-height, this causes the dialog to stretch down which looks strange. 
- Added a max-height for the YouTube Dialog
- Set overflow-y to scroll
- Added standard box shadow and border radius to dialog
- Move dialog upwards to make room for more results
Before change: 
After change: 
> EBP: Make sure Youtube dialog doesn't stretch offscreen

- Source/Plugins/Core/com.equella.core/js/tsrc/components/NavigationGuard.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetDialog.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetedSearchSettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/SearchFilterSettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/UISettingEditor.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/useError.ts
This is an initial attempt to address some of the `react-hooks/exhaustive-deps` warnings. There was more than 30, there are now 24.
Because we're just before release, I tried to find the easy ones and flesh out any patterns. (I did start on the `DateRangeSelector` but got a bit more involved - I was almost there, but ran out of time.)
This initial batch resulted in a custom hook being brought in (`useError`) to encapsulate the pattern of how we deal with errors - when we also want to properly specify our dependencies. But as per the comment, I hope this only hangs around for a short time and is ultimately replaced with a Context and Error Boundary (or multiple).
The effort also highlighted the complexity of state we're trying to manage via effects in several places, and I believe we could …
> Address some ESLint react-hooks/exhaustive-deps warnings

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java
#1750 
In Old UI, pushing Enter on a textfield which is the only input of a form does not submit the form whereas it submits the form in New UI. This is because the Javascript controlling whether to submit a form does not get executed in New UI. 
I have tested two places: the dialog for adding a favourite search and dialog for adding a link attachment. Now let's see if we can have green builds.
> Ensure forms submit properly in New UI

- Source/Plugins/Core/com.equella.core/js/tsconfig.json
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/src/com/tle/web/portal/standard/renderer/SearchPortletRenderer.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/SearchQuerySection.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/selection/SearchSelectable.java
Currently, when a search is triggered from quick search in Selection Session, the endpoint is not `selectoradd/searching.do`. This will result in showing the regular page in Selection Session. So we need to change the endpoint.
Also, in order to pass the search query to new search UI, we need to 
1. enable the feature of `converting query strings to search options` in Selection Session;
2. append the query to the URL.
When I was testing,  I noticed that `converting query strings to search options` is not quite compatible with `back to search page`. The issue is if back to a search URL which has query strings, the search option stored in browser history is ignored. 
So overall, this PR fixes above issue and make quick search work fine with new search UI.
[quick search in regular …
> Bugfix/search portlet do not support new search UI

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
In work on YouTube dialog styling done previously a few issues popped up. The negative margin on the dialog caused parts of the dialog to be cut off the top of the screen. After removing that, I noticed that the edit dialog styles were also broken. This PR fixes both issues. 
Before:
After:
> Improve Edit YouTube dialog styles

- Source/Plugins/Core/com.equella.core/resources/web/js/datepicker.js
The start of Wizard Calendar year range is relatively 50 years back to current year, which means 1970 is no longer available on the pick list since 2021. Some tests therefore fail to select 1970. So this PR makes sure the year range start is fixed to 1970.
> Ensure the year range of Wizard Calendar starts from 1970

- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
#2623 
This PR refactors the logic of how to convert query params to SearchOptions.
The biggest change is: 
If the new search page is open from `Quick Search`, the location pathname will be `searching.do` rather than `page/search`. This means we should call `newSearchQueryToSearchOptions` instead of `legacyQueryStringToSearchOptions`.
Here is a [video](https://streamable.com/tta47h) for the fix.
> Refactor the logic of converting query params to SearchOptions.

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
In a selection session, when the number of selection destinations exceeds 10, you can't scroll down far enough to see the lowest entries unless you scroll down to the bottom of the openEQUELLA search page. Adding max height to the list means that if it is too long it will have a scroll bar.
Before:
https://user-images.githubusercontent.com/24543345/103978903-aea49080-51d0-11eb-919d-5d0c6caf38aa.mp4
After:
https://user-images.githubusercontent.com/24543345/103978970-ced44f80-51d0-11eb-8325-9411d28ba6d0.mp4
> EBP: Add max-height to folderlist in selection session

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
Previous use of render was unnecessarily verbose. Briefly discussed in #2638 .
> refactor(front-end): Use 'component' for routes

- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SettingsPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/UISettingEditor.tsx
A ways back MUI renamed ExpansionPanel to Accordion. All still worked
but we'd get hit with extra errors in the console in development builds.
Plus, at some point they'll simply remove ExpansionPanel.
> chore(front-end): Rename ExpansionPanelXyz

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SettingsPage.tsx
Converts plain functions to generate JSX into react component functions.
This allows the react dev tools to inspect the props and state of the functions, and brings more consistency to the codebase.
> refactor: convert plain functions to generate JSX into react component functions

- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/IndexPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/MainMenu.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchSettingsModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaNodeSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/ContentIndexSettings.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/SearchPageSettings.tsx
Alright, yet another batch of addressing `react-hooks/exhaustive-deps` ESLint warnings. This leaves us with only 5 which are all focused around `SearchPage` (including `DateModifiedSelector` as that needs `SearchPage` fixed first).
Components addressed:
- `SearchPageSettings`
- `ContentIndexSettings`
- `SchemaSelector`
- `SchemaNodeSelector`
- `SearchResult`
- `IndexPage`
- `Template`
- `LegacyContent`
In `LegacyContent` I took a pragmatic approach and resorted to suppressing the 2/3 warnings. This is because the amount of effort was not justified when: 1. we plan to get rid of this long term; and 2. a ton of effort has just been expended on it to get it in better shape. (It feels like it would require treatment similar to what will be needed for `SearchPage`.)
I did observe other …
> Further refactor to address react-hooks/exhaustive-deps

- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
When in a selection session (as the selection panel takes up room) or on a small screen (there's less room to begin with), the Refine Search Panel has less width. So the collection selector when getting populated with chips can grow too big and force the panel to widen which can cause overlap with the selection panel or the side of the screen. 
This is addressed in this PR by changing the ratio of search panel width to refine panel width from 9:3 to 8:4. 
This change also limits the width of the chips so they can't take up more than 50 percent of the collection selector's total width.
In order to not lose information with the now truncated collection names, I have added in a tooltip for these chips which displays the full name.
Before: …
> Make sure that the Collection Selector doesn't overlap the Selection Panel in a Selection Session

- Source/Plugins/Core/com.equella.core/js/tsrc/components/DateRangeSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
Well, there we have it. This PR brings the count of `react-hooks/exhaustive-deps` warnings to _zero_!! :tada: 
To achieve that I've done two things:
1. Refactored `SearchPage` to `useReducer` for it's main state relating to searching; and
2. Removed a superfluous effect from `DateRangeSelector`.
**SearchPage**
Towards the conclusion of 2020.2 the amount of state and effects the `SearchPage` was looking after had made the component's function somewhat opaque, however there wasn't time for significant refactor. This PR now does that refactor with a pivot to `useReducer`.
Doing so has improved readability of the code, and  made it more explicit as to when searches are occurring - rather than depending on the chain of effects and their dependencies. I think it has also addressed a few cases …
> Refactor of SearchPage to useReducer to address last set of ESLint react-hooks/exhaustive-deps

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
- autotest/OldTests/src/test/java/io/github/openequella/pages/search/NewSearchPage.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/Search.test.ts
Adds support for filtering by a list of MIME types. We need this for a few things, but my immediate concern is the image gallery.
> Feature - Search2 MIME type filtering support

- Source/Plugins/Core/com.equella.core/resources/com/tle/core/i18n/service/impl/i18n-resource-centre.properties
- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/canvas/service/CanvasConnectorService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/HttpService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/services/impl/HttpServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/integration/IntegrationExceptionHandler.java
This is a fix for two related issues. 
**Issue 1:** Errors that occur within an integration selection session are "swallowed" by another error that reads "Already Rendered!" rather than showing the correct message. This is because the IntegrationExceptionHandler doesn't rethrow like the DefaultExceptionHandler does, causing the error page to be rendered but not served up. Then when it tries to render the actual page to serve up, it triggers the "Already Rendered!" error. 
In the old UI it appears to use the Default handler anyway, and so things work properly. 
I was able to edit the IntegrationExceptionHandler so that if in the new UI the error gets properly rethrown as a RuntimeException, rather than swallowed up.
**Issue 2:** An error that was hidden by this was a known bug in the …
> Ensure full page errors in new UI integration selection session are not swallowed by "Already Rendered!" error

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/DateRangeSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/AuxiliarySearchSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/ClassificationsPanel.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/RefineSearchPanel.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SidePanel.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaSelector.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
#2559 
This is the second PR for the Skinny Selection Session, which includes changes:
1. Improve the user experience in small screens - the side panel is displayed in a `Drawer` which is controlled by an icon button. This is achieved by using MUI hook `useMediaQuery`.
2. Add two new components: `SidePanel` and `ClassificationsPanel`.
3. Modify the default search option to include more fields with default values.
4. Tests for above changes.
While working on writing Jest tests, I also tried to fix lots of warnings. Now there is one remaining warning about determining attachment viewer which is what we expect to see.
https://user-images.githubusercontent.com/47203811/107449054-fbe09d00-6b96-11eb-823f-2caaa806a010.mp4
> New search page responsiveness

- Source/Plugins/Core/com.equella.core/js/tsrc/modules/ViewerModule.ts
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/AttachmentDao.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/AttachmentDaoImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/resource/ResourceAttachmentBean.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/GenericDao.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/GenericDaoImpl.java
When clicking attachment previews from the search page, if the attachment came from a non-integration selection session (Resource Attachment) then it wouldn't resolve the mimetype, and so the viewer would treat is as a default MIME type attachment and simply open in a new tab rather than a lightbox. 
To fix this, I added a case on the backend to handle mimetypes for resource attachments rather than just for file attachments. 
Since it is possible to select a resource attachment which points to a resource attachment which points to a resource attachment infinitely, we required a bit of recursion to drill down to the original attachment and get its mime type. 
> New Search UI: allow attachments contributed via Resource Selector to use the correct viewer on the search page

- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
This dialog flickers with different dialog content when it's about to close. This can be fixed by excluding it from the react virtual DOM tree when the visibility flag is false.
> Do not re-render FavouriteItemDialog when it's about to close

- .github/workflows/ci.yaml
This PR is just to test how GHA goes running the test suite against PostgreSQL 13.2 (current latest version). Recently when working on something else, I installed openEQUELLA with this version and it seemed to work. 
If this  goes well, I can take it out of draft and we can have GHA test against latest postgres from now on. If it doesn't go well, then we know that there are changes that need to be made to support this version. 
> Update ci.yaml to use postgres 13.2

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/favourite/FavouriteResource.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/favourites/service/FavouriteSearchService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/favourites/service/FavouriteSearchServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/FavouriteApiTest.java
- oeq-ts-rest-api/src/Favourite.ts
- oeq-ts-rest-api/test/Favourite.test.ts
This PR, I added a new REST endpoint to support adding a favourite search. I also updated the endpoint for favourite item (from `favourite` to `favourite/item`). Then, I added the support to the REST Module for the new endpoint.
During testing, I encountered the issue of viewing a favourite search in new Search UI. Since the fix seems easy to implement, I added the fix in this PR.
> Support adding a favourite search

- Source/Plugins/Core/com.equella.base/src/com/tle/web/api/item/interfaces/beans/AttachmentBean.java
- Source/Plugins/Core/com.equella.core/js/tsrc/components/ItemAttachmentLink.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- autotest/OldTests/src/test/java/io/github/openequella/pages/search/NewSearchPage.java
- autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
- autotest/Tests/tests/facet/institution/items/24/19096.xml
The new search UI doesn't handle restricted attachments properly - they will still appear in a search, although the file itself will be inaccessible. 
Added to the convertToAttachment function to filter out these attachments when the user does not have VIEW_RESTRICTED_ATTACHMENTS granted.
> Support restricted attachments properly in the new Search UI

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
This clash with the idea of what the gallery is providing (kind of, pre-packed filter configurations), so best to avoid clashes and hide/disable them.
https://user-images.githubusercontent.com/43919233/111733847-f2043500-88cc-11eb-8761-c31c7dad3d76.mp4
> feat(front-end): Disable MIME type filters in gallery modes

- Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
The folder (loginnoticeimages/) was missing from the getMimeType call which meant that uploading images to the login notice editor would error out. Added this to the image path for that call to fix it. 
I am open to spending time to add a test for this, currently we have a test for using an image URL but not uploading direct, which is how this went unnoticed. 
#2833 
Before change:
https://user-images.githubusercontent.com/24543345/111723724-23263a80-88b8-11eb-8e17-75e65dfc053f.mp4
After change:
https://user-images.githubusercontent.com/24543345/111723998-92039380-88b8-11eb-8598-d3bac016e6b9.mp4
> Allow login notice editor to upload images

- Platform/Plugins/com.tle.platform.common/src/com/tle/common/Check.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
Add support for oEQ's internal search service's concept of 'musts'. This essentially provides support for lucene queries at the index field level.
This is needed so that we can implement the Video gallery where suitable items are searched for with `videothumb:true`.
> feat(rest-api): Add support for 'musts' to search2

- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/Search.test.ts
So that we can use that provided in #2841 
Added some typing to try and assist callers providing musts in a correct format before they're sent to the server. Maybe overkill, but could help.
> feat(oeq-ts-rest-api): Add support for search2 musts

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/RenderDataHelper.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
We were defaulting to not full screen, which became a problem in selection sessions as it would take a short while to update based on width and height of the viewport. Now the default is false *unless* in a selection session or integration item view (integ/gen item link) where it is true. 
This involved adding to the renderData information passed from RenderNewTemplate a new variable viewedFromIntegration, which depends on a check as to whether the request is an /integ/gen item link. 
Before:
https://user-images.githubusercontent.com/24543345/112430075-c03e1300-8d91-11eb-979f-08c494bc6a8e.mp4
After:
https://user-images.githubusercontent.com/24543345/112429361-a6e89700-8d90-11eb-839f-def89e8e41ee.mp4
[commit guidelines]: …
> Hide menu panel in selection sessions and items viewed from integration

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
This way YouTube videos, their thumbnails, etc can be displayed in the
New UI by building strings around it.
> feat(rest-api): Include YouTube video ids in search2 results

- Source/Plugins/Core/com.equella.core/js/__mocks__/GallerySearchModule.mock.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/FpTsMatchers.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/GallerySearchModule.test.ts
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/GallerySearchResultHelpers.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/AttachmentsModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/GallerySearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/MimeTypesModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/YouTubeModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/GallerySearchResult.tsx
- oeq-ts-rest-api/src/Search.ts
This adds the transformation support to the `GallerySearchModule` to support Video Searches. As well as that, it then adds a function to do the `videoGallerySearch()`. Then, it was only a small bit of extra work to plug it in, so basic gallery view of videos is now functional (but need to add lightbox support for YouTube still - that's a future PR).
While at it, reworked the the Jest checks for `E.Left` and `E.Right` by setting up some custom Jest Matchers (`FpTsMatchers.ts`).
There was also a refactor around GalleryEntry so that it was no longer so Image specific.
Below video shows a quick look at the video gallery in action - noting the missing support for YouTube (coming soon).
https://user-images.githubusercontent.com/43919233/113254567-7bc2f200-9312-11eb-9b1b-81726bfe898e.mp4 …
> Add support to the GallerySearchModule for Video Gallery - and inital basic integration

- Source/Plugins/Core/com.equella.core/js/__stories__/components/Lightbox.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__stories__/components/YouTubeEmbed.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/Lightbox.test.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/YouTubeModule.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/components/Lightbox.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/YouTubeEmbed.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/MimeTypesModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/YouTubeModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
This simply adds support to the Lightbox to support previewing YouTube videos from the video gallery. Also paves the way to then support using this in the lightbox used to preview attachments in search results.
Things to note:
* Embed component is based on current embed code provided by YouTube - including default dimensions.
* Did bring in fp-ts `pipe` and `Option` into Lightbox component as it just keeps things sooo much tidier and readable. (This includes using `pipe` -> `match`.)
* Lightbox now has a `match` clause looking of `openequella` MIME types, and then within which just explicity checks for `openequella/youtube`. In the future I imagine this will be refactored out once we start supporting some of the other custom oEQ types - e.g. Kaltura. For now, possibly a bit awkward, but …
> Add support to Video Gallery to preview YouTube videos

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
A missing css file was not imported into legacy.scss - namely drmlicense.css. The only rule in this CSS file is this:
```css
.drmlink_preview, .drmlink_viewer {   
display: none; 
}
``` 
Importing the file fixes the issue in which the hidden DRM links for attachments in a resource summary show in the new UI.
Before change: 
After change:
> Hide preview and viewer links from DRM items

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#2850
This problem was discovered as a support issue. So various strings can break the layout if they are too long, both in the legacy EBP UI and the new search UI. 
In the Template.tsx file, I added a global rule to all `a` and `p` tags to `overflow-wrap:anywhere`, which means they can simply break to a new line rather than extending the width of their containers.
In the `legacy.scss` I handle the same issue in contribution wizards and in item summaries. 
I was able to confirm that this handles well in the main UI and in a selection session.
Before change:
https://user-images.githubusercontent.com/24543345/113230769-7602e780-92e5-11eb-8549-0c58196c9771.mp4
After change:
https://user-images.githubusercontent.com/24543345/113230778-7c915f00-92e5-11eb-9689-947b43c2d863.mp4
[contributor …
> Handle long strings without breaking layout

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
And when there are also result / found in attachment highlighting:
> feat(front-end): Add attachment count to search results

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
Since we have created a new component `SearchResultAttachmentsList` to handle attachments, the preparation for drag and drop should be moved to there as well. And the useEffect should depend on the state variable `attachmentsAndViewerConfigs` because the attachment list is built based on it.
https://user-images.githubusercontent.com/47203811/114112056-e382c980-991e-11eb-911b-ec8384f91ce9.mp4
> Make attachments draggable in SearchResultAttachmentsList.

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#2715 
This is a CSS change to realign custom data fields on resource summary pages. 
Before change: 
After change:
> Fix margins and padding for custom data fields on resource summary

- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
As discussed, use Raw search mode in new UI for searches saved or shared in old UI mode.
> Use Raw search mode for Old UI saved or shared searches

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Small tweak related to #2715. Just to add a little horizontal padding between the half page custom node displays. 
> Allow some margin between .displayNodeHalf elements

- Source/Plugins/Core/com.equella.core/js/__mocks__/UserModule.mock.ts
- Source/Plugins/Core/com.equella.core/js/__mocks__/UserSearch.mock.ts
- Source/Plugins/Core/com.equella.core/js/__stories__/search/ExportSearchResultLink.stories.tsx
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/MessageInfo.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/ExportSearchResultLink.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
- oeq-ts-rest-api/src/LegacyContent.ts
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/Search.test.ts
In this PR, I created a new ts component named `ExportSearchResultLink`. It is either a link or a icon, depending on whether the search result has been downloaded or not. This component is integrated in `SearchResultList`. I also refactored how to use `snackbar` in search page, to support showing a warning.
https://user-images.githubusercontent.com/47203811/114338155-cc014600-9b95-11eb-9093-ef812cd29edc.mp4
> Add Download CSV button to Search page

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/auditlog/AuditLogService.java
- Source/Plugins/Core/com.equella.core/src/com/tle/core/auditlog/impl/AuditLogServiceImpl.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
Previously, the search param was stored in column 'data2' which has a length limit. So when  search param was too long the audit log threw an error. 
This PR changes  'data2' to  'data4' which has no limit and saves search param in Json format.
> Ensure a long search params does not break audit log

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
The Lightbox title was centered in Image/Video gallery due to an inline style applied to `SeachResultLIst`. This PR makes this style conditionally working.
In standard mode 
In gallery mode
> Do not center Lightbox title

- sbt
It seems the URL the old one is using is suddenly failing, hoping this fixes it. If we get a green build, we know it does. (Then we need to consider if we want this over on `develop` or whether we can wait...)
NOTE: This is just the latest code from https://github.com/paulp/sbt-extras/blob/master/sbt
> chore(deps): Update SBT wrapper script

- Source/Plugins/Core/com.equella.base/src/com/tle/web/api/search/interfaces/SearchResource.java
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/GallerySearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/SearchResourceImpl.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/FacetSearchApiTest.java
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/src/SearchFacets.ts
This ensures that the classifications and categories are correct when in the Image and Video galleries. This requires that the same additional filters (MIME types or musts) are sent to list the classifications function.
> Integrate facets with galleries

- Source/Plugins/Core/com.equella.base/src/com/tle/common/security/PrivilegeTree.java
- Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/components/TooltipIconButton.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/ExportSearchResultLink.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
- autotest/OldTests/src/test/java/io/github/openequella/pages/search/NewSearchPage.java
- autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
This PR includes two major changes: 
1. changing the configuration of ACL `EXPORT_SEARCH_RESULT` on Collection level instead of Institution level.
2. better front-end error handling.
With the first change, the export button is displayed as long as user has the ACL granted against at least one Collection.  When user exports with a Collection which does not allow to export, the snack bar pops up with a warning message.
For the better error handling,  `ref` is used to help manually trigger a click event on the export link after the head request gets resolved. If the request gets rejected, an error message is showed.
https://user-images.githubusercontent.com/47203811/115316029-e0f45f80-a1bb-11eb-8792-ec9be874c0ae.mp4
> Front-end improvements for exporting search result

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Related to the fix for #2850. 
To fix long strings breaking the layout, global rules were added to the template to `overflow-wrap: anywhere` on all `<a/>` and `<p/>` tags. This affected the Notifications and Tasks icons as they were children of `<a/>` tags, causing any more than one digit of notifications or tasks in the badge to display incorrectly. 
Added a rule to exempt `<button/>` tags from the rule.
Before change:
After change:
> Prevent badge text from falling into multiple lines

- Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
This PR fixes the debounce issue of SearchBar by using `useReducer`. Also, the usage of `debounce` has been moved to SearchPage as whether to debounce a search is what SearchPage cares.
https://user-images.githubusercontent.com/47203811/116189953-19bca780-a76d-11eb-9d0a-33576229dc13.mp4
> Use 'useReducer' to better handle the state of SearchBar

- Source/Plugins/Core/com.equella.core/js/tsrc/mainui/MainMenu.tsx
Two warnings about `ref` have been there for quite a while. They are caused from component  `MainMenu`. Details about the warnings can be found from [MUI Guide](https://material-ui.com/guides/composition/#caveat-with-refs).
This PR fixes the two warnings by refactoring how to build a MUI ListItem that works as a link in component `MainMenu`.
> Fix MUI warnings about `ref`

- Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
The previous fix for SearchBar debounce issue can cause another issue: when open a shared search where a query is included, SearchBar does not show the query. So PR brings in an additional fix based on the debounce issue fix.
https://user-images.githubusercontent.com/47203811/116650627-ebd1a000-a9c4-11eb-98a3-5e38c72f2b8f.mp4
> Ensure search bar shows the correct query

- Dev/learningedge-config/build.sbt
- Installer/build.sbt
- Source/Plugins/Admin/com.tle.web.adminconsole/build.sbt
- Source/Plugins/Admin/com.tle.web.adminconsole/jarsrc/build.sbt
- Source/Plugins/Applet/com.tle.common.applet/build.sbt
- Source/Plugins/Applet/com.tle.web.filemanager.applet/appletsrc/build.sbt
- Source/Plugins/Applet/com.tle.web.filemanager.applet/build.sbt
- Source/Plugins/Birt/org.eclipse.birt.osgi/build.sbt
- Source/Plugins/Core/com.equella.core/jarsrc/build.sbt
- Source/Plugins/Platform/com.tle.platform.equella/build.sbt
- Source/Server/adminTool/build.sbt
- Source/Server/conversion/build.sbt
- Source/Server/equellaserver/build.sbt
- Source/Tools/UpgradeInstallation/build.sbt
- Source/Tools/UpgradeManager/build.sbt
- autotest/IntegTester/build.sbt
- autotest/Tests/build.sbt
- autotest/build.sbt
- build.sbt
- project/CommonSettings.scala
- project/JPFPlugin.scala
- project/JPFRunnerPlugin.scala
- project/JPFScanPlugin.scala
- project/JarSignerPlugin.scala
- project/YUICompressPlugin.scala
- project/build.properties
With PR #2912 we picked up a _whole lot_ of SBT deprecation warnings which you see the first time your run SBT for the project (as it compiles the `**/build.sbt` and `project/*.scala`). There were two main categories of them:
1. Deprecation of the slash syntax as per https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
2. Deprecation of IO.zip and replacing with a new version which takes a third param of type Option[Long] to represent timestamps due to SBTs move to support binary reproducible builds.
You'll see there's one commit for each of these.
I also snuck in:
1. Upgrade to SBT 1.5.2; and
2. A few other minor syntax tweaks here and there as recommended by IntelliJ
As a result of this, clean SBT start-up (after deleting `target` and `project/target`) looks like: …
> chore: Address SBT deprecation warnings due to upgrade to 1.5

- build.sbt
It seems that although the check is failing it wasn't stopping the CI - even though `$? != 0`. Maybe doing it with SBT's exception mechanisms will do so.
If this fix works, I expect the GHA build to fail on the build and check job. (Maybe then I'll add additional commits to address the checkstyle issues.)
> chore(SBT): Attempt to end CI on checkJavaCodeStyle failure

- Platform/Plugins/com.tle.platform.common/src/com/dytech/devlib/Md5.java
- Platform/Plugins/com.tle.platform.common/test/java/com/dytech/devlib/Md5Test.java
- build.sbt
This class (Md5) was the source of the most warnings in the CheckStyle
report. When looking at the class it became obvious it was just a
decompiled MD5 implementation which is rather redundant when there are
many standard offerings out there now. Indeed, even across the oEQ base
although there are many uses of this, there are also uses of others.
So to at least tidy things up, this has been refactored. However
arguably a refactoring to consolidate hashing on a broader scale should
be undertaken. This might be easier now with this one tidied up.
(Added the unit test before the refactor so that I could validate there
was no change.)
> refactor(server): Replace decompiled MD5 implementation

- Source/Server/equellaserver/build.sbt
Unfortunately 5.1.0 requires a newer version of Zk and that version is
not available as a standard debian package yet - so we'd have to change
our CD Zk cluster to test with. But at least 4.3.0 is still
significantly newer that what we had.
Will schedule in time to upgrade our CD environment and then revisit
upgrading to 5.x series.
Note: Just to clarify, the minimum supported Zk version for Apache
Curator is 3.5.x but debian is still on 3.4.13.
For testing I did run up the docker-compose locally with three nodes and confirmed they were all communicating and properly scheduling distributed tasks (like thumb-nailing and indexing).
> chore(deps): Rollback Apache Curator to 4.3.0

- oeq-ts-rest-api/package-lock.json
- oeq-ts-rest-api/package.json
Not sure why this was there, however based on what it is (a TS REPL) and the fact all tests etc pass without it, I think we can drop it.
> chore(deps): Remove unnecessary ts-node

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthserver/OAuthServerAccess.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/GenericDaoImpl.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/replicatedcache/dao/ReplicatedCacheDao.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/replicatedcache/dao/ReplicatedCacheDaoImpl.java
This PR replaces the Scala `CacheValue` with the Java one and replaces Scala `tokenQuery` with Java `ReplicatedCacheDao` in `OAuthServerAccess`.  The changes are mostly around the feature of Cloud provider. Due to my limited knowledge of Scala monad, I am honestly not 100% confident in whether the simplified code works as exactly the same as how those monads work. But I did run through the feature of Cloud provider locally and every things seem fine.
Unfortunately, we can't remove all the code related to the use of simpleDBA until we rewrite `CloudProviderDB`.
Register a CP.
Use a CP  Wizard control.
> Refactor `OAuthServerAccess.scala`

- react-front-end/tsrc/modules/GallerySearchModule.ts
#2936 
Exclude MIME types in gallery searches, but selected MIME type filters are still kept so that when we switch back to the standard search page, filters still get selected.
Please note that `external MIME types` are still included in gallery searches if they are provided.
> Exclude `mimeTypes` from a gallery search

- .github/workflows/ci.yaml
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/src/Utils.ts
- oeq-ts-rest-api/test/schema.test.ts
We seem to be missing these checks, and currently their are a couple of issues. ~~So at first I expect this PR to fail, and then we need to make a few minor commits to address the issues. (But I want to confirm it fails first to ensure I've probably added the new task.)~~
A quick run down of the issues being fixed:
- `Search.ts` : Add missing explicit return types - straightforward enough, and of good value;
- `Utils.ts` : Stop using `any` and replace `unknown` for known objects to `Record<string,unknown>` as per TS best practice. Also as a result add some more explicit run-time type validation to ensure we're working on what we think we are. Which ultimately, is why ESLint raises warnings around `any`.
- `schema.test.ts` : Rework conditional `expect` calls to ensure no false positives. …
> chore(ci): Include ESLint checks for oeq-ts-rest-api

- react-front-end/__tests__/tsrc/search/components/SearchResult.test.tsx
- react-front-end/tsrc/search/components/SearchResultAttachmentsList.tsx
#3044 
Caught during testing, we weren't omitting the dead attachments from prepareDraggable, so even though the select button was missing you could still drag n drop a dead attachment in a selection session.
Simply filtered the list that gets passed in to not include dead attachments.
Also surrounded with a Jest Test to ensure this doesn't happen again. 
> Make dead attachments not draggable

- react-front-end/package-lock.json
- react-front-end/package.json
- react-front-end/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
This came from #2435  - since I made a code change I'm making a new PR.
This branch failed because the Editor became completely non-interactible, typing would do nothing. 
This is because the `htmlInput` prop we were using plugs into the Editor's value parameter. In previous versions, 
this would work as an _initial_ value - every edit would run the `onStateChange` callback but `htmlInput` didn't need to change. 
Now, this works as a standard controlled component and `htmlInput` _is_ the value - meaning if it doesn't update, TinyMCE won't either. We were already holding state for this in this.state.current.notice, for `preventNavigation` checks - it just needs feeding back in.
As `this.state.current.notice` is initialized at the same time as `this.state.db.notice`, we don't need to change …
> Update @tinymce/tinymce-react to 3.12.6

- Platform/Plugins/com.tle.platform.common/src/com/tle/core/plugins/AbstractPluginService.java
- Platform/Plugins/com.tle.platform.common/src/com/tle/core/plugins/PluginService.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
We only want to include the CSS file when Kaltura Plugin is activated. In order to do this, add a new method to
support checking if a plugin is activated.
When Kaltura is activated: 
When it is not acitivated:
> chore: include Kaltura Upload control CSS in new UI

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
- react-front-end/tsrc/components/YouTubeEmbed.tsx
Make sure the reset rule in legacy.scss doesn't apply to the youtube preview iframe,
as width:auto and height:auto cause the preview to render incorrectly.
#2934 
The small YouTube preview panel was caused by the "Reset rule" at the top of legacy.scss. This reset rule is designed to unset any rules that apply to common tags and replace them with an openEQUELLA default value.
```css
html,
body,
div,
span,
applet,
iframe,
h1,
h2,
h3,
h4,
h5,
h6,
p,
blockquote,
pre,
a,
abbr,
acronym,
address,
big,
cite,
code,
del,
dfn,
em,
font,
ins,
kbd,
q,
s,
samp,
small,
strike,
strong,
sub,
sup,
tt,
var,
b,
u,
i,
center,
dl,
dt,
dd,
ol,
ul,
li,
fieldset,
form,
label,
legend,
input,
textarea,
table,
caption,
tbody,
tfoot,
thead,
tr,
th,
td,
select {
width: auto;
height: auto;
margin: 0;
padding: 0; …
```
> Exclude YouTube preview player from legacy.scss Reset rule

- .husky/pre-commit
- package.json
There was a renovate upgrade and automerge of Husky from 4.x to 7.x over
night. However this should've also included a migration of the husky
configuration as the approach has drastically changed.
See more at:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
(Note: Build status - after checks have passed - is irrelevant for this PR.)
> chore: migrate husky config to version 7

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
- oeq-ts-rest-api/src/Search.ts
This PR adds one optional field for Item DRM settings on both server and client. 
On server, I added a couple case classes to represent DRM settings and extended `SearchResultItem` to include DRM settings.
On client, I updated type definitions to match server side changes.
In terms of what specific DRM settings are included, I looked into `terms.ftl` and add whatever this template may render to the new field. Due to my limited experience of DRM, there may be more DRM settings we need to include in future work. 
With this approach, we don't need another endpoint to retrieve terms.
https://user-images.githubusercontent.com/47203811/124223575-5038e900-db47-11eb-926c-5457d492f37c.mp4
> Feature/add Item DRM settings to search2 API

- renovate.json
So as to reduce all the `@types` PRs.
See also: https://docs.renovatebot.com/presets-group/#groupdefinitelytyped
> chore(deps): Use group:definitelyTyped renovate preset

- react-front-end/__mocks__/searchOptions.mock.ts
- react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/SearchPageHelper.ts
- react-front-end/tsrc/search/SearchPageReducer.ts
Following a pattern I started in openequella/react-kaltura-simpleuploader , this pushes the reducer and supporting types out into a standalone file to assist with managing the size of `SearchPage.tsx` as well as aiding any additional testing etc we may wish to do.
> refactor(react-front-end): Break out SearchPage's reducer

- Source/Plugins/Core/com.equella.base/src/com/tle/web/api/item/interfaces/beans/AttachmentBean.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeAttachmentBean.java
This enables for previewing Kaltura media in search results and galleries. And by adding this to `AttachmentBean` also supports work in the future with Summary Pages etc.
Integrating with this will also be a PR over at https://github.com/openequella/openEQUELLA-Kaltura
> feat: Return Kaltura externalId in search results

- react-front-end/__mocks__/searchresult_mock_data.ts
- react-front-end/__tests__/tsrc/search/SearchPageHelper.test.ts
- react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
- react-front-end/__tests__/tsrc/search/components/SearchResult.test.tsx
- react-front-end/tsrc/components/ItemAttachmentLink.tsx
- react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
- react-front-end/tsrc/components/OEQLink.tsx
- react-front-end/tsrc/drm/DrmHelper.tsx
- react-front-end/tsrc/search/SearchPageHelper.ts
- react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
- react-front-end/tsrc/search/components/SearchResult.tsx
This PR adds the support of showing DRM Acceptance dialog when users attempt to view an Item. On standard list mode, the dialog pops up when an Item link is clicked,  and on gallery mode the dialog pops up when an Info icon is clicked. 
Once the terms are accepted, Item Summary page will be opened by different approaches, depending on whether in Selection Session or not.
https://user-images.githubusercontent.com/47203811/126739698-8e628e1c-e74c-48ff-b687-0971b440d790.mp4
> Feature/integrate DRM Acceptance dialog with Item

- react-front-end/__mocks__/GallerySearchModule.mock.ts
- react-front-end/__tests__/tsrc/FpTsMatchers.ts
- react-front-end/__tests__/tsrc/components/Lightbox.test.tsx
- react-front-end/__tests__/tsrc/components/LightboxHelper.test.ts
- react-front-end/__tests__/tsrc/modules/GallerySearchModule.test.ts
- react-front-end/__tests__/tsrc/modules/KalturaModule.test.ts
- react-front-end/tsrc/components/KalturaPlayerEmbed.tsx
- react-front-end/tsrc/components/Lightbox.tsx
- react-front-end/tsrc/components/LightboxHelper.tsx
- react-front-end/tsrc/components/LightboxMessage.tsx
- react-front-end/tsrc/modules/AttachmentsModule.ts
- react-front-end/tsrc/modules/GallerySearchModule.ts
- react-front-end/tsrc/modules/KalturaModule.ts
- react-front-end/tsrc/modules/MimeTypesModule.ts
- react-front-end/tsrc/util/langstrings.ts
This PR integrates all the other work and provides support for Kaltura media in the the New Search UI Video Gallery. There will be a subsequent PR which will add similar support for previewing Kaltura media via the lightbox in standard list mode.
Also there is a future piece of work to add support for high-res thumbnails. But that's outside of this PR.
The only area of note of the implementation is how the `externalId` value (containing the the delimited values we need to embed a player) from the search results through to the Lightbox that really only wants a MIME type and a `src`. For this I decided to simply add the `externalId` as a param to the `src` URL and then in the Lightbox pull it off and parse it when needed. Further, there was no issue leaving this in place for the viewing in …
> Video Gallery support for Kaltura Media

- react-front-end/__mocks__/Drm.mock.ts
- react-front-end/__mocks__/searchresult_mock_data.ts
- react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
- react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
- react-front-end/__tests__/tsrc/search/components/GallerySearchResultHelpers.ts
- react-front-end/__tests__/tsrc/search/components/SearchResult.test.tsx
- react-front-end/tsrc/drm/DrmHelper.tsx
- react-front-end/tsrc/modules/DrmModule.ts
- react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
- react-front-end/tsrc/search/components/SearchResult.tsx
This PR adds the support for listing DRM violations for unauthorised Items and attachments. The main change is to update the logic of DRM check in `DrmHelper`. This change results in function `createDrmDialog` becoming an async function, and therefore the `useEffect` which uses this function gets slightly changed as well. 
I tried to implement a custom hook `useAsyncEffect` but stopped after a couple hours experiments as I thought the next DRM ticket is more important.
https://user-images.githubusercontent.com/47203811/127578666-fe879e2a-1ea5-4687-9571-f3371a170598.mp4
> Feature/show DRM violations in dialog

- react-front-end/tsrc/drm/DrmHelper.tsx
- react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
- react-front-end/tsrc/search/components/GallerySearchResult.tsx
This PR includes two parts. 
1. Only show gallery entries that have been accepted DRM terms and authorised.
2. Add the gallery entry that has just been accepted to the Lightbox entry list.
https://user-images.githubusercontent.com/47203811/127603321-e7dbe9e5-f2a4-46e0-bbe9-b0bff7267800.mp4
> Feature/only show authorised entries in Lightbox

- react-front-end/__tests__/tsrc/modules/AttachmentsModule.test.ts
- react-front-end/__tests__/tsrc/modules/ViewerModule.test.ts
- react-front-end/tsrc/modules/AttachmentsModule.ts
- react-front-end/tsrc/modules/GallerySearchModule.ts
- react-front-end/tsrc/modules/KalturaModule.ts
- react-front-end/tsrc/modules/MimeTypesModule.ts
- react-front-end/tsrc/modules/ViewerModule.ts
This adds the ability to preview Kaltura videos in the Lightbox of the new Search UI when in list mode. This is similar to that provided by #3237 
Noticeably there were tests missing around the YouTube support for this, so I had to add some basic new ones to cover both.
> feat(react-front-end): preview kaltura videos in list-mode search

- react-front-end/tsrc/search/components/GallerySearchResult.tsx
A bug was found during testing work for the feature of filtering out gallery entries that are not authorised to view.
When switching between gallery modes, the previous gallery entries were not cleared out. As a result, images were displayed in the Lightbox when Search page was in Video mode.
So this PR fixes this issue by adding a `useEffect` which updates the state of gallery entries when the mode is changed.
> bugfix: ensure gallery entries are consistent with gallery mode

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/treeviewer/AbstractTreeViewerSection.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/drm/DRMTest.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/viewitem/DRMAgreementPage.java
#1160 
This bug was firstly caused by `LegacyContentApi` failing to parse the URL, which resulted in Item version being -1.
After above issue was fixed, the next issue was the page stayed in Summary page rather than going to the DRM acceptance page. After lots of investigations, I found the key thing is to make sure `RootItemFileModel` has a proper file name which can be extracted from the URL and is used to determine what viewers to be used in the full screen mode.
After fixing the second issue, there was a third issue. Once DRM terms had been accepted, although the page showing contents was opened, the page looked very bad because CSS styles applied to this page were never included in `Legacy.scss`.
Once the third issue was fixed, this bug was completed fixed. So I reverted workaround …
> Bugfix/show DRM acceptance page before viewing content in full screen

- react-front-end/package.json
Since upgrading to node 16 / npm 7 the renovate updates have been
failing due to renovate-checks. The checks are throwing up all kinds of
NPM errors which the CI pipelines don't experience.
This is based on the PR by @HonkingGoose over at:
https://github.com/renovatebot/renovate/pull/8559
> build: attempt to stop renovate errors for react-front-end

- react-front-end/tsrc/search/components/CollectionSelector.tsx
- react-front-end/tsrc/util/langstrings.ts
Use `All` as the default text of Collection Selector when there is no collection available.
> chore: change the default text of Collection Selector

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/equella/render/ButtonRenderer.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/standard/renderers/AbstractElementRenderer.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/summary/filter/DRMLicenseDialog.java
In new UI, the legacy DRM acceptance dialog is usually NOT open by `LegacyContent.tsx`, which means additional CSS files will be added to the whole page once the dialog is opened. One of those additional CSS files is `Bootstrap.css` which can break new UI components like buttons. So this PR adds a fix which allows the DRM dialog to include this CSS file only in Old UI.
Before: 
After:
Before: 
After:
> bugfix: don't include Bootstrap.css when open legacy DRM dialog in new UI

- Source/Server/equellaserver/build.sbt
Major upgrade to the last Java 8 supported version. (5 is now available, but only for 11+.)
Came to my attention due to #3316 
Rebuilt fine locally and passed really quick smoke test - which confirmed DB access.
> chore(deps): upgrade to HikariCP 4.0.3

- react-front-end/tsrc/mainui/IndexPage.tsx
- react-front-end/tsrc/mainui/routes.tsx
- react-front-end/tsrc/search/SearchPage.tsx
The initial implementation for Advanced Search routing was not actually resulting in a fresh SearchPage instance. So by adding a `key` to the SearchPage JSX we can ensure a new one is created for each unique Advanced Search.
Further, this highlighted we could move the Advanced Search routing into the New Routes paradigm.
> refactor: ensure new versions of SearchPage for different routes

- react-front-end/tsrc/search/components/SearchResult.tsx
Due to the support for DRM, we need to update state to show or hide the DRM
dialog. However, when a non-DRM item is clicked, the page just navigates to
Summary page, which unmounts the component. In this case, we should skip the
state update.
> bugfix: do not update SearchResult state when it is unmounted

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#2918 
This PR fixes the issue where clicking the caret icon (as a background image) of bulk action list does not show the list. The issue was caused by a 'padding-right' which moved where the icon was supposed to be. Although there were no visual differences, the position of the icon was indeed moved.
Before: 
After:
> bugfix: ensure clicking the caret icon can show the bulk action list

- Source/Plugins/Core/com.equella.core/swaggerui/package-lock.json
- Source/Plugins/Core/com.equella.core/test/javascript/package-lock.json
- autotest/IntegTester/ps/package-lock.json
- autotest/IntegTester/ps/package.json
- react-front-end/package-lock.json
In order to migrate the `package-lock` of `IntegTester`  to version 2, we need to using a https link resolving to the tarball of 
`oeq-cloudproviders` due to a NPM bug (https://github.com/npm/cli/issues/2610).
So in the repo of `oeq-cloudproviders` I created a new tag to support the migration.
> build: migrate IntegTester to lockfile version 2

- Source/Plugins/Admin/com.tle.web.adminconsole/build.sbt
This was only needed when launched via JLNP. But that support was
removed back in 2019.1, and we now use the Admin Console Launcher
Package.
Not sure if this is optimum SBT, however due to the dependency structure it seems easiest way to maintain that. (i.e. the use here of `(adminConsoleJar / assembly).value`)
> chore(build): stop signing Admin Console JAR

- Source/Plugins/Core/com.equella.core/swaggerui/package.json
- Source/Plugins/Core/com.equella.core/test/javascript/package.json
- autotest/IntegTester/ps/package.json
- oeq-ts-rest-api/package.json
- package.json
- react-front-end/package.json
specify the npm version in all 'package.json' files. However, the version is pinned to `7.19.1` because newer versions can fail renovateBot builds. The reason is still unknown.
> chore: specify the npm version in all 'package.json' files

- oeq-ts-rest-api/package.json
- react-front-end/package.json
The `prepare` script in `oeq-ts-rest-api` seems redundant as we can build the module when we run `npm install` for  `react-front-end`. So this PR removed The `prepare` in `oeq-ts-rest-api`.
> chore: update NPM scripts to correctly build the REST module

- .github/workflows/ci.yaml
- autotest/IntegTester/ps/.gitignore
- autotest/IntegTester/ps/install.js
- autotest/IntegTester/ps/package-lock.json
- autotest/IntegTester/ps/package.json
With NPM 7 `psc-package` is not installed properly. So we created a new NPM script which will downloaded the package and use it.
This issue was originally found in `renovate` PRs (e.g. #3380 ) which failed to update `package-lock.json`.
> chore: install `psc-package` via a NPM script

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#2970 
This black line shouldn't exist on the DRM page - adding a simple CSS rule to hide it. 
Before: 
After:
> Prevent black line from displaying on DRM page

- Source/Plugins/Core/com.equella.base/src/com/tle/common/taxonomy/wizard/TermSelectorControl.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/wizard/controls/userselector/UserSelectorControl.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/AdvancedSearchResource.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardControlHelper.scala
- oeq-ts-rest-api/src/AdvancedSearch.ts
- oeq-ts-rest-api/src/Taxonomy.ts
- oeq-ts-rest-api/src/wizard/WizardCommonTypes.ts
- oeq-ts-rest-api/src/wizard/WizardControl.ts
- oeq-ts-rest-api/test/AdvancedSearch.test.ts
This PR adds the support for retrieving Advanced search to the REST Module. 
The major change is creating different data structures to support Wizard controls used in Advanced search. And a new function was added to talk to the endpoint.
> feat: support for retrieving Advanced search definition in REST Module

- react-front-end/tsrc/mainui/App.tsx
- react-front-end/tsrc/mainui/index.tsx
- react-front-end/tsrc/search/SearchPage.tsx
As the front-end is about to become even more complex would be good to be able to add some basic logging which we can leave in place.
Maybe in the future we can build some common functions, but I don't think we need to bring in one of the various JS logging libraries at this point. Just keeping it simple and using what the browser gives us.
As we start doing this more, then we'll see what kind of pattern we really want to support, and add a group of functions to match.
> chore(front-end): facilitate leave in debug logging

- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/__tests__/tsrc/search/SearchPageTestHelper.tsx
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/components/SidePanel.tsx
This PR adds the feature of not showing Collection Selector and Classification panel in Advanced search mode. 
Also the REST API call to list Classifications will not be executed. Should not need to list Collections as well, but due to the existing implementation this will require more changes.
https://user-images.githubusercontent.com/47203811/133177963-7685b440-e692-44eb-8707-ed476a0a1ae7.mp4
> feat: don't show Collection Selector in Advanced search page

- oeq-ts-rest-api/src/Taxonomy.ts
- oeq-ts-rest-api/src/index.ts
- oeq-ts-rest-api/test/Taxonomy.test.ts
This PR adds the support for listing taxonomy terms to REST Module.
Two functions have been created. One is used to search child terms, given a path. The other one is used to search terms by query.
> feat: support for listing taxonomy terms in REST Module

- react-front-end/__mocks__/WizardHelper.mock.ts
- react-front-end/__stories__/components/wizard/WizardEditBox.stories.tsx
- react-front-end/__stories__/components/wizard/WizardLabel.stories.tsx
- react-front-end/__stories__/components/wizard/WizardUnsupported.stories.tsx
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardEditBox.tsx
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/components/wizard/WizardLabel.tsx
- react-front-end/tsrc/components/wizard/WizardUnsupported.tsx
- react-front-end/tsrc/util/langstrings.ts
The is the first part / foundation of the Advanced Search Form. It provides:
- 3 new components (`WizardEditBox`, `WizardLabel` and `WizardUnsupported`)
- `WizardHelper` with the logic for rendering a wizard definition
- Storybook stories for the new components
- Unit tests for the `WizardHelper`
Next step/part is to then integrate this with the new `AdvancedSearchForm`. And following on from that, is to implement and support all the wizard control types (and then visibility scripting).
I've not included screenshots, as I've already walked @PenghaiZhang through the new components.
And, I expect this will be further tweaked as we get into the integration and later and more components. But hopefully it provides a reasonable foundation for us.
[contributor license agreement]: …
> Feature/advanced search form (part 1)

- Source/Plugins/Core/com.equella.core/src/com/tle/web/hierarchy/HierarchyMenuContributor.java
#556 
This PR can make sure that when the Hierarchy `More` menu is clicked, the full list of Hierarchies is always displayed.
https://user-images.githubusercontent.com/47203811/134279674-b02daf3e-5adc-477b-b474-7a9f73a2342d.mp4
> bugfix: make sure the Hierarchy `More` menu uses the correct link

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
#2969 
The fix is removing the `text-align: right` applied on those buttons. I also added some adjustments for the margin between the save panel and wizard panel.
> bugfix: fix Contribution save panel UI issue where buttons are cut off

- react-front-end/__stories__/search/AdvancedSearchPanel.stories.tsx
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardEditBox.tsx
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/SearchPageModeReducer.ts
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
This integrates the previous work (#3420) to process a wizard definition into the actual search panel (and to some degree the search page - as far as storing the values). It did highlight the direction (rabbit hole) I went in the first PR for storing the control values was incorrect, so a refactor is also included here.
I will do a subsequent PR to this one to get some Jest tests going. But just wanted to get the core finalised before I go on leave. :wink:  (As you can see though, I did at least tweak the Storybook stories.)
https://user-images.githubusercontent.com/43919233/134453464-2aaaa163-4fa2-4550-8604-c2e67faf2392.mp4
> Feature/advanced search form (part 2)

- react-front-end/__stories__/components/wizard/WizardShuffleList.stories.tsx
- react-front-end/__tests__/tsrc/components/wizard/WizardShuffleList.test.tsx
- react-front-end/tsrc/components/wizard/WizardShuffleList.tsx
- react-front-end/tsrc/util/langstrings.ts
Adds a new Wizard component: Shuffle List. Following this PR will be an integration PR.
Before a user adds values:
Once a user adds values (note they are sorted, and can be removed via the delete buttons):
> feat(front-end): add WizardShuffleList component

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
The testing work found that if the default value of Calendar is configured as `today` or `today plus xx days`, the default value is not displayed properly in the advanced search panel.  The reason is when using `today`, the value is actually a number which represents how many days to be added to today.
So the fix is to check if the value is numeric, if yes then plus it to the day of today, otherwise use the value.
Please note that the Date Range Selector will show a warning if the default day is a future day.
> refactor: update how to build the default value of Calendar

- react-front-end/package-lock.json
- react-front-end/package.json
Remove unused deps typescript-fsa, typescript-fsa-reducers and timeago-react
Resolves #3551 and #3552 
> fix(deps): remove unused deps

- Source/Plugins/Core/com.equella.base/src/com/tle/common/search/DefaultSearch.java
- Source/Plugins/Core/com.equella.base/src/com/tle/common/searching/Search.java
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/tokenisation/TokenisationResource.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/ItemIndex.java
- Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/remoting/resteasy/RestEasyServlet.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/TokenisationApiTest.java
This is the first PR for supporting the advanced search criteria. 
The steps are:
1. Add a new field to `SearchParam` to receive lucene query sent from client.
2. Set the lucene query to the new field added in `DefaultSearch`.
3. In the method which builds the whole query, parse the lucene query and combine it to other queries.
Also includes:
- A new /api/search/token endpoint to use lucene to tokenise a raw string (so that it can be used to build up 'tokenised' queries for advanced search controls)
> feat(REST): add support to search2 for raw lucene query and add new tokenisation endpoint

- react-front-end/__mocks__/WizardHelper.mock.ts
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
Add mock data and control type for `Html`, `Check box` group and `List box`. Based on #3539 ticket.
> Test: add mock data and control type for 3 wizard components

- autotest/OldTests/src/test/java/io/github/openequella/search/AdvancedSearchPageTest.java
- oeq-ts-rest-api/src/Search.ts
- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/__tests__/tsrc/search/SearchPageTestHelper.tsx
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/modules/SearchModule.ts
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/SearchPageHelper.ts
- react-front-end/tsrc/search/SearchPageModeReducer.ts
- react-front-end/tsrc/util/langstrings.ts
This is the fourth (and hopefully the last) PR for the advanced search criteria. It's all about the integration with `SearchPage`.
Main changes are:
1. Add a new field to `SearchParam` and `SearchOptions` to support the raw Lucene query.
2. Hide the Adv search panel whenever a search is triggered.
3. Update how to generate the initial advanced search query values.
4. Rework how to perform the initial search.
5. Update how to check if any adv search criteria has been set.
> feat: integrate Advanced search criteria with New Search UI

- react-front-end/tsrc/components/RichTextEditor.tsx
Convert RichTextEditor from class component to functional component.
> refactor: convert RichTextEditor from class to functional component

- Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/ItemIndex.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
- react-front-end/__mocks__/WizardHelper.mock.ts
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
This is the fifth PR to support the Advanced search criteria. Previous testing work found that if a value is phrase, the parsed Lucene query is not quite right. So this PR brings in the fix and updates the test as well.
The fix includes changes on both server and client. On server, we use `KeywordAnalyzer` instead of `TleAnalyzer` to when the raw query is parsed. on Client, we add `""` for each term and phrase unless the control supports tokenisation or the control is a Calendar.
I also noticed that the query built from `ShuffleList` still has one issue so I fixed that in this PR.
> refactor: use KeywordAnalyzer to support the phrases in Lucene query

- react-front-end/__mocks__/UserSearch.mock.ts
- react-front-end/__stories__/components/wizard/WizardUserSelector.stories.tsx
- react-front-end/__tests__/tsrc/components/wizard/WizardUserSelector.test.tsx
- react-front-end/__tests__/tsrc/modules/UserModule.test.ts
- react-front-end/tsrc/components/SelectUserDialog.tsx
- react-front-end/tsrc/components/wizard/WizardUserSelector.tsx
- react-front-end/tsrc/modules/UserModule.ts
- react-front-end/tsrc/search/components/OwnerSelector.tsx
- react-front-end/tsrc/util/langstrings.ts
Here is the User Selector Wizard control. It re-uses existing functionality to search for users, however further updates are still to come to properly support the level of multi-user selection capable with the legacy user selector (as that common control will need to be further developer). Additionally, there is not yet support for filtering to specific groups etc.
It does include some optimisation to minimise server calls to resolve full user details, however there slightly more optimisation could be done but things were getting out of hand. That said though, it should be fine without those but if needs be adding it wont be too involved. (I'll highlight what this is in comments on the code.)
Up next I'll integrate this into the wizard/advanced search, and then loop back around after that …
> feat(front-end): add User Selector wizard component

- oeq-ts-rest-api/src/Theme.ts
- oeq-ts-rest-api/src/index.ts
- oeq-ts-rest-api/test/Theme.test.ts
- oeq-ts-rest-api/tsconfig.json
Create api with tests for Theme module.
API: 
- getThemeSettings,
- updateThemeSettings,
- getThemeLogo,
- updateThemeLogo,
Because I am still struggling with tests for theme logo, only contains tests for:
- getThemeSettings
- updateThemeSettings
> feat(rest-api): add support for the theme endpoint to oeq-ts-rest-api

- autotest/OldTests/src/test/java/io/github/openequella/rest/DrmApiTest.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/selection/SelectionStatusPage.java
Trying to fix this issue, but failed to reproduce in local env. 
But based on this [reference](https://stackoverflow.com/questions/38596456/how-to-over-staleelementreferenceexception-when-working-with-pagefactory)  I add a waiter before clicking the finish button. Not sure if it works or not.
> fix(test): remove flakiness of MyResourcesTest - testAddMyResource

- Source/Plugins/Core/com.equella.core/src/com/tle/core/facetedsearch/bean/FacetedSearchClassification.java
#3021 
This index is longer than 30 characters, which causes problems for Oracle Database 12c Release 1 or earlier. 
When Oracle Database 12c Release 2 was released they increased the character limit to 128. 
This seems to be the only place this index is referred to.
> Reduce the length of the facetSearchClassificationInstitutionIndex name

- react-front-end/__mocks__/GroupModule.mock.ts
- react-front-end/__mocks__/UserModule.mock.ts
- react-front-end/__mocks__/UserSearch.mock.ts
- react-front-end/__mocks__/searchOptions.mock.ts
- react-front-end/__stories__/components/UserSearch.stories.tsx
- react-front-end/__stories__/components/wizard/WizardUserSelector.stories.tsx
- react-front-end/__stories__/search/OwnerSelector.stories.tsx
- react-front-end/__tests__/tsrc/components/UserSearch.test.tsx
- react-front-end/__tests__/tsrc/components/wizard/WizardUserSelector.test.tsx
- react-front-end/__tests__/tsrc/modules/UserModule.test.ts
- react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
- react-front-end/__tests__/tsrc/search/SearchPageHelper.test.ts
- react-front-end/__tests__/tsrc/search/components/OwnerSelector.test.tsx
- react-front-end/tsrc/components/SelectUserDialog.tsx
- react-front-end/tsrc/components/UserSearch.tsx
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/components/wizard/WizardUserSelector.tsx
- react-front-end/tsrc/modules/GroupModule.ts
- react-front-end/tsrc/modules/UserModule.ts
- react-front-end/tsrc/util/langstrings.ts
This adds support for the feature of the Wizard User Selector control where one or more groups can be configured to limit the users returned in search results - and thereby the users available for selection.
Points of note:
- Refactoring was done to create a new `UserModule.mock.ts` from what was in `UserSearch.mock.ts` to better align the emergent naming standard for our mocks - which was highlighted when creating the new `GoupModule.mock.ts`. This resulted in a lot of minor updates to `*.test.ts*` and `*.stories.tsx` files.
- In the interest of time, no additional tests (other than a minor one) have been explicitly added for this, but manual testing and testing via the new storybook test was undertaken.
- Main effort is focused in `UserSearch.tsx` with support from `GroupModule.ts` …
> Add support to the Wizard User Selector for filtering by group

- react-front-end/__mocks__/WizardHelper.mock.ts
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/components/wizard/WizardSimpleTermSelector.tsx
This PR integrates the `WizardSimpleTermSelector` into the Advanced search panel. Due to time limit I only updated `WizardHelper.test`.
https://user-images.githubusercontent.com/47203811/144141588-037d119b-e394-47b6-821b-20bfb5db5c3e.mp4
> feat: integrate WizardSimpleTermSelector with Adv search panel.

- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/SearchPageModeReducer.ts
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
Add a flag to keep the search panel open.
Add a useEffect in AdvancedSearchPanel to update state value 
Change the corresponding test.
https://user-images.githubusercontent.com/92769668/143172913-a5778d59-f8f3-4c3a-95ea-977138bad2d6.mp4
> feat(frontend): keep advanced search panel open after clicking clear button

- react-front-end/__mocks__/AdvancedSearchModule.mock.ts
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/__tests__/tsrc/modules/ScriptingModule.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/modules/ScriptingModule.ts
Provides a minimal basic implementation of visibility scripting based on the values of other controls which you could build via the Admin Console scripting UI. (That is, supporting `contains` and `get` on the `xml` object.)
Two main outstanding parts to come (in future PRs):
- Support for the `user` object (only `hasRole` as that's all the Admin UI uses); and
- Clearing the values for controls which become hidden
https://user-images.githubusercontent.com/43919233/144365517-b9d4b905-b97c-4588-9ea6-889658216039.mp4
> feat(frontend): add basic visibility scripting support

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
- oeq-ts-rest-api/src/LegacyContent.ts
- oeq-ts-rest-api/test/auth.test.ts
- react-front-end/__mocks__/UserModule.mock.ts
- react-front-end/tsrc/legacycontent/LegacyContent.tsx
Quick tweak to `currentuser` endpoint to support returning `roles` so that we have it available for the `user` object in  visibility scripts.
Minor tidy-up of endpoint code too, mainly so that we can have better Swagger doco.
> feat: Updte /api/content/currentuser to also return roles

- autotest/OldTests/src/test/java/io/github/openequella/search/AdvancedSearchPageTest.java
- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/tsrc/search/SearchPageModeReducer.ts
https://user-images.githubusercontent.com/92769668/143371258-08fb7ab5-225c-4a0c-8187-e66528687af6.mp4
Updated comment for `overrideHide` state:  [#3595](https://github.com/openequella/openEQUELLA/pull/3595#pullrequestreview-821010760).
Changed two initial values in `SearchPageModeReducer` for `initialiseAdvSearch` action.
Updated test helper `renderAdvancedSearchPage` function since now the panel is open after the first search.
> feat(frontend): Keep Advanced Search panel open when user first selects an advanced search

- react-front-end/tsrc/util/langstrings.ts
Change help text for new Open item summary page button from `Open Item Summary page` to `Open resource summary page`.
> chore: change help text for new Open item summary page button to Open resource summary page

- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/__tests__/tsrc/modules/ScriptingModule.test.ts
- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/legacycontent/LegacyContent.tsx
- react-front-end/tsrc/mainui/Template.tsx
- react-front-end/tsrc/modules/ScriptingModule.ts
- react-front-end/tsrc/modules/UserModule.ts
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
This adds basic support for the `user` object in visibility scripts. The goal was to have enough support for the scripts generated by the UI in the Admin Console. That would only require hasRole, but it wasn't too involved to add a few of the other basics quickly.
Also addressed a warning in the AdvancedSearchPage.test due to the togglePanel not correctly using `act()`.
I undertook manual testing with scripts testing various live combinations of roles and username etc.
> feat: Add support for the `user` object in Visibility Scripts

- react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
- react-front-end/__tests__/tsrc/search/components/SearchResult.test.tsx
- react-front-end/tsrc/components/Lightbox.tsx
- react-front-end/tsrc/util/langstrings.ts
Add help text for Open in new tab button in Lightbox.
Add help text for Close button in Lightbox.
Add help text for Copy buttton in Lightbox.
I use TooltipButton instead of IconButton, but we lost the background animation for Open in new tab icon.
https://user-images.githubusercontent.com/92769668/144938832-1e456ec9-87bd-4255-be95-9a46213e4f96.mp4
> chore: ensure all Lightbox buttons have tooltips

- react-front-end/__stories__/search/AdvancedSearchPanel.stories.tsx
- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
To match Legacy UI workings, when a field is hidden due to visibility scripting, then it's value should be cleared. This change adds that.
Also includes minor fix to AdvancedSearchPanel.stories... Not sure how long that's been broken....
https://user-images.githubusercontent.com/43919233/144963888-4c22cfb2-9ede-4154-b67d-ed526e948118.mp4
> feat: With visibility scripting, clear values of any hidden fields

- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
Fix additional whitespace in user selector by adding two classes to the root div for wizards in AdvSearchPanel.
Solution found in [here](https://stackoverflow.com/questions/51445959/unexpected-empty-space-using-flexbox).
https://user-images.githubusercontent.com/92769668/144966006-e633327d-04bf-4014-88e9-c61d14f91900.mp4
> fix: additional whitespace in user selector

- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/components/wizard/WizardSimpleTermSelector.tsx
- react-front-end/tsrc/components/wizard/WizardUserSelector.tsx
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
Some Wizard Controls are a bit smarter than others (say, with async
calls) and as a result are prone to have errors. Therefore, we need a
standard way for them to report their errors.
For this, I've created a React Context that sits in WizardHelper so that
any wizard rendered controls can be wrapped in that context and can
rely on it be present. Currently, this is only in the Advanced Search
Panel, but in the future it would be in the components for contribution
wizards.
Tests: Covered mostly be existing tests, plus manual testing to ensure when network connectivity was broken that the standard search page error toast was displayed.
> feat(frontend): add error handling for wizard controls

- react-front-end/__tests__/tsrc/search/AdvancedSearchHelper.test.ts
- react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
- react-front-end/__tests__/tsrc/search/SearchPageHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/search/AdvancedSearchHelper.ts
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/SearchPageHelper.ts
This PR adds the support for converting a Legacy advanced search criteria into a `PathValueMap` which can be further used to generated a `FieldValueMap`. As a result, any search shared from Old UI or favourited in Old UI can be viewed in the new Search UI.
Key steps are:
1. Use DOMParser to parse the XML string and generate a DOM tree, and then walk through the tree and build a PathValueMap.
2. Update `AdvancedSearchHelper` to support converting the PathValueMap to the initial FieldValueMap.
https://user-images.githubusercontent.com/47203811/144786714-d47af018-0cc7-44f4-9191-90ac5141fa94.mp4
> Feature/support search shared from old UI

- react-front-end/__stories__/search/AdvancedSearchPanel.stories.tsx
- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/tsrc/search/SearchPage.tsx
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
Show the name of an Advanced search at the top of the Advanced search panel.
> feat: show Advanced search name at the top of the Advanced search panel

- react-front-end/tsrc/fileuploader/InlineFileUploader.tsx
Now attachment actions only display after the user click the edit button.
So before we were misled by the local variable `editable` and props `editable`. :smile: 
It can actually be done in the front end.
https://user-images.githubusercontent.com/92769668/145497673-7911dbc4-1244-4442-8222-4b21031b670f.mp4
> fix: display attachment actions only in editable mode

- react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
Do not execute the visibility script is it's just an empty string. As a result, the Wizard control is visible.
> bugfix: show Wizard control that uses an empty string as visibility scripting

- Source/Server/conversion/build.sbt
- Source/Server/equellaserver/build.sbt
When we upgraded to Tika 2 (#3296) it turns out that the microsoft parser in
standard parsers brings in log4j including an SLF4J binding. This causes
some of our logging to then fail, as it uses SLF4J and picks up the
Log4J2 binding where we only configure Log4J 1.2.x.
This was only new in the version we're currently working on and have not
yet released - 2021.2.
I tested this manually to ensure that Microsoft Office files (tested with docx and doc) are still nicely indexed with searches for words in the content returning the items and highlighting the search result was in the attachments. This means that tika is still successfully extracting text from Microsoft files.
[commit guidelines]: …
> chore(deps): stop tika parsers transitive log4j dep

- react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
- react-front-end/tsrc/util/langstrings.ts
Let the Advanced search panel show a warning if there are multiple matching control types pointing to the same metadata schema node.
https://user-images.githubusercontent.com/47203811/145762843-24c219a9-d740-489e-91ce-9b77bcc8ad56.mp4
> feat: show warning in Advanced search panel 

- react-front-end/__tests__/tsrc/modules/ScriptingModule.test.ts
- react-front-end/tsrc/components/wizard/WizardHelper.tsx
- react-front-end/tsrc/modules/ScriptingModule.ts
This PR adds the support for using  xml.getAll in visibility scripts.
https://user-images.githubusercontent.com/47203811/145932937-d7a380ff-8eac-457f-b5fe-e4192de9d5c8.mp4
> feat: support using `xml.getAll` in visibility scripts

- react-front-end/tsrc/legacycontent/LegacyContent.tsx
When editing an Item, repeatedly submitting a Legacy Content request in a very short period can result in attachments missing or the whole UI broken. Actually, where this bug can happen is not limited to Contribution. For example, double clicking the `Edit this version` button in Resource Summary page can break the UI as well.
To fix this, I added a new type definition in `LegacyContent.tsx` and used `useRef` to create an object which stores the details of the request in progress. And then I can stop the redundant submissions by comparing the details with that of the new request.
https://user-images.githubusercontent.com/47203811/147991371-ffe23149-a2ef-432e-b721-98dececea707.mp4
> bugfix: ensure double clicking the Save button don't lose attachments

- react-front-end/tsrc/legacycontent/LegacyContent.tsx
- react-front-end/tsrc/settings/SettingsPage.tsx
Reload legacy content as needed
Reload legacy content as needed to persist old UI.
Change func reload to open in SettingsPage to handle go back operation.
https://user-images.githubusercontent.com/92769668/148157452-c33f0ae0-462b-43a6-9db9-6b3f1294288c.mp4
> fix(frontend): persist old UI after going into a Settings page that uses Material UI

- react-front-end/package-lock.json
- react-front-end/package.json
I've run unit tests, type checking and done manual testing and all is
fine. I believe this must be left over from some old code, as all is now
typescript so why would we need this?
Resolves #3709 
> chore(deps): removed unused prop-types dependency

- Source/Server/equellaserver/build.sbt
This appears to be unused (based on testing by complete rebuild after
removal, and manual UI usage); most likely as there was also the
dependency for the newer [org.apache.tomcat:tomcat-jsp-api](https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-jsp-api). This newer
one was kept - and is in sync with all the other Tomcat deps due to a
variable.
> chore(deps): remove unused tomcat:jsp-api

- Source/Server/equellaserver/build.sbt
Not sure why this was explicitly included other than possibly when the
migration was done from the 'lib' directory to accommodate what is now a
transitive dependency.
Also, explicitly include a version meant the transitives had to be
excluded where as now that can be simplified and left to its own
devices.
Tested manually locally with full rebuild and then manual mini smoke test.
Resolves #3329 
> chore(deps): remove references to asm

- Source/Server/equellaserver/build.sbt
I'm guessing this was added from when dependencies where just managed in a `lib` directory. As the Tika parsers from Microsoft office documents do have a transitive dependency - so we can just leave it to that.
Here is the output from `whatDependsOn` after I removed it:
```
sbt:Equella> whatDependsOn org.apache.poi poi-ooxml
[info] org.apache.poi:poi-ooxml:4.1.2
[info]   +-org.apache.tika:tika-parser-microsoft-module:2.2.1
[info]     +-org.apache.tika:tika-parsers-standard-package:2.2.1
[info]       +-com.github.equella:conversion_2.12:702b5b5601dfdd347a0e6948ce92a075a0de0a9d [S]
[info]       
```
Resolves #3326
> chore(deps): remove unused apache poi-ooxml

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- docker/learningedge-log4j.properties
Main task here was to try and get us to an up to date and known base image - we pinned it a few years back to avoid an issue, but since then have been unsure how to accept renovate pull requests to update. To update the image we also needed to address the deprecation and removal of libav-tools from debian based distros (and this base image is debian).
While doing that I also reviewed and revised some of the docker and simplified the expected filename for the installer.
Undertook manual smoke testing locally, and looks to still function the same (including video previews to ensure I'd done the symbolic links correctly for ffmpeg -> libav).
(I did have an issue getting the Zookeeper part of the docker-compose working even before the upgrade - so at some point we need to loop back around and …
> build(docker): Upgrade base image to openjdk 8u312-jre

- react-front-end/tsrc/api/errors.ts
- react-front-end/tsrc/legacycontent/LegacyContent.tsx
- react-front-end/tsrc/mainui/ErrorPage.tsx
- react-front-end/tsrc/mainui/IndexPage.tsx
This is a draft PR to address #2873
There are two cases in old UI if there is a missing file:
https://user-images.githubusercontent.com/92769668/149067406-a5ddd62c-233c-4531-ae5d-4dbfee38e529.mp4
An index in the catalogue points to a missing file:
An internal link in IMS viewer points to a missing file:
But in New UI both cases will display the menu:
In old UI it actually uses param `temp.hn=true` to hide the menu (`RenderTemplate.java:394`).
And 404 page will directly return after the request `IntroToDBS_summary.html?temp.hn=true&temp.hb=true`.
But in new UI, `IntroToDBS_summary.html?temp.hn=true&temp.hb=true` will only return 404 code with some useless HTML content, and trigger a new request to the `LeagcyContent content/submit API`. 
If the URL points to a normal Legacy content, the …
> fix: hide menu bar for error page in IMS viewer

- .github/workflows/ci.yaml
Now that 9.6 is no longer supported, version 10 is the oldest supported
version (until November this year - see
https://www.postgresql.org/support/versioning/ for more info).
> build(gha): upgrade GHA CI to postgres 10

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/item/service/AttachmentService.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/AttachmentHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/AttachmentResourceService.scala
#3769 
We have added a fix (#3563)for the bug caused by a custom attachment which points to the latest version of another resource. 
However, that fix only works when the linked resource is an Item. When the resource is an Attachment, the issue can still happen such as when checking the MIME type of the linked attachment. (#3769)
So this PR adds some improvements to make sure whenever a linked resource is used in search2 API, the genuine latest version is used. 
During implementation, I realised that `SearchHelper` has been getting bigger and bigger. So I move some functions to the Scala version `AttachmentResourceService` and some to `AttachmentHelper`.
> bugfix: ensure Custom Attachment uses the correct latest version

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/FacetedSearch/FacetedSearchClassificationResource.scala
FacetedSearchClassification will generate its own id for creating operations.
Therefore the change is to make sure the response id is correct. 
> fix(api): ensure batchUpdate return correct id in response

- import-export-tool/build.gradle
I missed the Log4j in `import-export-tool` as this module was somehow unloaded in my dev env. So open this PR 
to update the Log4j.
After the update, warns from `SLF4J` disappear.
> chore: update Log4J to v2.17.1 in 'import-export-tool'

- Source/Plugins/Core/com.equella.core/src/com/tle/core/externaltools/service/impl/ExternalToolsServiceImpl.java
New Search UI is broken when an Item has an LTI attachment. This is because the LTI custom params are null 
and calling `customParams.size()` results in NPE. 
So we should properly check if the custom params are provided or not by calling `!Check.isEmpty`.
> fix: don't convert LTI custom parameters to string if no parameters provided 

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
Before 2020.2, the value of 'available' in a PagedResult is the full number of available
entities, which is actually not correct because ACL is not taken into account. We fixed
this in 2020.2. However, we found the fix can cause significant performance issue due to
filtering entities by ACL. So we decided to revert the fix and use the full number of
available entities again.
> refactor: don't filter entities by ACL in `PagedResults`

- Installer/data/server/learningedge-config/hibernate.properties.sqlserver
- Installer/resources/script/app-script.xml
- Installer/src/com/dytech/edge/installer/DatasourceConfig.java
- Installer/src/com/dytech/edge/installer/application/DatabaseConnectCallback.java
- Installer/src/com/dytech/edge/installer/application/FinishedCallback.java
- Installer/src/com/dytech/installer/WizardPage.java
- Installer/src/com/dytech/installer/controls/GuiControl.java
- Installer/src/com/dytech/installer/controls/MsSqlTrustServerCertsSelector.java
- project/CommonSettings.scala
oEQ was using a very old version of the MS SQL JDBC Driver which had dependencies on an old version of Jackson (1.9.x) which has recorded security vulnerabilities. So it was high time to upgrade to the latest.
However, it turned out that in the [latest mssql-jdbc](https://github.com/microsoft/mssql-jdbc/releases/tag/v10.2.0) they'd also addressed a [bug where server certificates were not being fully validated](https://github.com/microsoft/mssql-jdbc/pull/1731). By default though, SQL Server installs with a self-signed certificate which will fail this validation.
To support these cases, you can set the new flag `trustServerCertificate` to `true` in JDBC URLs.
In the oEQ installer though we test the JDBC configuration, so if that was not set then the test would fail and you would not be …
> Upgrade MS SQL Server JDBC Driver

- Installer/plugin-jpf.xml
- Source/Tools/UpgradeInstallation/plugin-jpf.xml
- Source/Tools/UpgradeManager/plugin-jpf.xml
- project/JPFScanPlugin.scala
Previous Log4J update work has caused a sbt error about not being able to to find plugin `TLE Upgrade Manager`. 
This is because the project of `TLE Upgrade Manager` is the dependency of project `UpgradeInstallation`. 
So we just need to add `TLE Upgrade Manager` to the JPF plugin scan list. However, `TLE Upgrade Manager` is not a valid name so I also renamed the plugin to `UpgradeManager`.
> fix: add 'UpgradeManager' to jpf scan list

- .github/workflows/ci.yaml
- autotest/IntegTester/ps/package-lock.json
Since merging #3814 we've been having GHA build issues. This should address them.
It's unclear how this really got into the lock file in this fashion, however without builds fail in pristine environments (like openjdk
docker containers and GHA) - but still work on CodeBuild for some (ominous) reason.
I did go down the path of installing the ansi-regex package explicitly (no at v6.0.1) and that worked. However, without understanding the tangled web of why this is there, I thought best to simply revert what we needed from #3814 and get things working again.
Also noted (as a red-herring) there is a slight bug in the GHA YAML specification meaning we're not using the version of Node/NPM for the functional tests - just what ever the default is.
(I did test the build of the …
> chore(deps): partial revert of ansi-regex PR #3814

- Source/Server/equellaserver/build.sbt
It seems the dependencies of `jboss-logging` are not used anywhere so we can drop these deps.
I tested locally to make sure logs are still correctly generated. Now let's wait for CI.
> refactor: drop dependency 'jboss-logging'

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
This param (customLuceneQuery) was added for the initial implementation of Advanced Searches. However later a different approach was used and this must have been left behind.
(I've done this edit straight into GitHub, so definitely need green builds. Locally though, I do search for usages and found _none_.)
> chore(cruft): remove unused property of SearchParam

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/item/service/AttachmentService.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/AttachmentHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
Profiling revealed a lot of time was spent in search2 requests in `ifNotBroken` due to both uses calling off to retrieve the same
attachment. Significant performance (both speed and DB calls) improvements were possible if instead we re-use the attachment we retrieve when we first check for broken attachment status rather than throwing it away.
Existing tests provide coverage for this, and I also undertook manual testing.
(While doing this, I noticed that for broken attachments the New UI was showing _no_description - just the exclamation mark. This was due to the change to show the Kaltura description. As a result, I rejigged that a little too - and so now broken attachments are more likely to show a description.)
[commit …
> refactor(search2): optimise number of attachment retrievals

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
This adds a new param to the search2 endpoint that allows for attachments to be excluded from the result. Doing so can skip the (sometimes) intensive processing required for attachments and thereby speed up responses.
The intention is to use this in the front-end to exclude attachments on search, but then if a user expands the attachments for an item to use the same endpoint but with a `must` of the item `uuid`. To ensure this can be done and still have the UI display how many attachments an item have there is also a new field in the response called `attachmentCount`.
> feat(REST): new includeAttachments param for search2 API

- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/Search.test.ts
- react-front-end/__mocks__/GallerySearchModule.mock.ts
- react-front-end/__mocks__/searchresult_mock_data.ts
- react-front-end/__tests__/tsrc/modules/GallerySearchModule.test.ts
Short and simple, this updates the REST Module (oeq-ts-rest-api) to match the back-end changes for `includeAttachments` and `attachmentCount`.
> feat(rest-module): add support for includeAttachments param of search2

- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
After Hibernate was updated to version 5, adding a new database schema from the Institution Manager no longer works. 
According to my investigation, this is because Hibernate no longer has the entity bindings for 'SchemaId' and 'MigrationLog' after `TransactionModule` is configured. As a result, the SQL of creating the two tables are just empty strings, which fail the whole process of adding a new database. 
The fix is to add the two entities in the `plugin-jpf.xml` as plugins of `com.tle.core.hibernate`. This will make sure Hibernate has the bindings and the SQL of creating the two tables are correct.
Please grab to chat if it's hard to understand above description.
> fix: make sure 'SchemaId' and 'MigrationLog' are added in Hibernate entity binding map

- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/AttachmentHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
- Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/item/impl/ItemLinkServiceImpl.java
- autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
To assist with the display of suitable thumbnails (especially if `includeAttachments` is `false`) a new property has been added to the search2 response.
Included a slight refactor to push some code into `AttachmentHelper` for reuse.
> feat(rest): add thumbnailDetails to search2 response

- oeq-ts-rest-api/package.json
- oeq-ts-rest-api/src/Search.ts
- oeq-ts-rest-api/test/Search.test.ts
Adds support for the new `thumbnailDetails` field introduced in #3916 .
> feat(rest-module): add support for thumbnailDetails

- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
- Source/Plugins/Core/com.equella.core/src/com/tle/core/system/migration/InitialMigration.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/ExtendedAnnotationConfiguration.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
- Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/migration/impl/HibernateMigrationService.java
The previous fix does not completely fix the issue. After a new database is added and initialised, adding more databases will result in the error about missing table `sys_schema_id` again.
The reason is initialising the firstly added database will change the Hibernate entity bindings, so when the second new database is added, entity bindings for those system level tables are missing.
So I think the proper fix is to save the entity bindings for system tables so they are accessible when needed.
https://user-images.githubusercontent.com/47203811/157595259-86704a69-6bdd-4816-b028-1aa8f4ed764c.mp4
> fix: make sure multiple database schemas can be added

- Source/Plugins/Core/com.equella.core/src/com/tle/mypages/web/attachments/MyPagesSummariser.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/stream/WrappedContentStream.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/ItemFilestoreServlet.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/RootItemFileSection.java
The audit logs for webpage attachments were missing because cache of the webpage
was used and no requests were sent to server. So we need to update the cache control
for webpage attachment so that a request is sent to check whether the cache is still
valid and this request will also trigger an audit log.
I also noticed the audit log event type for webpage viewing is wrong. It should be `CONTENT_VIEWED` rather than `SUMMARY_VIEWED`. So I added a fix for this as well.
> fix: ensure each view of a webpage has an audit log

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Before fix:
After fix: 
Also, I didn't see the search bar is changed.
> fix: align prompt input position with real input

- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/SearchResourceImpl.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/SearchApiTest.java
Change query param status type from string to CsvList.
> fix: handle multiple status for api search

- Source/Plugins/Core/com.equella.core/src/com/tle/web/core/filter/TokenUserStateHook.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/login/LogonSection.java
- autotest/OldTests/src/test/java/com/tle/webtests/test/users/TokenLoginTest.java
In New UI, if a user logins with an invalid shared secret or with one that the user does not have permission to use, the token error is not showed in the Login page. 
The reason is `TokenUserStateHook` fails to keep the token error in New UI. In Old UI, the error is saved in the attribute of the login request which is a GET request, but when New UI is turned on, the GET request only returns the page which triggers another POST request to get the page content. Obviously, the POST request does not know anything about the token error. 
If above sounds confusing please grab me to explain in more detail. 
I have tried different approaches to fix the issue, and in the end I chose the one in this PR which I believe is the safest fix and have least impacts on others. It's to save the token error …
> fix: make sure Login page shows the captured token error

- Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/guice/ViewItemModule.java
Since 2022.1, if the audit level is null it will break thumbnails. So we use 'NONE' as the default value.
> fix: ensure audit level has a non-null default value

- Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/brightspace/editor/BrightspaceConnectorEditor.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/dialog/LMSAuthDialog.java
Force return old UI to resolve the 500 error.
Provide a custom close function to close the Dialog in the new UI.
This PR fixes two problems.
The first one is that the LMS auth dialog in the new UI will trigger a 500 error. This 500 error happens after the finishedAuth event is triggered. Since the cause of this error is difficult to trace, we force the new UI to be closed in finishedAuth Event.
The second problem was that after fixing the 500 error, the LMS auth dialog didn't close properly in the new UI. In fact, it didn't close properly even in the old UI (it disappeared because the whole brightspace connector page was redirected). The reason is the returned script `$.fancybox.close` is in the iframe, and it does not have a `self.parent` prefix or context, so this script won't close the …
> fix: brightspace connector 500 error and automatically close dialog

- Source/Plugins/Core/com.equella.base/src/com/tle/web/api/item/interfaces/ItemResource.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
Update annotations for api `search`.
Including status and info params.
Before:
After:
> fix: update swagger ui annotations for info and status params

- Source/Plugins/Core/com.equella.base/src/com/tle/beans/viewcount/AbstractViewcount.java
- Source/Plugins/Core/com.equella.core/plugin-jpf.xml
- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
- Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20221/RenameViewCount.java
The two View Count tables have columns named `count` which is a reserved word in Oracle. So we need to escape the reserved word.
> fix: escape the reserved word 'count' for Oracle

- Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
- Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
- Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/manage/ConnectorManagementResultsSection.java
Change func `findAllUsages` to throw UnsupportedOperationException.
Add catch statement to set error message.
> fix: blackboard 500 error from manage external resources

- react-front-end/package.json
Since we have updated Scala to 2.13, the output of `npm run dev` should be saved in `com.equella.core/target/scala-2.13/classes` now.
> chore: update the output directory of `npm run dev`

- react-front-end/tsrc/mainui/MainMenu.tsx
Add missing `target` attribute to menu link.
> fix: add missing target attribute to menu link

- Source/Plugins/Core/com.equella.core/resources/web/js/versioncheck.js
- Source/Plugins/Core/com.equella.core/test/javascript/__mocks__/versioncheck_mock_data.js
- Source/Plugins/Core/com.equella.core/test/javascript/versioncheck.test.ts
Rework versioncheck.js to consume new versions.json from openequella.github.io.
> refactor: use versions.json determine latest version

- Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
Add missing collection query in breadcrumb and "Collection" button in right menu in summary page.
Before:
https://user-images.githubusercontent.com/92769668/171098413-ce5bea8b-b74a-4758-b38b-779ecd0a5eaa.mp4
Now:
https://user-images.githubusercontent.com/92769668/171099165-adb5cee2-62a9-4238-a6d1-fb8d4cf2db2b.mp4
> fix: add missing collection query in breadcrumb

- Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Import missing `portal.css` in `legacy.css`.
Before:
https://user-images.githubusercontent.com/24543345/112783026-1369db80-909a-11eb-94db-f4a5bcfc7477.mp4
Now:
https://user-images.githubusercontent.com/92769668/172736421-0c3bc071-1d40-4849-af23-09821b2b474a.mp4
> fix: portlet display in new UI

- project/plugins.sbt
It would appear this is not actually required, as the build appears to
work fine without it. However keeping it there, we're blocked from
upgrading to axis 1.8+ as there is no version of this in that release -
release notes say they renamed it, but they don't say what to. (Well,
they do but there seems to be a typo as they say it is renamed to the
same name.)
Will help #4217 
> chore(deps): remove unused plugin dep axis2-jaxbri

- build.sbt
resolves #4299 (this didn't work in the renovate branch as it required the build.sbt file to be re-linted).
Updates the com.oracle.database.jdbc ojdbc8 from 19.3.0.0 to 19.16.0.0.
I can confirm the new driver works, I tested it with Oracle Database 19c. 
> Update the com.oracle.database.jdbc ojdbc8 from 19.3.0.0 to 19.16.0.0.

- .github/workflows/ci.yaml
`set-output` is deprecated so we need to update GHA build configuration to use the new approach.
> chore: remove the deprecated use of 'set-output' in GHA build config

- oeq-ts-rest-api/package.json
- react-front-end/package.json
Pin Node and NPM versions so that Renovate will use the correct versions to build.
The pinned Node version matches to the one specified in `.nvmrc`.
> chore: pin node version and npm version

- autotest/Tests/src/test/scala/equellatests/sections/wizard/UniversalControl.scala
In `UniversalControl`,  the exception is raised from `ExpectedConditions.stalenessOf(row)`. 
And the error message says it can't find the node with the given id.
Consider we updated the web driver and the above code will remove the `row` element from dom,
so I think it's possible the element is already been moved before we do `ExpectedConditions.stalenessOf(row)`.
Thus I add a new function to check if the element is still there before calling `ExpectedConditions.stalenessOf(row)`.
> fix: ScalaCheck tests

- autotest/Tests/src/main/java/com/tle/webtests/pageobject/ExpectedConditions2.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/searching/AbstractResultList.java
Same issue with [!4700](https://github.com/openequella/openEQUELLA/pull/4700). The element has been removed before we monitor it.
> fix(selenium test): check the element before stalenessOf

- Source/Plugins/RemoteRepositories/com.equella.z3950/build.sbt
- autotest/Tests/build.sbt
To fix #4719.
Add new dep serializer.
Found this solution from https://stackoverflow.com/questions/76555759/java-lang-classnotfoundexception-org-apache-xml-serializer-outputpropertiesfact.
But the release note didn't mention it, except this sentence is related to serializer: 
https://xalan.apache.org/xalan-j/index.html#current
> fix: xalan xalan 2.7.3

- autotest/IntegTester/ps/package-lock.json
- autotest/IntegTester/ps/package.json
- autotest/IntegTester/ps/tsconfig.json
- oeq-ts-rest-api/gen-io-ts/package-lock.json
- oeq-ts-rest-api/gen-io-ts/package.json
- oeq-ts-rest-api/package-lock.json
- oeq-ts-rest-api/package.json
- package-lock.json
- package.json
- react-front-end/package-lock.json
- react-front-end/package.json
- react-front-end/tsrc/mainui/Template.tsx
To fix #4870.
But note it has a warning:
```
npm run check:ts
> check:ts
> eslint ${npm_package_config_typescript_glob}
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0
YOUR TYPESCRIPT VERSION: 5.2.2
Please only submit bug reports when using the officially supported version.
=============
```
> chore(deps): update dependency typescript to v5

- autotest/Tests/src/test/scala/equellatests/pages/LoginNoticePage.scala
- oeq-ts-rest-api/src/Errors.ts
- react-front-end/package-lock.json
- react-front-end/package.json
To fix #4839.
Looks like TinyMCE changed the encode for trailing space from `&nbsp` to `&#xFEFF`, so I just removed the last space form the text.
> chore(deps): update dependency tinymce to v6.7.0

- react-front-end/__tests__/tsrc/components/aclexpressionbuilder/ACLExpressionBuilder.test.tsx
- react-front-end/__tests__/tsrc/components/aclexpressionbuilder/ACLExpressionBuilderTestHelper.tsx
- react-front-end/__tests__/tsrc/components/securityentitydialog/SelectGroupDialog.test.tsx
- react-front-end/__tests__/tsrc/components/securityentitydialog/SelectRoleDialog.test.tsx
- react-front-end/__tests__/tsrc/settings/integrations/lti13platforms/CreateLti13Platform.test.ts
- react-front-end/__tests__/tsrc/settings/integrations/lti13platforms/CreateLti13PlatformTestHelper.tsx
- [x  the [contributor license agreement][] is signed
The Jest test case of LTI Platform creation was too big and GHA builds failed on it due to timeout very frequently. As a result, I split the test case into 5 smaller cases and reduced the timeout for each to 20 seconds. The overall time taken by this test suite increases, but it should be a lot more stable...so I think it's worth.
> test: address Jest test timeout issues

- .github/workflows/ci.yaml
With the move to Java 21 building (and running) we need to update the GitHub CI setup as well.
Included in this is to stop building the import-export tool, as that's not supported. See  import-export-tool/README.md.
> ci(github): bump java to 21

- autotest/OldTests/src/test/java/io/github/openequella/pages/advancedsearch/NewAdvancedSearchPage.java
I think the issue is when you input query in the user selector dialog, the result won't be rendered in the dom immediately, which causes the `findElement` to fail. 
> OEQ-1811 - fix(selectUser test): remove findElement

- autotest/OldTests/src/test/java/com/tle/webtests/test/dashboard/PortalsTest.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/portal/RecentContributionsSection.java
I think this is flaky because when a user contributes an item, even though the front end returns a success message, the back end has not yet saved the data properly.
Therefore, the solution is to use a custom waiter to continuously load the page to determine whether the item has been successfully created.
> fix: testRecentPortal

- autotest/Tests/src/main/java/com/tle/webtests/pageobject/oauth/OAuthClientEditorPage.java
- I've added a condition on OAuthClientEditorTest to check WebElement get attribute by id not empty based on the below condition of this test.
- The issue by when we send the empty string into the find element of Selenium Webdriver it will show an error when we send the empty string. But in the latest Chrome maybe Selenium Webdriver doesn't support the latest version.
> fix: OAuthClientEditorTest fails with latest Chrome

- .github/workflows/ci.yaml
A recent upgrade of ubuntu-latest to Ubuntu 24 (https://github.com/actions/runner-images/issues/10636) caused a lot of issues in the community (due to missing tooling etc) and we also saw an increase in failures of a new type. As a result, just like we pin our other dependencies we should really do the same here.
Hopefully renovate will also manage it for us.
> build(ci): pin ubuntu-22.04

- autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/controls/attachments/FileAttachmentControlTest.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/AbstractPage.java
- autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/controls/UniversalControl.java
According to the log, click of the Edit button is intercepted.
Pretty sure the button is clickable, but the error still happened, so I use JS to click the button.
> fix: FileAttachmentControlTest specialCharacters test

- autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/controls/AutoCompleteTermResults.java
I believe the flakyness in this test is due to Selenium not being able to click the right element in smaller browser window. So the potential fix is to use JS to do the click.
> Fix TaxonomyControlsTest

- autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/controls/UniversalControl.java
According to the log, click of the Add Resource button is intercepted by the ul above the button. Both are parts of the Attachment control which is a React component but used in the Legacty UI.
I guess  when the button is visible and the test is about to click it, the list is not yet. However, when the click happens, the list becomes visible and is displayed in where the button was (and the button is moved down to below the list).
So the first potential fix is to add a wait of element being clickable to the button.
> Fix SearchResultTemplateTest
