sbt

added using instructions from https://github.com/paulp/sbt-extras

Adds sbt wrapper for simpler installation experience

---

Dev/learningedge-config/build.sbt
Installer/build.sbt
Source/Server/equellaserver/build.sbt

Hi @doolse , can you review and merge please?

#89 switched the settings logger to a streams logger

---

Source/Plugins/LTI/com.tle.common.externaltools/src/com/tle/common/externaltools/constants/ExternalToolConstants.java
Source/Plugins/LTI/com.tle.web.externaltools/src/com/tle/web/externaltools/viewer/ExternalToolViewerSection.java
Source/Plugins/Server/com.tle.core.services/src/com/tle/core/services/guice/CoreServicesModule.java
Source/Plugins/Server/com.tle.web.institution/resources/lang/i18n.properties
Source/Plugins/Server/com.tle.web.institution/resources/view/tab/license.ftl

@doolse - please merge these changes for #71.  I confirmed the email configuration is being pulled from optional-config.  The other changes were just text changes.

#71 changes to remove hard coded legacy support emails

---

Source/Plugins/Server/com.tle.web.viewitem.treeviewer/resources/web/scripts/treenav.js

calculate the max height to take into account the nav buttons and the logo:

#270 tree viewer height fix

---

README.md

Brought over setup guide from docs repo.

Moved dev setup guide to readme

---

Source/Plugins/Items/com.tle.common.item/src/com/tle/beans/item/ItemSelect.java
Source/Plugins/Server/com.tle.web.endpoint.srw/plugin-jpf.xml
Source/Plugins/Server/com.tle.web.endpoint.srw/src/com/tle/web/endpoint/srw/EquellaSRWDatabase.java
Source/Plugins/Server/com.tle.web.endpoint.srw/src/com/tle/web/endpoint/srw/SRWServletExt.java
Source/Plugins/Server/com.tle.web.endpoint.srw/src/com/tle/web/endpoint/srw/guice/SRWEndpointModule.java

@doolse , I know you removed the static injection, but I don't see any other way to get it to work?

#384 static inject again

---

Source/Plugins/Generic/com.tle.common.reporting/src/com/tle/beans/entity/report/Report.java
Source/Plugins/Items/com.tle.common.item/src/com/tle/beans/item/attachments/Attachment.java
Source/Plugins/Server/com.tle.core.freetext/src/com/tle/freetext/TextExtracter.java
Source/Plugins/Server/com.tle.core.reporting/src/com/tle/core/reporting/ReportingServiceImpl.java

Issue #407 
Provides more detailed logging around attachment indexing and what reports are run.
Request to be merged into master.  Not sure if it's appropriate to be cherry-picked into 65stable...

Issue 407:  Added logging for indexing and reporting

---

sbt

Includes latest changes from upstream https://github.com/paulp/sbt-extras/blob/715a3a8ba9bf16796eee0b034143acb4594c1d2d/sbt

build(sbt): update sbt wrapper to latest version

---

.gitignore
Source/Plugins/Core/com.equella.base/src/com/tle/common/security/PrivilegeTree.java
Source/Plugins/Core/com.equella.core/resources/com/tle/core/i18n/service/impl/i18n-admin-console.properties
Source/Plugins/Core/com.equella.reporting/plugin-jpf.xml
Source/Plugins/Core/com.equella.reporting/resources/lang/i18n-resource-centre.properties
Source/Plugins/Core/com.equella.reporting/src/com/tle/core/reporting/ReportingService.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/core/reporting/ReportingServiceImpl.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportBean.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportBeanSerializer.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportEditor.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportEditorFactory.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportEditorImpl.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportException.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportResource.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/web/api/report/ReportResourceImpl.java

For enhancement:  https://github.com/equella/Equella/issues/436
/api/report endpoint enabled.   Supports report 'locking', create, edit, view, and delete.

Issue/436 - Create Report REST API endpoint

---

.travis.yml
Source/Plugins/Core/com.equella.core/build.sbt
Source/Plugins/Core/com.equella.core/plugin-jpf.xml
Source/Plugins/Core/com.equella.core/src/com/tle/core/userscript/scriptobject/UserScriptObjectImpl.java
build.sbt
buildspec.yml
project/CommonSettings.scala

FYI @edalex-ian - EQUELLA used to have a downloads page as part of the server admin which contained documentation downloads but it was removed when it went open source

#555 Create a scripting api javadoc zip

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Based off suggestions from contributing guide
See: https://help.github.com/articles/about-issue-and-pull-request-templates/

docs: issue template for reporting issues and requesting features

---

Source/Plugins/Core/com.equella.core/resources/web/css/actions/sort.css
Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
Source/Plugins/Core/com.equella.core/resources/web/js/whereclause.js

Selects are 100% width by default.  Fixed reload method of dropdown in "where" editor screen.

#606, #608 fix dropdown related issues

---

Source/Plugins/Core/com.equella.core/js/src/MainUI/Template.purs
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/customlinks/menu/CustomLinksMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/section/MenuContributor.java

Add icon and newWindow field, ensure externals urls come through

---

Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx

UI settings visual tweaks #653

---

Source/Plugins/Core/com.equella.base/src/com/tle/beans/entity/LanguageBundle.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/collection/service/impl/ItemDefinitionServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/dynacollection/impl/DynaCollectionServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/entity/service/impl/AbstractEntityServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/indexer/AbstractIndexingExtension.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/indexer/StandardIndexer.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/item/service/impl/ItemServiceImpl.java

#612 Init the name bundle properly

---

Source/Plugins/Core/com.equella.base/src/com/tle/common/search/DefaultSearch.java
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/searches/SearchDefaults.scala

Bullets logo sorting

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/activation/viewitem/summary/section/EditActivationSection.java

Fix active CAL activation editing

---

Source/Plugins/Core/com.equella.core/resources/view/fileupload.ftl
Source/Plugins/Core/com.equella.core/src/com/tle/web/htmleditor/tinymce/addon/tle/selection/FileUploadSection.java

Switch to new ajax uploads for tinymce 

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/equella/render/EquellaDropdownExtension.java

Re-enable old <select>s for accessibility mode

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala

Make sure body tag is used

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/externaltools/LtiHandler.java

Put the default name in the LTI attachment at create time

---

Source/Plugins/Core/com.equella.core/js/src/MainUI/Template.purs
Source/Plugins/Core/com.equella.core/js/src/SelectionUI/Main.purs
Source/Plugins/Core/com.equella.core/js/src/UI/MessageInfo.purs
Source/Plugins/Core/com.equella.core/js/tsrc/api/errors.ts
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/LoginNoticeResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/impl/LoginNoticeResourceImpl.java

Add delete functionality, as well as feedback snackbars for the creation and deletion methods.
#660

Login HTML Notice: delete notice

---

Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
Source/Plugins/Core/com.equella.core/resources/view/logon/logon.ftl
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/login/LogonSection.java

Login Screen Notice: view plaintext notice

---

README.md

So as to highlight to any newcomers of the repository that what they're
looking at is the unstable branch. And if they want stable, then where
to get it.

Note difference between master and develop in README.md

---

Source/Plugins/Core/com.equella.core/js/.editorconfig
Source/Plugins/Core/com.equella.core/js/src/MainUI/Main.purs
Source/Plugins/Core/com.equella.core/js/src/MainUI/Routes.purs
Source/Plugins/Core/com.equella.core/js/src/TSComponents.js
Source/Plugins/Core/com.equella.core/js/src/TSComponents.purs
Source/Plugins/Core/com.equella.core/js/tsrc/api/General.ts
Source/Plugins/Core/com.equella.core/js/tsrc/api/bridge.ts
Source/Plugins/Core/com.equella.core/js/tsrc/components/EntityList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/course/SearchCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/searchconfig/ListSearchConfigs.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/searchconfig/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/settings/SettingsDB.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/ApiHelper.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/searches/SearchConfigApi.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/searches/SearchConfigDB.scala
Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/DBQueries.scala
Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/DBSchema.scala
Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/package.scala
Source/Server/equellaserver/build.sbt

Listing of search configurations using EntityList react component

---

Source/Plugins/Core/com.equella.admin/src/com/tle/admin/controls/universal/UniversalControlModel.java

#747 
This bug was caused due to using the wrong key.

Restore attachment save confirmation messages

---

Source/Plugins/Core/com.equella.core/src/com/tle/core/item/edit/impl/ItemEditorServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/viewitem/actions/NewVersionSection.java

* using CoreStrings to read language strings
* renaming variables to avoid confusion.

Optimize the REST API and UI of creating new versions (#718)

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala

The OEQEntity JSON for cloud providers

Cloud provider storage

---

Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PostLoginNoticeConfigurator.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
autotest/Tests/src/test/scala/equellatests/browserpage/CommonXPath.scala
autotest/Tests/src/test/scala/equellatests/pages/LoginNoticePage.scala
autotest/Tests/src/test/scala/equellatests/pages/LoginPage.scala
autotest/Tests/src/test/scala/equellatests/tests/LoginNoticeMenuPropertiesSerial.scala

Update login notice autotests for rich text

---

Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/LoginNoticeService.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/PreLoginNoticeResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/impl/PreLoginNoticeResourceImpl.java
autotest/Tests/src/test/scala/equellatests/pages/LoginNoticePage.scala

Login Notice: add image uploading to rich text editor.

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/SearchQuerySection.java

766 make submitWizard not stateful

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/package.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/cloudprovider/CloudProviderApi.scala
Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java

Add provider API using a replicate cache to store registration tokens. Depends on #774

Provide a registration API

---

Source/Plugins/Core/com.equella.core/js/src/Bridge.purs
Source/Plugins/Core/com.equella.core/js/src/MainUI/Main.purs
Source/Plugins/Core/com.equella.core/js/src/MainUI/Routes.purs
Source/Plugins/Core/com.equella.core/js/src/TSComponents.js
Source/Plugins/Core/com.equella.core/js/src/TSComponents.purs
Source/Plugins/Core/com.equella.core/js/tsrc/api/routes.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderListPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/NewCloudProvider.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/util/commonstrings.ts

Add a page for registering cloud providers

Add a page to register cloud providers

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/command/EditInWizard.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/command/SaveAndContinue.java

This PR fixes another case where the mandatory field bug happens.
"When save and continue is clicked the user can save and publish without completing the mandatory field on page 2"

Fix another case where mandatory field bug occurs (#749)

---

Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/LoginNoticeService.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/PreLoginNoticeResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/impl/PreLoginNoticeResourceImpl.java

#660 
Uploaded images were getting converted to PNG. Now, they retain their original file type.

Login Notice: Preserve content of image files on upload

---

Source/Plugins/Core/com.equella.base/src/com/tle/common/scripting/types/AttachmentScriptType.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/scripting/types/AttachmentScriptTypeImpl.java

#786 add scripting methods to handle longs and doubles

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/lti/usermanagement/LtiWrapper.java

#588 re-use the same ID

---

Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
Source/Plugins/Core/com.equella.core/src/com/tle/web/oauth/service/OAuthWebServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/oauth/servlet/AbstractOAuthServlet.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/oauth/servlet/OAuthTokenServlet.java

Fix oauth redirect param and language strings

---

Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx

Login Notice: Remove max_height parameter

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/PagesSection.java

Fix: Failing to publish new item with mandatory field filled

---

Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx

Login Notice: Compare date and time rather than just date

---

Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderAddDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderModule.ts

#757 
Validate the cloud provider registration URL.
After discussing with Charlie, the validation will only check if a URL starts with "http(s)://".

Validate the cloud provider registration URL

---

autotest/OldTests/src/test/java/com/tle/webtests/test/searching/SearchSettingsTest.java
autotest/Tests/src/main/java/com/tle/webtests/pageobject/searching/SearchPage.java

Fix SearchSettingsTest

---

Source/Plugins/Core/com.equella.core/plugin-jpf.xml
Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsList.scala
Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/loginnotice/impl/LoginNoticeServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/impl/PostLoginNoticeResourceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/loginnotice/impl/PreLoginNoticeResourceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/loginnotice/LoginNoticeEditorPrivilegeTreeProvider.java

Login Notice: Add ACL target in EDIT_SYSTEM_SETTINGS for Login Notice Editor

---

Source/Plugins/Core/com.equella.admin/src/com/tle/admin/controls/cloudcontrol/configcomponent/CheckboxConfig.java
Source/Plugins/Core/com.equella.admin/src/com/tle/admin/controls/cloudcontrol/configcomponent/DropdownConfig.java
Source/Plugins/Core/com.equella.admin/src/com/tle/admin/controls/cloudcontrol/configcomponent/RadiobuttonConfig.java
Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.js
Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.purs
Source/Plugins/Core/com.equella.core/resources/web/scripts/cloudcontrol.js
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderService.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/package.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/cloudproviders/CloudWizardControl.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/BrokenWebControl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardControlFactory.java
Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/validation/EntityValidation.scala
autotest/IntegTester/ps/package.json
autotest/IntegTester/ps/tsrc/cloud.tsx
autotest/IntegTester/ps/www/control.tsx
autotest/IntegTester/src/main/scala/integtester/IntegTester.scala
autotest/IntegTester/src/main/scala/integtester/testprovider/TestingCloudProvider.scala

* Also fixes to checkbox, dropdown & radio storage to use the supplied values

Cloud control wizard javascript bundle

---

Source/Plugins/Core/com.equella.admin/src/com/tle/admin/controls/UnavailableControlEditor.java
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardItemEditor.scala

Fixed a few files that didn't get caught in the repo-wide header change.

#868 updated headers

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/item/ItemEdits.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/item/ItemEditsExisting.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardItemEditor.scala
Source/Plugins/Core/com.equella.core/src/com/tle/core/item/edit/ItemEditor.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/item/edit/impl/ItemEditorImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/item/resource/EquellaItemResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/item/resource/impl/ItemResourceImpl.java

Abstract the ItemEdits for use with existing API

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudAttachmentResourceExtension.scala
Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
Source/Plugins/Core/com.equella.core/src/com/tle/mypages/web/attachments/MyPagesSummariser.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/copyright/section/ViewByRequestSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/mimetypes/section/FakeMimeTypeResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/ViewAttachmentSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/ViewDefaultSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/summary/attachment/service/ViewAttachmentWebServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/ViewAttachmentUrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/ViewItemService.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/ViewItemServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/ViewableResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/attachments/impl/AttachmentResourceServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/resource/AbstractWrappedResource.java

Show and use additional cloud attachment viewers

---

Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.js
Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.purs
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderAddDialog.tsx
Source/Plugins/Core/com.equella.core/resources/view/header.ftl
Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/react.ftl
Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java

Support New UI in IE11

---

Source/Plugins/Core/com.equella.core/js/src/IndexPage.js
Source/Plugins/Core/com.equella.core/resources/view/header.ftl
Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java

Fix New UI in 6.6 on IE11

---

Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.js
Source/Plugins/Core/com.equella.core/js/src/UI/LegacyContent.purs
Source/Plugins/Core/com.equella.core/resources/web/css/styles.css
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java

Fix New UI in 2018.2 on IE11

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudAttachmentEditor.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudAttachmentJson.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudAttachmentSerializer.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderService.scala
Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/indexer/StandardIndexer.java
Source/Plugins/Core/com.equella.core/src/com/tle/freetext/TextExtracter.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/api/item/equella/interfaces/beans/CloudAttachmentBean.java
autotest/IntegTester/ps/www/control.tsx
cloudprovidersdk/controls/index.d.ts

Index cloud attachments

---

renovate.json

https://renovatebot.com/docs/configuration-options/

Stop Renovate rebasing stale PRs

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala

IE11 caches GET requests which was causing the currentuser api to work incorrectly.

Add cache control to the currentuser API to prevent caching issues in IE11

---

import-export-tool/build.gradle

Fix the issue that these two tools cannot be built on Windows.

Fix the tools not working on Windows

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json
Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts

Prevents IE11 crash on contribution wizard when cloudcontrol is present.

Add IE11 xpath support

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/stream/ContentStreamWriter.java

* Add ETag to response headers
* Fix the bug that the server did not  properly handle downloading requests

Add ETag to response header

---

Source/Plugins/Core/com.equella.core/build.sbt
Source/Plugins/Core/com.equella.core/swaggerui/package.json
build.sbt

Also a new "cleanrun" task which cleans builds and runs the dev server
#943

#943 Clean npm projects from sbt clean

---

Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Source/Plugins/Core/com.equella.core/src/com/tle/web/favourites/AbstractRootFavouritesSection.java

Ajax callbacks are being called twice which is causing some ui glitches

Fix some ui glitches due to legacycontent re-write

---

Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/SectionInfo.java
Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/SectionWriter.java
Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/events/StandardRenderEventContext.java
Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/generic/DefaultSectionInfo.java
Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/generic/WrappedSectionInfo.java
Source/Plugins/Admin/com.tle.web.adminconsole/scalasrc/com/tle/core/adminconsole/AdminConsoleExtensions.scala
Source/Plugins/Core/com.equella.core/js/tsrc/api/errors.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/components/SearchResult.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/course/EditCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/course/SearchCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/searchconfig/ListSearchConfigs.tsx
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/SettingsResource.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/cloudproviders/CloudWizardControl.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/EditableSettings.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsPage.scala
Source/Plugins/Core/com.equella.core/src/com/tle/core/favourites/service/FavouriteSearchServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/render/WizardFreemarkerFactory.java

* Fix the adminconsole link in the new ui
* Make sure missing cloud control script fails gracefully (both if the script fails to load or the control isn't registered)
* Don't show "You have changes" when you save a new course
* Don't display (maybe outdated) content below error pages
* Make favourite searches work in new UI
* Fix previewing items in wizard from new UI
* Make sure non JSON errored requests show up as errors instead of blank pages

Lots of fixes

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json
Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
Source/Plugins/Core/com.equella.core/resources/web/scripts/submit.js
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/cloudproviders/CloudWizardControl.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardState.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/PagesSection.java
autotest/IntegTester/ps/package-lock.json
autotest/IntegTester/ps/package.json
autotest/IntegTester/ps/www/control.tsx

Cloud controls can now:
* Prevent you from navigating to the next page 
* Mark themselves as being required to be filled out
* Edit the xml metadata on page submission (navigation & saving)

Cloud control validator hook

---

Source/Plugins/Core/com.equella.core/js/tsrc/course/EditCourse.tsx

Please forgive the auto-formatting of the imports...

803 edit course unique individuals

---

Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContentRenderer.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx

The component hierarchy for the new UI means that certain interactions can cause momentary unmounting of the main content component which in turn can lead to duplicate requests to the server.

Fix New UI component hierarchy to prevent multiple requests

---

Source/Plugins/Core/com.equella.core/resources/view/itemadmin-query.ftl
Source/Plugins/Core/com.equella.core/resources/web/css/component/richdropdown.css
Source/Plugins/Core/com.equella.core/resources/web/js/ajaxhelper.js
Source/Plugins/Core/com.equella.core/resources/web/scripts/component/richdropdown.js

#628 Rich dropdown width fix

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/equella/utils/UserLinkSection.java

Impersonation label fix 

---

.travis.yml
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/standard/controls/TreeNavWebControl.java

Fix the Navigation builder in the new UI

---

renovate.json

resolves https://github.com/apereo/openEQUELLA/pull/1000#issuecomment-502536618

Reconfigure Renovate - group scala http packages together

---

Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/events/BookmarkEvent.java
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala
Source/Plugins/Core/com.equella.core/src/com/tle/web/activation/ActivationsMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/contribute/ContributeMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/customlinks/menu/CustomLinksMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/hierarchy/HierarchyMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/itemadmin/ItemAdminMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/settings/menu/SettingsMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/section/AbstractCachedMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/section/AbstractUpdatableMenuContributor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/section/MenuContributor.java
Source/Plugins/Core/com.equella.reporting/src/com/tle/core/reporting/web/ReportingMenuContributor.java

#1017 and a one liner which fixes some of the tests in #1008

Fix nav link updates on new UI

---

Installer/data/server/learningedge-config/optional-config.properties
Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/guice/FreetextModule.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/AbstractIndexEngine.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/ItemIndex.java
Source/Plugins/Core/com.equella.core/src/com/tle/freetext/FreetextIndex.java
Source/Plugins/Core/com.equella.core/src/com/tle/freetext/FreetextIndexImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/freetext/TLEAnalyzer.java

* Add a new property which enables users to specify what language stemming to use
* Add German stemming search if the value of above property is German

Add German stemming

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/flickr/FlickrHandler.java

Since this handler has it's own tree, there is a race condition for
removal of the tree between the Flickr control and InfoEventListener. So
a method was added that ensures it is added from the Flickr control.

Change the event that causes the Flickr search tree to be registered

---

Source/Plugins/Core/com.equella.core/resources/view/canvasconfig.ftl

See history in #586 and PR #661 .  Something went awry in rebasing off of `develop`, so I made a fresh branch / PR.

#586 added missing params for canvas lti

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/mypages/MyPagesHandler.java

Works in exact same way as recently fixed FlickrHandler bug.

Fix No Tree For ID issue with Web Pages in Universal Attachment Control

---

Source/Plugins/Core/com.equella.base/scalasrc/com/tle/beans/cloudproviders/CloudControlDefinition.scala
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderEntity.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderListPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/components/EquellaListItem.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/package.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/cloudprovider/CloudProviderApi.scala

Two commits:
* Make min and max optional for cloud control config options
* Ability to refresh cloud provider registration

Backwards compatible cloud provider enhancements

---

.travis.yml

We actually fixed this for Develop in PR #991, but did not cherry pick it to Release.

Make sure directory is correct

---

Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx

Use the URL in the form being submitted rather than the page URL

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/PagesSection.java

This bug happens in some cases when hitting Save button the XML of an item is still not available .

Fix saving uuid as item title

---

.idea/codeStyles/Project.xml
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx

Make sure the login page is working.

Fix blank logon page

---

.travis.yml

Make Travis do branch build only for master, develop, release and stable.

Change Travis branch build targets

---

Source/Plugins/Core/com.equella.core/resources/web/css/controls.css

In case anyone is wondering, the actual change is to add:
```
.wizard-controls select.listbox + .newListSelected,
.wizard-controls select.listbox + .newListSelected .newList {
box-sizing: border-box;
width: 100% !important;
}
```
Blame the rest on the formatter.

Force 100% width on wizard dropdown elements

---

Platform/Plugins/com.tle.platform.common/src/com/tle/common/URLUtils.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/RootItemFileSection.java

when the original request is already hiding them
#1198

Dirtiness to prevent navigation bars on error screen

---

Source/Plugins/Core/com.equella.core/resources/web/css/controls.css

Backporting #1200 (PR #1278) into 2018.2

#1200 manual backport of AJAX stylish select width fix

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/cloud/view/CloudViewItemAuditor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/cloud/view/section/RootCloudViewItemSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/ItemFilestoreServlet.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/ViewItemAuditor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/RootItemFileSection.java

When "smart" auditing is enabled
#861

Don't register a HEAD or OPTIONS request as a viewing

---

Installer/build.sbt
Source/Server/equellaserver/build.sbt
build.sbt
project/CommonSettings.scala

From 2019.2.0, ojdbc8 will be used.

Update Oracle Driver

---

Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/IAttachment.java
Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
Source/Plugins/Core/com.equella.core/src/com/tle/core/auditlog/AuditLogService.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/auditlog/impl/AuditLogServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/cloud/beans/converted/CloudAttachment.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/cloud/service/impl/CloudServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/cloud/search/CloudSearchListEntry.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/cloud/view/section/RootCloudViewItemSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/AbstractAttachmentViewItemResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/ViewItemAuditor.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/attachments/DetailUrlResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/attachments/LinkResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewitem/section/RootItemFileSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/ViewItemResource.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/viewurl/WrappedViewItemResource.java
autotest/OldTests/src/test/java/com/tle/webtests/test/viewing/ItemSummaryTest.java
autotest/Tests/src/main/java/com/tle/webtests/pageobject/viewitem/AttachmentsPage.java

Also show view count on link attachments that was never shown before
(but should have been)
Resolves: #1199

Log external link views as attachment views

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Source/Plugins/Core/com.equella.core/src/com/tle/web/template/RenderTemplate.java

sass code has been written to style the search page in a material-like way. the code is a mixture of existing legacy css and new sass code written by me 
For testing all functionality on the search page will need to be tested, to ensure everything has been styled in a pleasing way. I have been looking at it all for too long, so there are likely still issues that i haven't yet found/glossed over. Any feedback welcome

search page styling mega commit/monster

---

Platform/Plugins/com.tle.platform.common/src/com/dytech/common/io/FileUtils.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/services/impl/FileSystemServiceImpl.java

Part of the 'Attachment Health' effort.  This is a first pass at a better audit trail around deleting attachments.
Old PR - #1355

#1295 - Add detailed log around deleting attachments (round 2)

---

Source/Plugins/Core/com.equella.core/src/com/tle/tomcat/guice/TomcatModule.java
Source/Plugins/Core/com.equella.core/src/com/tle/tomcat/service/impl/TomcatServiceImpl.java

Enables the config `tomcat.internalProxies` (  #1360 )

Added tomcat config for internalProxies

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/controls/universal/UniversalWebControlNew.scala
Source/Plugins/Core/com.equella.core/src/com/tle/core/wizard/LERepository.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/wizard/controls/HTMLControl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/wizard/controls/HTMLCtrlWrapper.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/wizard/controls/WizardPage.java
Source/Plugins/Core/com.equella.core/src/com/tle/mypages/web/MyPagesRepository.java
Source/Plugins/Core/com.equella.core/src/com/tle/mypages/web/MyPagesState.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/universal/UniversalResourcesDialog.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/SimpleLERepository.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WebWizardPage.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardState.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/WizardStateInterface.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/AbstractHTMLControl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/CCustomControl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/CGroupCtrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/CMultiCtrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/CRepeater.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/EditableCtrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/GroupsCtrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/MultipleCtrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/controls/OptionCtrl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WebRepository.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/impl/WizardServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/PagesSection.java

Surprisingly this backport of several of Jolse's fixes into 2018.2 appears to work without any issues.  Will see what the build says.
#1093

Bugfix/1093 wizard sync backport 2018.2

---

Installer/build.sbt
Source/Server/equellaserver/build.sbt
build.sbt
project/CommonSettings.scala

Ensure the Oracle JDBC Driver is also included in the Installer.

Include Oracle JDBC Driver in the Installer

---

Source/Plugins/Core/com.equella.core/resources/view/results.ftl
Source/Plugins/Core/com.equella.core/src/com/tle/web/search/base/AbstractSearchResultsSection.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/SearchResultsSection.java

Add a new CSS class to the Search Result section for images and videos

Support new CSS classes in the Search Result section

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

Very basic styling of the image and video gallery search results. to keep things simple (time constraints) the ui is pretty much the same as it was in the old ui

basic video and image gallery styling

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

Includes the styling of Manage activations, manage external resources, and manage resources pages

Manage activations, tasks, external resource page styling

---

Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala

The  'editoradmin', 'apidocs' and 'reports' pages do not need 'legacy.css' so load CSS on Server side.

Exclude 'legacy.css' from a few pages

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

This PR will cover all remaining styling fixes that need to be performed in order to get the autotests passing

Remaining styling fixes

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

Selection session fixes

---

autotest/OldTests/src/test/java/com/tle/webtests/test/myresources/MyResourcesWebPageTest.java
autotest/Tests/src/main/java/com/tle/webtests/pageobject/myresources/MyResourcesPage.java

Fix my resources web page test

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Add rules to make the duplicate attachment section format properly

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Stop the save dialog from being unnecessarily long

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Fix broken modify key resources tree CSS

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Prettify login button

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/swaggerui/package-lock.json
Source/Plugins/Core/com.equella.core/swaggerui/package.json

Updated Swagger UI to the latest release ( 3.25.0 )
#1451

#1451 Update Swagger UI to 3.25.0

---

Source/Plugins/Core/com.equella.core/resources/view/flickrquery.ftl
Source/Plugins/Core/com.equella.core/resources/view/itemadmin-query.ftl
Source/Plugins/Core/com.equella.core/resources/view/manage-query.ftl
Source/Plugins/Core/com.equella.core/resources/view/managequery.ftl
Source/Plugins/Core/com.equella.core/resources/view/query.ftl

Adds the  role attribute was missing from the Within drop down.

Accessibility: Add listbox role to "Within" dropdown

---

project/CommonSettings.scala

Upgraded postgre JDBC from 42.1.4-jre7 to 42.2.9.  
Didn't look like any changes to the code logic was needed to move from JDBC 4.1 to 4.2.  The known issues in the change log didn't raise any serious flags since we use `timestamp`s instead of just the 24 hr time.
#1446

#1446 Upgrade Postgre JDBC to 42.2.9

---

Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/render/TagRenderer.java
Source/Plugins/Core/com.equella.core/resources/view/macro/receipt.ftl
Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/ajax/freemarker/AjaxCaptureDirective.java

#1432 This one turned out to be slightly more complicated than just adding the role attribute into the ftl, due to some freemarker marcro/ajax magic

jump through some hoops to get role attributes working on ajax elements

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderService.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardApi.scala

Don't copy host header for Cloud Provider requests.

Don't copy host from Headers for Cloud Provider requests

---

Source/Server/equellaserver/build.sbt

Issue #1466 
Upgraded tomcat to 8.5.50.  Doesn't look like any changes besides the version bump is needed.  
Interesting bugfix in 8.5.48 with SameSite cookies - https://bz.apache.org/bugzilla/show_bug.cgi?id=63865 .  FYI #1458 

#1466 Upgrade tomcat to 8.5.50

---

Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/components/SearchResult.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/course/EditCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/theme/ColorPickerComponent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/util/validation.ts

Typescript's `any` feature disables type checking for a variable, this change goes through areas that have been disabled and adds appropriate types.

refactor: add missing typings

---

Source/Plugins/Generic/org.hibernate/build.sbt
project/CommonSettings.scala

Fairly straight-forward version bump of xstream to 1.4.11.1

#1496 upgrade xstream to 1.4.11.1

---

autotest/OldTests/src/test/java/com/tle/webtests/test/contribute/UniquenessTest.java

The Uniqueness test has been failing frequently on Codebuild recently. So add this fix to make it more work more stably.

Make UniquenessTest more stable on Codebuild.

---

Source/Plugins/Core/com.equella.core/js/src/Common/Strings.purs
Source/Plugins/Core/com.equella.core/js/src/MainUI/SettingsPage.purs
Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsList.scala
autotest/Tests/src/main/java/com/tle/webtests/pageobject/SettingsPage.java

Add a new subcategory to the search page for searching settings. Update the SearchSettingsTest to work with it. 
#1337

Add new Search Setting category

---

Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContentRenderer.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyForm.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/ErrorPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/PreventNavigation.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/ScreenOptions.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/AdminDownloadDialog.tsx
autotest/IntegTester/ps/tsrc/cloud.tsx
autotest/IntegTester/ps/tsrc/viewitem.tsx

This is a pattern used through a majority of the code, bringing the few places that are different, over to the standard.

refactor: update prop types to use interfaces and destructuring

---

Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx

No related issue
This PR aims to fix the error caused by the merge from PR #1231.

Fix the Google tag error caused by the react prop types update

---

renovate.json

https://renovate.whitesourcesoftware.com/blog/introducing-renovates-master-issue

chore: setup Renovate dashboard issue feature

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/ApiErrorResponse.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/CloudSearchSettingsResource.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/SearchFilterResource.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/SearchSettingsResource.scala
Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
Source/Plugins/Core/com.equella.core/src/com/tle/web/remoting/resteasy/RestEasyServlet.java
autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/SearchSettingApiTest.java

#1337 
REST APIs for SearchFilter.

REST API for Search Filter

---

Source/Plugins/Core/com.equella.core/js/src/MainUI/Template.js
Source/Plugins/Core/com.equella.core/js/tsrc/api/errors.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/components/CourseSelect.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/course/EditCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/course/SearchCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
package-lock.json
package.json

This eslint config is provided by the react team with a set of recommendations to make react apps run smoothly.
https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app
These recommendations are non-stylistic, focusing on things like the rule of hooks.
https://reactjs.org/docs/hooks-rules.html
https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks
These rules do not overlap with, or interfere with, the existing prettier code style.

test: add eslint config create react app to checks

---

CONTRIBUTING.md
Dev/docs/clienterrors.md
Dev/docs/reactjs.md
Dev/docs/restendpoint.md
README.md
docker/README.md
package-lock.json
package.json

Uses https://github.com/remarkjs/remark with https://github.com/remarkjs/remark-validate-links and https://github.com/davidtheclark/remark-lint-no-dead-urls to check that links in documentation still point to real web pages and documentation headers.

test: validate links in markdown with remark

---

Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsList.scala

https://github.com/openequella/openEQUELLA/issues/1337

added new content indexing settings menu item

---

Source/Plugins/Core/com.equella.core/js/entrybuild/index.ts
Source/Plugins/Core/com.equella.core/js/entrybuild/selection.ts
Source/Plugins/Core/com.equella.core/js/entrydev/index.ts
Source/Plugins/Core/com.equella.core/js/entrydev/selection.ts
Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json
Source/Plugins/Core/com.equella.core/js/tsrc/__tests__/mainui/ErrorPage.test.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderAddDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderDisclaimerDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderListPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/AppBarQuery.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/CourseSelect.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/EntityList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/Error.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/MessageInfo.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SearchResult.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/course/EditCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/course/SearchCourse.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/installcss.ts
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContentRenderer.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/ErrorPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/ScreenOptions.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx

#1522 
Involved jumping through some hoops to get the breaking changes fixed.
NOTE: This breaks the course editor page, which is soon to be decommissioned.

Migrate Material UI to v4

---

Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/ErrorPage.test.tsx
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/actionutil.test.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/commonstrings.test.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/dictionary.test.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/encodequery.test.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/langstrings.test.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/util/validation.test.ts
Source/Plugins/Core/com.equella.core/js/tsconfig.json
package.json

js/__test__ and js/tsrc/__test__ have been merged into js/__test__
resolves folder comment from https://github.com/openequella/openEQUELLA/pull/1602#pullrequestreview-389729975

refactor: combine test folders

---

Source/Plugins/Core/com.equella.core/js/__stories__/components/AppBarQuery.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/ConfirmDialog.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/Error.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/Loader.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/MessageInfo.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/RichEditor.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchResults.stories.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/AppBarQuery.tsx

Refactors app bar query to functional component.
Moves story structure to match folder structure.
Adds story for app bar query.

refactor: app bar query to functional component

---

Source/Plugins/Core/com.equella.core/js/tsrc/components/ConfirmDialog.tsx

refactor: ConfirmDialog to pure component

---

.travis.yml
autotest/IntegTester/ps/tsconfig.json
autotest/IntegTester/ps/tsrc/cloud.tsx
autotest/IntegTester/ps/tsrc/viewitem.tsx
package.json

I found there was another tsconfig file in the project, this has now been added to the type checking, and the typescript/eslint warnings raised have been resolved.

test: check types in auto tests

---

Source/Plugins/Core/com.equella.core/js/__stories__/components/SettingsList.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/SettingsToggleSwitch.stories.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsToggleSwitch.tsx

This PR simply adds a storybook story to SettingsList.tsx, and also corrects the formatting of the documentation comments in that file.

Add story to settings list

---

Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/JQueryDiv.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts

replace window any and tinymce any with defined types

types: replace window any and tinymce any with defined types

---

autotest/IntegTester/ps/www/control.tsx

types: replace any in control tsx with defined types

---

.github/workflows/ci.yaml

For large features, we build them on a component branch which is then
merged back on feature completion - and various sub branches come off
them as each part of the feature is developed. As a result, we should
also add this to the list of branches to build both on merge (push)
and on PRs targeting them.

CI: Add GitHub actions trigger for component/** branches

---

README.md

[![openEQUELLA CI](https://github.com/openequella/openEQUELLA/workflows/openEQUELLA%20CI/badge.svg?branch=develop)](https://github.com/openequella/openEQUELLA/actions?query=workflow%3A%22openEQUELLA+CI%22+branch%3Adevelop)

docs: add github actions badge to readme

---

Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/settings/SettingsList.scala

https://github.com/openequella/openEQUELLA/issues/1337

Added new facet search settings category

---

NOTICE.md

Quick update to central copyright year.

docs: Bump copyright year to 2020

---

.github/workflows/ci.yaml

ci: Stop one set of tests failing cancelling others

---

project/build.properties

Upgrading to latest patch level of SBT. Regardless of what version of SBT you have installed locally, this file governs what is used for the build (unless explicitly set to override at runtime). As a result, we should have it up to date.
(Note: This however is not the latest version of SBT which is 1.3.10. It would be good to upgrade to that, but the build currently fails with anything greater than 1.1.x. I'll raise a ticket soon with further information.)

Upgrade SBT to latest 1.1.x version

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/ApiBatchOperationResponse.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/FacetedSearch/FacetedSearchClassificationResource.scala
autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/FacetedSearchClassificationApiTest.java

#1337 
Add a PUT endpoint which create or update multiple classifications, and a DELETE endpoint which deletes multiple classifications.

REST endpoints for batch operations on Faceted search classifications

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json
autotest/IntegTester/ps/package-lock.json
autotest/IntegTester/ps/package.json
oeq-ts-rest-api/package-lock.json
oeq-ts-rest-api/package.json
package-lock.json
package.json

this release is of particular interest because of speed improvements compiling/checking material ui
https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#speed-improvements

chore: upgrade typescript version to 3.9.2

---

Source/Plugins/Core/com.equella.core/js/__stories__/components/FacetDialog.stories.tsx
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/MessageDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetedSearchSettingsModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetedSearchSettingsPage.tsx

#1337 
Refactor Faceted search setting page to support editing and deleting facets.
Add a Jest test for this page.
Add a story for a new component `FacetDialog`.

Add functionality of editing and deleting facets

---

Source/Plugins/Core/com.equella.core/js/tsrc/schema/SchemaModule.ts

Initially with `schemaListSummary` to be used for the schema browser when configuring facet classifications. I did a quick test of this function with a local Jest test, and will later be covered when integrated with the UI component - which @SammyIsConfused is working on in parallel.
Will subsequently add a method to retrieve a schema, just wanted to keep this moving.
#1337

Add new SchemaModule.ts for schema interactions

---

autotest/OldTests/src/test/java/com/tle/webtests/test/viewing/ItemSummaryTest.java

Replace the testing url for ItemSummaryTest.

Replace the testing url for ItemSummaryTest

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json

Not sure how this crept in, but we don't need it so let's remove. (I know I've added this once before in another project by accident - I think by doing something like `npm install test` when planning to do `npm run test`.)

chore: Removed unused NPM `test` dependency

---

.github/workflows/ci.yaml

https://github.blog/changelog/2020-05-27-github-actions-v2-cache-actions/

ci: upgrade github cache action to version 2

---

Source/Plugins/Core/com.equella.core/js/.licensee.json
package.json

this would allow for catching new potential licensing issues, failing the build if a new package with an unknown/unapproved license is added.
also adds 0BSD, which is re-packaged ISC license, used by tslib.

test: ignore known issue packages

---

renovate.json

long term fix for #1764 
based off:
https://docs.renovatebot.com/configuration-options/#packagenames
https://docs.renovatebot.com/configuration-options/#rangestrategy

chore: change version strategy for tough cookie

---

Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx

Ensures that external links include the rel attribute with appropriate settings.

fix: add rel noopener and noreferrer to external links

---

README.md

docs: remove travis ci badge from readme, add language flags

---

Source/Plugins/Core/com.equella.core/js/__mocks__/getSearchResult.js
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchModule.test.ts
Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/tsrc/acl/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/config.ts
Source/Plugins/Core/com.equella.core/js/tsrc/entity/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/schema/SchemaModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/schema/index.ts
Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/settings/SettingsPageModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx

#1306 
The Search module provides a function that interacts with REST Client API to do a search.

Setup Search module to interact with the Search Rest Client API.

---

oeq-ts-rest-api/src/Auth.ts
oeq-ts-rest-api/src/AxiosInstance.ts
oeq-ts-rest-api/src/Common.ts
oeq-ts-rest-api/src/LegacyContent.ts
oeq-ts-rest-api/src/Schema.ts
oeq-ts-rest-api/src/Search.ts
oeq-ts-rest-api/src/Settings.ts
oeq-ts-rest-api/src/Utils.ts
oeq-ts-rest-api/src/index.ts

This includes a number of improvements:
1. It ensures that the return type of data is only narrowed when a validator is passed
2. it runs prettier on the rest client
3. it requires validators to be a type predicate, to ensure they match the assertion 

feat(typings): strengthen type checks for axios instance

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
Source/Plugins/Core/com.equella.core/src/com/tle/web/wizard/section/WizardBodySection.java

#1527 #1524 
1. Make some CSS changes in order to display three Wizard controls (Shuffle list, Auto-complete taxonomy and Grouping control) in full width with New UI turned on. 
2. Make Contribution right-hand navigation bar stick to the top of the page in New UI.

EBP improvements

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx

Separate each Search result item by a MUI Divider

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

Remove extra top padding for New UI legacy content.

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json

chore: remove downshift dependency

---

Source/Plugins/Core/com.equella.core/js/__stories__/components/ConfirmDialog.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/SettingsList.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/SettingsListControl.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/components/SettingsToggleSwitch.stories.tsx
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/SearchSettingFormControl.test.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/EntityList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingPageTemplate.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsListControl.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaNodeSelector.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/SchemaSelector.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/SearchPageSettings.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/components/DefaultSortOrderSetting.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/components/WebPageIndexSetting.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/facetedsearch/FacetedSearchSettingsPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/SearchFilterSettingsPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/UISettingEditor.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
package.json

addresses https://github.com/openequella/openEQUELLA/pull/1967#discussion_r450505439 can be autofixed by pre-commit hook and `npm run format:ts`

style: jsx only use curly brace for properties when needed

---

Source/Plugins/Core/com.equella.core/js/__stories__/components/SettingsList.stories.tsx
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/MimeTypeFilterEditingDialog.test.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderAddDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/ScreenOptions.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/components/DefaultSortOrderSetting.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/components/WebPageIndexSetting.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/SearchFilterSettingsPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/theme/ColorPickerComponent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
package.json

enables:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

style: omit optional boolean props, omit unneed fragments, use fragment shorthand

---

Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderDisclaimerDialog.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/EntityList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/EquellaListItem.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/Error.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/Loader.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/MessageInfo.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SearchResult.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsMenuContainer.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/react-visibility-sensor.d.ts
package.json

diff is easier to read with spacing changes hidden https://github.com/openequella/openEQUELLA/pull/2016/files?diff=split&w=1

refactor: for render only components prefer functional components

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx

Add drop shadows and curved edges to the thumbnails

---

Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx

Add CircularProgress spinner to LegacyPage

---

Source/Plugins/Core/com.equella.core/js/__mocks__/getSearchResult.js
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchModule.test.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx

#1306 
Update search page Jest test, including: 
1. adding new tests for Search page pagination and the sorting control; and
2. refactoring the tests for spinner and debounce query; and
3. updating mock data.

Jest tests for search page pagination and sorting

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx

Add thumbnail styles to the placeholder thumbnail

---

Source/Plugins/Core/com.equella.core/js/__mocks__/getCollectionsResp.js
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/CollectionModule.test.ts
Source/Plugins/Core/com.equella.core/js/tsrc/modules/CollectionsModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/modules/OEQHelpers.ts
Source/Plugins/Core/com.equella.core/js/tsrc/modules/README.md
Source/Plugins/Core/com.equella.core/js/tsrc/schema/SchemaModule.tsx

Here is the new CollectionsModule to be used in the Refine Search panel for collections.
With this I'm also starting to put in place a new folder where we will consolidate all our `XyzModule.ts` files. So I've also included a README.md to outline this.
#1306 

Add new CollectionsModule

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/RefineSearchPanel.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchOrderSelect.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPagination.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts

#1306 
Created a new component for the Refine search panel and integrated Search page with it. At the moment, some place holder refine controls are used.
Also slightly tweaked the structure of Search page so that the Refine panel is properly displayed.

Search page Refine panel

---

Source/Plugins/Core/com.equella.core/js/__mocks__/getSearchResult.js
Source/Plugins/Core/com.equella.core/js/__mocks__/searchresult_mock_data.ts
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
oeq-ts-rest-api/src/Search.ts

Update Search module and mock data to reflect additional attachment properties (mimeType, isPlaceholderThumb) being added to search2 rest endpoint.

Update Search module and mock data

---

project/Common.scala

This ensures that the NPM side of our builds (which are triggered by SBT) use the same fixed dependencies each time - as much as possible. In this fashion, we can then also ensure that the dependencies only change in our build if we intend them to.

chore(deps): Use npm ci for SBT managed NPM builds

---

buildspec.yml

Since #2076 has been closed, open another PR to add `npm run check` on `buildspec.yml`.

Execute 'npm run check' on Codebuild

---

renovate.json

One possible answer for https://github.com/openequella/openEQUELLA/pull/2061#issuecomment-659739319
documented at https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
E2E test for preset: https://github.com/renovatebot/renovate/blob/02e6817fb977ba82c13ce076759dbe179c37265d/test/e2e/package.json#L16

chore: configure renovate to update lockfiles weekly

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Set breakpoint width values to variables. 

---

README.md

resolve broken link to jdk 8 download, flagged in #2092 

docs: update link to jdk 8

---

Dev/docs/reactjs.md
Dev/old/DevGuideEvents.md
README.md
autotest/docs/statefultesting.md

docs: use https links in documentation

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Fix width issue with thumbnail preview

---

docker/.env
docker/docker-compose.yml

#1531 
Since Postgres docker image requires the environment variable POSTGRES_PASSWORD, added this variable to `docker-compose.yml `. Also added a `.env` file which is used to declare default environment variables.

Update docker compose configuration

---

.gitignore

This gets generated whenever opening the project in IntelliJ.
It should not be included as a committable file.
This gets generated whenever opening the project in IntelliJ.
It should not be included as a committable file.

Add .idea/.name to gitignore

---

Source/Plugins/Core/com.equella.core/js/__stories__/components/SearchResult.stories.tsx
Source/Plugins/Core/com.equella.core/js/__stories__/search/SearchResult.stories.tsx

Update the Storybook title of component SearchResult

---

Source/Plugins/Core/com.equella.core/resources/view/contribute/contribute.ftl
Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

#1983 
Aligns contribution page text styles to MUI typography. 

EBP: improve contribution page text styling

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

EBP: Fix action link dividers alignment

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

#1983 
- Removed indentation of p tags within manual data fix page
- Added consistent top and bottom padding to the buttons on the page

EBP: Improve Manual data fixes page styles

---

README.md

https://www.imagemagick.org/script/binary-releases.php is now a dead link, the downloads page has moved to https://imagemagick.org/script/download.php

docs: update imagemagick download link

---

package.json

documentation links to localhost cannot be validate on CI, ignore them.
This should resolve the build error related to a pgadmin localhost link in https://github.com/openequella/openEQUELLA/pull/2295

test: have remark lint ignore links to localhost

---

.github/workflows/ci.yaml
autotest/github-actions.conf
oeq-ts-rest-api/test/TestConfig.ts
oeq-ts-rest-api/test/auth.test.ts

#1480 ### Checklist
The purpose of this PR is to include tests of module `oeq-ts-rest-api` in GHA.

Include REST module's tests in GHA

---

autotest/Tests/src/main/java/com/tle/webtests/pageobject/ErrorPage.java

This test has been intermittently failing a fair bit this week. Non-reproducible without throttling my browser network speed, which highlighted to me that we need a wait.

Add a wait to ApidocsTest - testLoginNoAccess

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

#1983 
There was no width set on this button, which caused it to look broken. 
As was used in other places, I simply added the col2width variable. 
Broken:
Fixed:

EBP: Fix styles for "Add MIME Type" button

---

Source/Plugins/Core/com.equella.core/js/package-lock.json
Source/Plugins/Core/com.equella.core/js/package.json

build: remove unused create react class dependency

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/controls/universal/UniversalWebControlNew.scala

#1769 
The link duplicate check should match URL rather than description (display name).

Check link duplicates by matching URL rather than description.

---

oeq-ts-rest-api/src/AdvancedSearch.ts
oeq-ts-rest-api/test/AdvancedSearch.test.ts

Simple addition of function in REST module to support new endpoint.
#1306

feature(oeq-ts-rest-api): Support Advanced Search endpoint

---

oeq-ts-rest-api/src/RemoteSearch.ts
oeq-ts-rest-api/test/RemoteSearch.test.ts

Just another quick one for you @PenghaiZhang to support the new Remote Search endpoint.
#1306

feature(oeq-ts-rest-api): Support Remote Search endpoint

---

oeq-ts-rest-api/src/AxiosInstance.ts
oeq-ts-rest-api/src/Search.ts

replaces #1860, applies feedback from that PR

refactor: move transformer out of and after validation

---

Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts

As per request from @cathfitz .

chore(front-end): Change remoteSearchSelector title

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

- Made alignment of the item summary panel consistent across browsers (width: fit-content was used before, needed to add width: -moz-fit-content to make them work the same)
- Fixed the alignment of the navbar (some of the text and part of the logo were cut off before)
- Fixed alignment of the Select Summary Page button to be to the right of the Item title. 
- The summary/details tab bar divider now goes across the full length rather than roughly halfway
- Realigned the help text within the help button (before when that was shown it would cut off the first word of every line)
- Fixed faint line above Save button
- Made the Select Summary Page button round and the same size as the others
- Aligned the right side of the comment text box to the rest of the content in the panel
- Hidden a …

EBP: Improve styles for selection session item summary page

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx

don't wrap the category label

---

Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx

Close user menu when menu item is clicked

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx

Additionally, to improve UX show previous search results and
classifications while waiting for new search results.
Note I also pushed the `Classifications` component out of the main `SearchPage` component to stop unnecessary unmounting. To some degree this is temporary as @PenghaiZhang has refactored it into it's own `tsx` file in his current work.
Addresses #2716
https://user-images.githubusercontent.com/43919233/106989419-3ed0f800-67c6-11eb-9b62-5a8da5fa63c3.mp4

feature(front-end): Keep window position when changing page size

---

Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/RenderDataHelper.ts
Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
Source/Plugins/Core/com.equella.core/resources/view/selection/skinny-layout.ftl
Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

#2629 
This PR is to support using new search UI in Skinny Selection Session.
Changes can be basically categorised in three parts: 
1. EBP  changes to improve UI; and
2. Typescript side changes to make new search UI work properly in Skinny; and
3. Jest tests for above changes.
Here are two videos: [Moodle](https://streamable.com/3nwk95) and [Brightspace](https://streamable.com/4da7w2)

Support skinny selection session 

---

Source/Plugins/Core/com.equella.core/js/tsrc/fileuploader/InlineFileUploader.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/fileuploader/UploadActions.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/fileuploader/UploadList.tsx
autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/AbstractWizardControlPage.java
autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/controls/UniversalControl.java
autotest/Tests/src/main/java/com/tle/webtests/pageobject/wizard/controls/universal/FileUniversalControlType.java
autotest/Tests/src/test/scala/equellatests/sections/wizard/UniversalControl.scala

#2559 
This PR has two fixes:
1. Making sure deleting an uploaded file also deletes the file's child files.
2. Making sure the Attachment number restriction counts for unzipped files.
https://user-images.githubusercontent.com/47203811/108668166-c80a5d80-752e-11eb-9e87-7b7853af3876.mp4

Fix another two File Uploader issues

---

Source/Plugins/Core/com.equella.core/src/com/tle/video/thumbnail/VideoThumbnailGenerator.java

We need this for the Video Gallery in the New UI. It is unclear why
historically this was off - perhaps just because they weren't needed.

feat(server): Generate 'Preview' thumbnails for videos

---

renovate.json

chore: update renovate config to match new preset name

---

Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts

Update the placeholder text. Will re-target to the release branch later.

Update Search bar placeholder text

---

renovate.json

chore(renovate): Update renovate config param names

---

oeq-ts-rest-api/package.json

Not overly important, but be good to keep it inline while it sits within the same repo.

chore(oeq-ts-rest-api): Bump version

---

Dev/docs/clienterrors.md
Dev/docs/mainui.md

Missed some MD updates due to moving the front-end code, so here's a tweak.
(As an aside, we really need to go back and review and rework the content of this doco.)

chore(doc): Fix some links due to move of front-end

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/MimeTypeResource.scala

#2951 
Remove the ACL check for listing MIME types.

Remove the ACL check for listing MIME types.

---

react-front-end/__stories__/search/DisplayModeSelector.stories.tsx
react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
react-front-end/tsrc/search/SearchPage.tsx
react-front-end/tsrc/search/components/DisplayModeSelector.tsx

Apply the gallery visibility settings in New Search UI. 
https://user-images.githubusercontent.com/47203811/120432568-75f29700-c3bd-11eb-90c5-2a123721204c.mp4

Apply the gallery visibility settings in New Search UI

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

Some EBP work to make the Kaltura dialog look nicer.

EBP for the Kaltura dialog

---

buildspec.yml

Run npm script to build Kaltura TS Upload control on Codebuild.

chore: run npm build for Kaltura TS Upload control on Codebuild

---

Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss

Move styles of CSS class `btn` into a mixin and reuse it for Kaltura Submit button.

refactor: update Kaltura submit button styles

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/drm/DrmResource.scala
oeq-ts-rest-api/src/AxiosInstance.ts
oeq-ts-rest-api/src/Drm.ts
oeq-ts-rest-api/src/index.ts
oeq-ts-rest-api/test/Drm.test.ts
oeq-ts-rest-api/test/TestConfig.ts

This PR adds the support for DRM to REST module, including two functions talking to server and some type definitions.

feat: add support for DRM to REST module

---

react-front-end/package-lock.json
react-front-end/package.json

When upgrading to Node 16 this should probably have also been updated to
match.... I guess....

chore(deps): Update @types/node to match .nvmrc

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala

Rather than use the description from AttachmentBean, use the one from
Attachment as it supports any tweaks done in CustomAttachment instances
(such as Kaltura) to provide a string more suitable.
In turn, the resultant strings better align with those seen in the
LegacyUI.
(I also tweaked the broken attachment check to try and ensure consistency
with convention. No logical change though.)

fix(rest/search2): Use description from Attachment

---

react-front-end/.storybook/preview.ts
react-front-end/.storybook/preview.tsx
react-front-end/package-lock.json
react-front-end/package.json

Remove the dependency storybook-react-router which seems making some renovate PR failed.
I have uploaded some screenshots to confirm they are still working.

chore: remove storybook-react-router

---

buildspec.yml

More info at https://github.com/nvm-sh/nvm/issues/2574

build: attempt work around for NVM build issue

---

react-front-end/.storybook/preview-head.html
react-front-end/__stories__/pages/ThemePage.stories.tsx
react-front-end/tsrc/theme/ThemePage.tsx

Convert ThemePage to functional component.
Create a story for ThemePage.

refactor: ThemePage

---

autotest/OldTests/src/test/java/com/tle/webtests/test/searching/manage/BulkMetadataEditTest.java

First commit, add retryTest annotation.

fix(test): testBulkMetadataEdit timeout issue

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/users/UserQueryResource.scala
autotest/Tests/tests/facet/institution/acls/entries.xml
autotest/Tests/tests/facet/institution/acls/expressions.xml
autotest/Tests/tests/rest/institution/acls/entries.xml
autotest/Tests/tests/rest/institution/acls/expressions.xml
autotest/Tests/tests/vanilla/institution/acls/entries.xml
autotest/Tests/tests/vanilla/institution/acls/expressions.xml

Add LIST_USERS permission to autotest account and admin role.
Add ACL LIST_USERS checker for userquery api.

fix(server): add missing LIST_USERS ACL

---

react-front-end/tsrc/components/ShuffleBox.tsx

chore: make shuffle box full width

---

project/build.properties
sbt

Also upgrades the SBT wrapper.

chore(build): upgrade SBT to 1.5.6

---

project/plugins.sbt

These two plugins greatly assist in review and maintenance of dependencies in SBT.

build: add sbt-dependency-check and dependencyTree

---

react-front-end/package-lock.json
react-front-end/package.json

Remove deps query-string since it's no longer used after #3792 

chore(deps): remove query-string

---

.github/workflows/ci.yaml

We are currently having memory issues, but on other branches where we use ubuntu-latest things are working. So this is a test.

build(gha): use ubuntu-latest for functional-tests

---

Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/services/impl/UrlServiceImpl.java

Get schema based on both request and URI.

fix: correctly set base url in error page under ssl env

---

docker/README.md
docker/docker-build/Dockerfile
docker/docker-build/entrypoint-buildenv
docker/docker-build/install-chromedriver

To assist with the evaluation of build issues through easy access to a
clean build environment. (For example, we're currently having odd
test failures on GitHub Actions, however it's working on local dev
machines and AWS CodeBuild.)

build(docker): add full docker based build environment

---

react-front-end/tsrc/components/UserSearch.tsx

Add a callback onError
Correctly show 404 and error message
https://user-images.githubusercontent.com/92769668/156957434-b1b046df-0449-490b-8dcb-6068f36ac948.mp4

fix: correctly handle error for UserSearch dialog

---

Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala

Make sure the attachment beans used to get thumbnail link use the real version rather than 0.

fix: make sure attachment beans use the real version

---

Source/Plugins/Core/com.equella.core/swaggerui/package.json
Source/Plugins/Core/com.equella.core/test/javascript/package.json
autotest/IntegTester/ps/package.json
oeq-ts-rest-api/package.json
package.json
react-front-end/package.json

As discussed in #3701 , we probably no longer need to specify the NPM version in `package.json`.

chore: don't specify NPM version in 'package.json'

---

.github/workflows/ci.yaml
CONTRIBUTING.md
Dev/learningedge-config/defaults/optional-config.properties.default
Installer/resources/script/app-script.xml
Installer/src/com/dytech/edge/installer/application/FfmpegCallback.java
Source/Plugins/Core/com.equella.core/plugin-jpf.xml
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/FfmpegException.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/FfmpegService.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/FfmpegServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/guice/FfmpegModule.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/workflow/video/VideoServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/video/thumbnail/VideoThumbnailGenerator.java
Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
Source/Tools/UpgradeInstallation/src/com/tle/upgrade/UpgradeMain.java
Source/Tools/UpgradeInstallation/src/com/tle/upgrade/upgraders/AddLibAvConfig.java
autotest/README.md
docker/Dockerfile
docker/defaults.xml
docker/docker-build/Dockerfile
project/InstallOptions.scala

Replace libav with ffmpeg (#697): 
* docs (comments and readme files)
* ffmpeg/libav module
* installer
* upgrader
final optional configs output:
* ci
* docker

refactor: replace libav with ffmpeg

---

.github/workflows/ci.yaml
CONTRIBUTING.md
Dev/learningedge-config/defaults/optional-config.properties.default
Installer/data/server/learningedge-config/optional-config.properties
Installer/resources/script/app-script.xml
Installer/src/com/dytech/edge/installer/application/FfmpegCallback.java
Source/Plugins/Core/com.equella.core/plugin-jpf.xml
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/FfmpegException.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/FfmpegService.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/FfmpegServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/ffmpeg/guice/FfmpegModule.java
Source/Plugins/Core/com.equella.core/src/com/tle/core/workflow/video/VideoServiceImpl.java
Source/Plugins/Core/com.equella.core/src/com/tle/video/thumbnail/VideoThumbnailGenerator.java
Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
Source/Tools/UpgradeInstallation/src/com/tle/upgrade/UpgradeMain.java
Source/Tools/UpgradeInstallation/src/com/tle/upgrade/upgraders/AddLibAvConfig.java
autotest/README.md
docker/Dockerfile
docker/defaults.xml
docker/docker-build/Dockerfile
project/InstallOptions.scala

fix installer for #4115
Missing changes in `Installer/data/server/learningedge-config/optional-config.properties`

fix: installer for replacing libav with ffmepg

---

react-front-end/__tests__/tsrc/components/wizard/WizardSimpleTermSelector.test.tsx
react-front-end/__tests__/tsrc/myresources/MyResourcesPage.test.tsx
react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
react-front-end/package-lock.json
react-front-end/package.json
react-front-end/tsrc/search/components/DisplayModeSelector.tsx

This PR adds the code changes required by `@types/jest` v29.

Chore/update "types/jest" to v29

---

oeq-ts-rest-api/gen-io-ts/package-lock.json
oeq-ts-rest-api/gen-io-ts/package.json
oeq-ts-rest-api/package-lock.json
oeq-ts-rest-api/package.json
react-front-end/package-lock.json
react-front-end/package.json

Fix #4778.
Update package-lock.json for react-front-end

fix: update dependency @types/node to v18.17.5 

---

Source/Plugins/Core/com.equella.core/src/com/tle/web/remoting/resteasy/CorsInterceptor.java
Source/Server/equellaserver/build.sbt

Fix #4706.
I can't find the related changes in the change log:  
https://github.com/resteasy/resteasy/releases/tag/3.15.6.Final
Here is the error:
Update `allow-headers` fix the issue.

fix: resteasyversion

---

package-lock.json
package.json
react-front-end/package-lock.json
react-front-end/package.json

To fix #4732.
Update package-lock.json for react-front-end.

fix: babel monorepo

---

react-front-end/package-lock.json
react-front-end/package.json

To fix #4818.
Updated package-lock.json for react-front-end. 

fix: luxon 3.x

---

package-lock.json
package.json
react-front-end/package-lock.json
react-front-end/package.json

chore(deps): update babel monorepo to v7.22.11

---

build.sbt

Format `build.sbt` to fix #4843.

chore(deps): update dependency com.oracle.database.jdbc:ojdbc8 to v23

---

react-front-end/package-lock.json
react-front-end/package.json

chore(deps): update dependency rewire to v7 

---

package-lock.json
package.json
react-front-end/package-lock.json
react-front-end/package.json

chore(deps): update babel monorepo to v7.22.15

---

oeq-ts-rest-api/gen-io-ts/package-lock.json
oeq-ts-rest-api/gen-io-ts/package.json
oeq-ts-rest-api/package-lock.json
oeq-ts-rest-api/package.json
react-front-end/package-lock.json
react-front-end/package.json

chore(deps): update dependency @types/node to v18.17.15

---

react-front-end/package-lock.json
react-front-end/package.json

chore(deps): update dependency @babel/core to v7.22.17

---

autotest/github-actions.conf

Add the configuration required for running OauthTest.

chore: update GHA configuration for OauthTest

---

.well-known/funding-manifest-urls

Used for https://floss.fund based funding.

chore(funding): add Apereo funding file
